### ISSUE TITLE
pubnote search: journal_name together with the journal volume

### ISSUE THREAD

**Issue by drjova** [inspirehep/inspirehep#1056]
Currently searches like `Phys. Rev. D95 (2017) 123002` don't work because `D` is omitted by GROBID:
```bash
$ curl 'https://grobid.inspirebeta.net/api/processCitation' --data-raw 'citations=Phys. Rev. D95 (2017) 123002'    
```

```xml                                                                                                              
<biblStruct>
	<analytic>
		<title/>
	</analytic>
	<monogr>
		<title level="j">Phys. Rev</title>
		<imprint>
			<biblScope unit="volume">95</biblScope>
			<biblScope unit="page">123002</biblScope>
			<date type="published" when="2017" />
		</imprint>
	</monogr>
</biblStruct>
```

```py
{
   'reference': {
       'publication_info': {
        'journal_volume': '95',
        'journal_title': 'Phys. Rev',
        'year': 2017,
        'page_start': '123002'
       }
    }
}
```

Currently `inspire-matcher` doesn't exact match on `journal_title`, instead we have to do a prefix search on `journal_title` i.e. `Phys. Rev` should match `Phys. Rev D`.

**Acceptance:**
The following search should work:
- [ ] Phys. Rev. D95 (2017) 123002
- [ ] Eur Phys J C73 2531
- [ ] M. Dine, W. Fischler and M. Srednicki, Phys. Lett. B104 (1981) 19

**Tech Notes:**
* Increase the matches from `1` to  up to `5`  https://github.com/inspirehep/inspirehep/blob/master/backend/inspirehep/matcher/api.py#L61
* Create a similar [configuration](https://github.com/inspirehep/inspirehep/blob/master/backend/inspirehep/matcher/config.py#L62) but instead of exact match in `journal_title` we should do a `prefix` match (and update the [match_reference](https://github.com/inspirehep/inspirehep/blob/master/backend/inspirehep/matcher/api.py#L113)). The configuration is used from [inspire-matcher](https://github.com/inspirehep/inspire-matcher)

**Tech Notes:**
* Change [this](https://github.com/inspirehep/inspirehep/blob/master/backend/inspirehep/matcher/api.py#L61) to `if len(matched_recids) == 1:`
* We should create a similar function to [match_reference](https://github.com/inspirehep/inspirehep/blob/master/backend/inspirehep/matcher/api.py#L77) function which instead of using https://github.com/inspirehep/inspirehep/blob/master/backend/inspirehep/matcher/api.py#L122 should get all the `recid` from the matched references and return only the first five. Common parts of `match_reference` and this new function should be separated and reused in both.
* Rename [this](https://github.com/inspirehep/inspirehep/blob/master/backend/inspirehep/matcher/api.py#L132) to `match_reference_control_numbers`  and instead of using ` match_reference` should use the function from the previous step.
* Update the [query](https://github.com/inspirehep/inspirehep/blob/master/backend/inspirehep/search/api.py#L220-L225)  to do a query for all recid returned from `match_reference_control_numbers`

**Comment by drjova** [comment]
IRL we decided to increase the matched records to `5` instead of `1` https://github.com/inspirehep/inspirehep/blob/master/backend/inspirehep/matcher/api.py#L61

**Comment by michamos** [comment]
Reopening because the change on https://github.com/inspirehep/inspirehep/blob/6b321d50b5aae129630088b3886f6d9f07fc1140/backend/inspirehep/matcher/api.py#L61 doesn't make sense:
* it allows up to five matches (so if the ref without journal letter is ambiguous, you'lle still get results), but only returns the first one which defeats the purpose, as there's no reason for the first one to be the correct one
* it also modifies the actual reference matcher (which we'll use later with refextract) to allow ambiguous matches, which is probably not what we want.
