### ISSUE TITLE
add speaker to title of calendar events when exporting seminars

### ISSUE THREAD

**Issue by drjova** [inspirehep/inspirehep#1073]
If there are more than one speakers add only the first speaker and add `et al.`.

The title format of the event should be:

```firstname lastname − title```

With a long dash in the middle and no comma between first and last, same format as in the UI.

more details

 

**TECH NOTES:**

    The format should be ```firstname lastname - title``` where the dash is a long dash. If there are several authors, it should be ```firstname lastname et. al. - title```

Create a util function which returns the formatted title to use in both https://github.com/inspirehep/inspirehep/blob/5929fb0ed76817a2099330150f7d180c0dc3569f/ui/src/seminars/components/ExportToCalendarAction/google.js#L19 and https://github.com/inspirehep/inspirehep/blob/5929fb0ed76817a2099330150f7d180c0dc3569f/ui/src/seminars/components/ExportToCalendarAction/ics.js#L36

**Comment by harunurhan** [comment]
Done by https://github.com/inspirehep/inspirehep/commit/95173723332de39ca4527008f002d9b4e247242e
