### ISSUE TITLE
embedded search errors causes redirection

### ISSUE THREAD

**Issue by harunurhan** [inspirehep/inspirehep#1081]
When there is an error is returned from any search API request, we redirect to an error page on the client side. This is correct for search pages, but not for detail pages (embedded searches)

So we need to parameterize https://github.com/inspirehep/inspirehep/blob/f9d36c5b008494599c6d66a531b45ad8c3eea12f/ui/src/actions/search.js#L37 this, set it only when needed.

**Comment by drjova** [comment]
TECH NOTES:

* In the config https://github.com/inspirehep/inspirehep/blob/f9d36c5b008494599c6d66a531b45ad8c3eea12f/ui/src/search/config.js#L33-L86 add `redirectableError: true` for the following namespaces
  * `LITERATURE_NS`
  * `AUTHORS_NS`
  * `JOBS_NS`
  * `INSTITUTIONS_NS`
  * `CONFERENCES_NS`
  * `SEMINARS_NS`
  * `EXPERIMENTS_NS`    
And for the rest we should add   `redirectableError: false`

* Replace https://github.com/inspirehep/inspirehep/blob/f9d36c5b008494599c6d66a531b45ad8c3eea12f/ui/src/actions/search.js#L37 reading the config of the namespace, we can do something like the following:

```js

function searchError(namespace, errorPayload) {
 const { redirectableError } = searchConfig[namespace];
  return {
    type: SEARCH_ERROR,
    payload: { ...errorPayload, namespace },
    meta: {redirectableError},
  };
}


```
