### ISSUE TITLE
Assign Papers UI

### ISSUE THREAD

**Issue by harunurhan** [inspirehep/inspirehep#1095]
### single paper

- I click on the checkbox next to the paper
- I click on the button Assign and select the dropdown option 'Assign to this author'.
- I get a confirmation modal: "Assign 11 papers to this author?" witH the buttons: Confirm and Cancel.
- I click confirm.
- Display a success alert (TBC) for a few seconds
- The assigned icon appears next to the paper.

### multiple papers 

- click on their checkboxes and click on assign on top. The assigned icon appears next to each paper.

### single paper

- I click on the checkbox next to the paper.
- I click on the Assign button and select the dropdown option: "Assign to another author"
- Then, I get a drawer with the following
   <img width="616" alt="Screenshot 2019-10-08 at 18 18 12" src="https://user-images.githubusercontent.com/4868667/86783588-cc960a80-c060-11ea-8205-afeafd65c6db.png">
  - `New author` option is same as `unassign` functionality
- If I click on an author name in the drawer, I get the author profile in a new tab.
- I browse through different profiles and when I decide which author to select, I click the button 'Assign' on that author result.
- When I click Assign, I get a success alert that goes away after a few seconds and the profile of author2 opens in a new tab.
- The modal closes and I get back to the profile of the author1. The paper that belongs to author2 has disappeared from the list of papers.

### multiple papers

- do exactly the same, only click on the assign button on top of the paper list.

### single paper

- I click on the checkbox next to the paper.
- I click on the Assign button and I select the dropdown option: "Unassign".
- I get a confirmation modal: "Remove 11 papers from this author profile?" with the buttons Confirm and Cancel
- I click confirm.
- Display a success alert (TBC) for a few seconds
- The modal closes and I get back to the profile of the author1. The selected paper has disappeared from the list of papers. 

### multiple papers

- do exactly the same, only click on the button on top of the paper list. 

## New Facets

<img width="218" alt="Screenshot 2020-07-09 at 18 08 33" src="https://user-images.githubusercontent.com/24955201/87167777-c9538680-c2cd-11ea-8f62-b9e2c9540af7.png">

### Batch assign dropdown (multiple papers)

<img width="668" alt="Screenshot 2020-07-10 at 16 51 07" src="https://user-images.githubusercontent.com/24955201/87167710-a9bc5e00-c2cd-11ea-95bd-156ec90f7974.png">

### Selection display

<img width="404" alt="Screenshot 2020-07-09 at 18 17 30" src="https://user-images.githubusercontent.com/24955201/87064790-7d8ed780-c210-11ea-8d72-84dc2d18280f.png">

Moved from JIRA Issue: https://its.cern.ch/jira/browse/INSPIR-2769

**Comment by harunurhan** [comment]
@StellaCh how about error display? if operation fails

**Comment by StellaCh** [comment]
An alert should be ok in that case, what do you think @harunurhan ?

**Comment by harunurhan** [comment]
yes, but where? since action can be done in multiple ways (different buttons on the UI), there is no obvious place to display `Alert` (https://ant.design/components/alert/), I was thinking it would be better to display the error in a modal or https://ant.design/components/message/

**Comment by StellaCh** [comment]
I will create some mockups about that after the discussion with the curators.

**Comment by harunurhan** [comment]
I think opening pages in new tab automatically after success is not the best? can't we just put the links in the success message and user can click if needed? @StellaCh

**Comment by StellaCh** [comment]
Yes, good point, in a success modal that users should close once they read it

**Comment by harunurhan** [comment]
@StellaCh we're going to use `Modal` for success and error messages? not https://ant.design/components/message/ or https://ant.design/components/notification/

**Comment by StellaCh** [comment]
yes these 2 work, the requirement is that when a new author is created, it should not disappear after a few seconds, as the curator might need to click on the new profile to see the new info
