### ISSUE TITLE
Desirialization of search results takes up to 25% of the response time

### ISSUE THREAD

**Issue by drjova** [inspirehep/inspirehep#1098]
The goal is to reduce desirialzation time as much as possible, based on this [profiling](https://inspirehep.zulipchat.com/user_uploads/4640/patlHPW3EKcu9AUzSX3a__yV/wUMJos2K.svg) and improve the overall response time for search queries.

**Comment by michamos** [comment]
spending 20% of the time in `strip_empty_values`. That function is expensive as it's recursive (removes all empty values from leaves, then walks up the tree recursively to remove now empty nodes), and it's called multiple times.
