### ISSUE TITLE
Add the curated_relation field to hits for assign view

### ISSUE THREAD

**Issue by monaawi** [inspirehep/inspirehep#1102]
### SS
<img width="382" alt="Screenshot 2020-07-15 at 12 57 22" src="https://user-images.githubusercontent.com/24955201/87537463-ec4db400-c69a-11ea-8bcd-1337c6583e3b.png">

### Tech Notes
In #1100 we already set assignView for the ```AuthorPublications```. 
1. Create a class that derives from ```JSONSERIALIZER``` that will be used for ```literature_json_list_response```. It should override the ```serialize_search```. Check if there is an author param and user is superuser or curator. If yes,it should do an ES query using the ```author``` from the request params and the control numbers of the current ```search_results```, the query should be looking for literature records with these records ids that have ```curated_relation : True``` for the given author (nested query). Then, populate ```curated_relation``` within these search results. And call super. (query is similar to https://github.com/inspirehep/inspirehep/blob/1e9c1df61ff75a0b715cf6bb5a051c83431447a9/backend/inspirehep/search/aggregations.py#L258-L300)
2. In the ```LiteratureListWrappedSchema``` in ```get_ui_display```, set the ```curated_relation``` from the metadata.
3. Create the component with the ```< FileExclamationTwoTone / >``` icon (add a tooltip when you hover over the icon: *Unclaimed paper. Click on the Claim button to claim or remove it from the profile*) and dropdown menu. 
4. In LiteratureItem check if assignView is True and if the value of the curated_relation for the current user (author) is False in metadata. If the conditions are met display created component.

**Comment by monaawi** [comment]
Separated from #1095

**Comment by StellaCh** [comment]
I need to update the icon. Since we changed the color of the titles to black, the gray icon won't stand out anymore

**Comment by StellaCh** [comment]
I updated the screenshot. Let's use <FileExclamationTwoTone />

**Comment by pazembrz** [comment]
`curated_relation` flag is separate for every author in every paper. Currently UI have access to only first 10 authors, to get all authors for every paper will be to expensive as response size will be too big and filtering through 5k authors to get proper one will be slow. 
There might be few solution to this:
1. On ui serializer we can put list of all curated_relations for each paper and then on UI check if current author is on this list
2. On LiteratureListWrappedSchema  serializer query ES/DB for author and current paper to check if relation is curated.
Maybe there is better solution. 
This requires more refinement.
