### ISSUE TITLE
Add source and date

### ISSUE THREAD

**Issue by StellaCh** [inspirehep/inspirehep#1109]
Curators need more context in order to take a decision on whether they should approve a conflict. They don’t know where and when the conflict came from.

Therefore, we need to add info about the source (publisher/arxiv) and date/time (to know how recent is the update in case we have multiple).

Add this info in the conflict panel before the Accept all/Reject all buttons as in the screenshot:

<img width="442" alt="Screenshot 2020-07-30 at 11 44 53" src="https://user-images.githubusercontent.com/24955201/88908467-2ea9f000-d25a-11ea-8663-c72ba0b9b96c.png">

Date/time should be displayed in the same format as we display it in the editor history (as in the screenshot above)

**Comment by StellaCh** [comment]
As all conflicts are from the same source and at the same time, we should display this info as an overall attribute, and not for each conflict individually.

**Comment by harunurhan** [comment]
First we need `ng2-json-editor` to support displaying metadata of conflicts, so we would need to add a way to pass a `patchesHeadingTemplate` or something similar, which will be then rendered just like in the mock-up. We have many examples of custom templates already, should be easy to figure out.

Conflicts are set in [merging.py](https://github.com/inspirehep/inspire-next/blob/4d116e13e625dc4ea4a8b9a3ab2bcf6261ecec77/inspirehep/modules/workflows/tasks/merging.py#L86). So we need to add a new field like `conflicts_metadata` in `extra_data` where we we will store current datetime and the update source.

As the last step, we will read `conflicts_metadata` from `extra_data` of the workflow object (which can be accessed anywhere by [using the global state](https://github.com/inspirehep/record-editor/blob/f463b7556a7468cf0c65ba7fcf09dd264f80e418/src/app/core/services/global-app-state.service.ts#L32)), and use it in the template which will be passed to `ng2-json-editor`.

Do not forget this conflict_metadata object can be undefined for current workflows which have conflicts, so we need to make sure UI doesn't blow up for this.
