### ISSUE TITLE
Author splitting

### ISSUE THREAD

**Issue by StellaCh** [inspirehep/inspirehep#1110]
This is the biggest blocker to use the merger in the editor.

Example:
https://inspirehep.net/editor/holdingpen/2348549

Authors that are obviously the same, are split and repeated. In the example above, there are 2 new authors, but these create 6 entries that need approval. This is confusing, we need to have only 1 new conflict per author. In addition, the conflicts are mixed, so we see conflicts for Akahori then Nagai and then Akahori again, making it very hard to understand what needs approval.

Expected behavior:
Only 1 conflict entry per new author. 
Ideally, the author entry would follow the ordering as in the paper: eg. If the 1st author is added, we'll see the new addition in the beginning of the author list.

**Comment by pazembrz** [comment]
After discussion with Micha we suggest as follows:
1. Add ordering information for authors input dictionary so we could keep ordering of authors.
2. Ignore root from merged conflicts
3. Before flattening MERGE conflict looks like this:
 `   
  ('MANUAL_MERGE',
    ('authors',),
    (
      pmap(<ROOT>),
      pmap(<HEAD>),
       pmap(<UPDATE>)
)),
`
4. Before flattening conflicts, take out all `MANUAL_MERGE` and do as follows:
  - Remove/Ignore ROOT
  - Update merged result with HEAD from conflict
  - make UPDATE from conflict as actual conflict
5. Remove all positioning information form author dictionary.

This should result in less conflicts in editor, also should allow to achieve behavior of getting HEAD when dismissed all conflicts.
