### ISSUE TITLE
Release experiments

### ISSUE THREAD

**Issue by StellaCh** [inspirehep/inspirehep#1115]
- In literature detailed page, link the experiments to the corresponding page. 
Example: https://inspirehep.net/literature/1809147 link CERN-LHC-ATLAS to https://inspirehep.net/experiments/1108541

-  Also, link experiments in Authors Search page and Author detail page. Example author: https://inspirehep.net/authors/1032472

- Add Experiments dropdown in search menu and extra Experiments tab after Institutions menu. 

- Hide Experiments and Institutions in the tab under a `More...` menu.
<img width="505" alt="Screenshot 2020-07-30 at 10 52 52" src="https://user-images.githubusercontent.com/24955201/88902944-27cbaf00-d253-11ea-9f16-81f9038a389f.png">

- Submission form should be visible only to curators.

**TECH NOTES** : 
* ```ExperimentList``` and ```AcceleratorExperimentsList``` do the same thing. There should be only one component, get label as prop. Change this component to have a Link to the experiment in ```renderExperiment```. 
* In the ```SearchScopeSelect``` remove the check for experiments so that they appear in the namespace dropdown. Make sure they appear in the correct order.
* In the ```HeaderMenu```, add a new menu item for Experiments. See how things fit in smaller screens. If needed, add the `More..`

**Comment by MJedr** [comment]
I think that also linking experiments in Authors Search page and Author detail page is necessary.

**Comment by StellaCh** [comment]
You're right, I missed this!

**Comment by monaawi** [comment]
@StellaCh What about in the Job detail page? we have experiments there as well

**Comment by monaawi** [comment]
@StellaCh  also we don't have the submissions experiments yet

**Comment by StellaCh** [comment]
Good catch yes, everywhere we have experiments.
It's ok, we can release like we do for Institutions

**Comment by MJedr** [comment]
@StellaCh for other links when they are active we hover them. Should we do it also for the links in the dropdown menu (experiments and institutions)?

**Comment by StellaCh** [comment]
yes thanks!

**Comment by StellaCh** [comment]
I forgot to add that next to the experiments dropdown in the tab menu we should display the 'New' green tag. No need to add it in the search dropdown
