### ISSUE TITLE
Bibedit links are wrong inspirehep.net -> old.inspirehep.net

### ISSUE THREAD

**Issue by drjova** [inspirehep/inspirehep#1116]
**Describe the bug**

At least in the following places the link to Bibedit is wrong:

- [ ] https://github.com/inspirehep/inspire-next/blob/master/inspirehep/modules/authors/templates/authors/tickets/curation_needed.html#L21

It should be `old.inspirehep.net` instead.

**Comment by harunurhan** [comment]
Are 2 below even used? because that's part of the old literature submissions

**Comment by drjova** [comment]
@harunurhan that's true, I just copy paste from zulip without checking.
