### ISSUE TITLE
Create CI for author-disambiguation

### ISSUE THREAD

**Issue by MJedr** [inspirehep/inspirehep#1117]
Currently, we don't have a CI set for the repository, so there is no way to verify if the changes are correct. We need to set it up (also linters must be configured).

**Comment by harunurhan** [comment]
We can use github actions, which would be very similar to [unit test setup on inspirehep ](https://github.com/inspirehep/inspirehep/blob/master/.github/workflows/backend-unit.yml), that runs https://github.com/inspirehep/inspire-disambiguation/blob/master/run-tests.sh

**Comment by harunurhan** [comment]
Actually let's take this opportunity to merge `inspire-disambugation` repo into this one, under `disambiguation` folder.
