### ISSUE TITLE
Wrong `/api/facet` response, instead of `aggs` it returns `hits`

### ISSUE THREAD

**Issue by drjova** [inspirehep/inspirehep#1136]
This example https://inspirehep.net/api/literature/facets?sort=mostrecent&size=25&page=1&q=Particles%201%20%282018%29%20%20138 returns `hits` instead of `aggs` which is wrong. The query is `Particles 1 (2018)  138`

**Comment by MJedr** [comment]
Facets are not showing for this query https://inspirehep.net/literature?sort=mostrecent&size=25&page=1&q=Particles%201%20%282018%29%20138

**Comment by michamos** [comment]
Yes, because the `/literature/facets endpoints doesn't return `aggregations` but full `hits`.

**Comment by MJedr** [comment]
I think that for some searches it still doesn't work https://inspirehep.net/literature?sort=mostrecent&size=25&page=1&q=Phys.%20Rev.%20D95%20%282017%29%20123002

**Comment by drjova** [comment]
We don't return facets for pubnote search

**Comment by monaawi** [comment]
Yes, this is what we decided to do for now
