### ISSUE TITLE
Create RT tickets as nobody instead of cli user

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspirehep#1144]
Currently RT tickets on hep and next are created as user `cli`. This causes various problems (harder for curators to reassign to other people, no automatic assignment to the curator closing the tickets leading to bad statistics), so it would be better to create them without any user associated.

**Comment by tsgit** [comment]
if the owner isn't set in ticket create via api it defaults to Nobody.
that's preferable to `cli`

however I don't think the owner is set on ticket creation. Look at the ticket history

https://rt.inspirehep.net/Ticket/History.html?id=1046227

an email is send, and then the status is changed new->open and the owner is set and then status is changed open->new
that may have to do more with the scrips active for the Queue
https://rt.inspirehep.net/Admin/Queues/Scrips.html?id=50

**Comment by tsgit** [comment]
compare with an older ticket, which didn't send out email
https://rt.inspirehep.net/Ticket/History.html?id=776455

**Comment by tsgit** [comment]
@michamos 
so the author workflow creates the ticket and then replies to it with a message to the requestor
and then it edits the ticket to switch it back from open to new.
so the entire ticket handling logic is in the workflow
it could be done with a queue specific scrip in RT
or the two scrips which change status on correspond and owner on correspond could be modified to not act on API interactions with user `cli`
e.g. https://rt.inspirehep.net/Admin/Scrips/Modify.html?id=42&From=47 already skips the owner update when the `$Actor = $RT::SystemUser->id;` 

either way there is currently an awkward confusion of logic between RT scrips and workflows

**Comment by tsgit** [comment]
for reference -- cli numeric user id is  265407

> sudo perl -e 'use lib qw(/opt/rt-4.2/lib); use RT -init; use RT::User; print "systemuser : [", $RT::SystemUser->id, "]\n"; $cli = RT::User->new(); $cli->Load("cli");  print "cli : [", $cli->id, "]\n";'
systemuser : [1]
cli : [265407]

**Comment by tsgit** [comment]
sometime later when the submission is accepted in the holdingpen UI the ticket is resolved via API. at that point it would be good to set the `Owner ` of the ticket to the logged in curator processing the submission.
