### ISSUE TITLE
Most recent sorting for lit

### ISSUE THREAD

**Issue by drjova** [inspirehep/inspirehep#1166]
When sorting `Most Recent`, sort articles with the same day by `control_number`

**Comment by StellaCh** [comment]
low priority

**Comment by drjova** [comment]
TECH NOTES:

* As we have in `leastrecent` https://github.com/inspirehep/inspirehep/blob/master/backend/inspirehep/records/config.py#L613 add in https://github.com/inspirehep/inspirehep/blob/master/backend/inspirehep/records/config.py#L607 

```json
{
        "mostrecent": {
            "title": "Most Recent",
            "fields": ["-earliest_date", "control_number"],
            "default_order": "asc",
            "order": 1,
        },
}
```
