### ISSUE TITLE
move match_references to matcher module

### ISSUE THREAD

**Issue by drjova** [inspirehep/inspirehep#1181]
Move the remaining matcher functionality to hep:

* `match_references` https://github.com/inspirehep/inspire-next/blob/master/inspirehep/modules/refextract/matcher.py#L112 to https://github.com/inspirehep/inspirehep/blob/master/backend/inspirehep/matcher/api.py
* Move `/linked_references` endpoint https://github.com/inspirehep/inspire-next/blob/master/inspirehep/modules/editor/api.py#L231 

### Tech Notes

1. Move  `match_references` https://github.com/inspirehep/inspire-next/blob/master/inspirehep/modules/refextract/matcher.py#L112 to https://github.com/inspirehep/inspirehep/blob/master/backend/inspirehep/matcher/api.py and add tests
2. Move https://github.com/inspirehep/inspire-next/blob/master/inspirehep/modules/editor/api.py#L81-L108 to `editor` views, update ingress to point to `inspirehep` and add tests
3. Move https://github.com/inspirehep/inspire-next/blob/master/inspirehep/modules/editor/api.py#L231-L235 to `matcher` views, update ingress to point to `inspirehep` and add tests
4. Remove the endpoints from `next`.

**Comment by MJedr** [comment]
I am not sure if we can remove ```match_references``` from next since it is used multiple times in workflows
https://github.com/inspirehep/inspire-next/blob/d237fe351bdfc2d04f5276a1d10e4198cfdd3165/inspirehep/modules/workflows/tasks/actions.py#L424-L438
