### ISSUE TITLE
hep-th preprint not loaded in INSPIRE

### ISSUE THREAD

**Issue by fschwenn** [inspirehep/inspirehep#1187]
**Describe the bug**
The hep-th-preprint https://arxiv.org/abs/2008.03852 is not in INSPIRE.
According to INSPIRE, the workflow https://inspirehep.net/holdingpen/2435112 is completed.

**Expected behavior**
hep-th preprints should be loaded automatically. If this for some reason fails the workflow should be at least in error.

**Comment by ksachs** [comment]
the user submission is from 2020-08-11T01:15:53
the arxiv harvest comes later: 2020-08-11T02:34:07
To me it's a flaw in the WF logic: an autoingest WF (like arXiv hep-th) should not be stopped by a user submission waiting in the HP. Details to be discussed.

**Comment by pazembrz** [comment]
Yes in this WF history we can see that it was stopped as this one https://inspirehep.net/api/holdingpen/2434198 came in.
