### ISSUE TITLE
post to https://inspirehep.net/callback/workflows/robotupload frequently fails

### ISSUE THREAD

**Issue by tsgit** [inspirehep/inspirehep#1188]
**Describe the bug**
The callbacks from completed bibuploads initiated by workflows frequently fail with
`Gateway Error`, `Timeout`, `Internal Server Error`, etc.

These are simple HTTP POST to https://inspirehep.net/callback/workflows/robotupload
with a json payload containing the wf nonce, record-id, and possibly the marcxml

**To Reproduce**

These are intermittent but recurrent problems, with several callbacks (out of O(10^2))  failing every day, despite the callback being wrapped in a `@retry`

**Expected behavior**

Successful POST and HTTP status 200.

**Additional context**
The callbacks are necessary to complete the workflow. They also confirm the record id for the uploaded record. A failed callback requires manual cleanup.

**Comment by michamos** [comment]
Endpoint not used any longer now that legacy is gone.
