### ISSUE TITLE
rt entpoints to hep

### ISSUE THREAD

**Issue by drjova** [inspirehep/inspirehep#1191]
Move `rt` [endpoints](https://github.com/inspirehep/inspire-next/blob/master/inspirehep/modules/editor/api.py) and change the ingress to point to hep.

**Tech notes** : 
* Move [these](https://github.com/inspirehep/inspire-next/blob/92c9f08aba093421f343e39ba936f8df0c6168eb/inspirehep/modules/editor/api.py#L111-L165) endpoints to hep to ```editor/views``` as they are
* Change the permission from ```@editor_permission``` to ```@login_required_with_roles([Roles.cataloger.value])```
* All the methods needed from the rt module are already in hep so you can just use them. (Note: these methods are not tested)
* Tests for this on next are simply mocking RT and checking the correct methods are called, we could do the same
* Remove the endpoints from next
* Ask Ben to change the ingress to hep

**Comment by drjova** [comment]
@MJedr did we change the ingress to point to hep?

**Comment by MJedr** [comment]
No, the PR is still waiting to be merged https://github.com/inspirehep/inspire-next/pull/3959
