### ISSUE TITLE
Experiments are not linked in literature detail

### ISSUE THREAD

**Issue by drjova** [inspirehep/inspirehep#1197]
Experiment [FNAL-E-0362](https://inspirehep.net/experiments/1110005) should be linked in https://inspirehep.net/literature/10337 but instead it's just text.

<img width="949" alt="Screenshot 2020-08-13 at 12 32 09" src="https://user-images.githubusercontent.com/4287772/90124675-16a99480-dd61-11ea-96b2-d594e2948ab6.png">

**Comment by pazembrz** [comment]
Looks like all 3 experiments should be linked as all of them have record.$ref field in metadata:
```json
"accelerator_experiments":[{"legacy_name":"FNAL-E-0244","record":{"$ref":"https://inspirehep.net/api/experiments/1110111"}},{"legacy_name":"FNAL-E-0245","record":{"$ref":"https://inspirehep.net/api/experiments/1110109"}},{"legacy_name":"FNAL-E-0362","record":{"$ref":"https://inspirehep.net/api/experiments/1110005"}}]
```

**Comment by monaawi** [comment]
No, the ```record.$ref``` isn't there for the request with the ui content-type. So it must be an issue in the ui serializers for ```accelerator_experiments```

**Comment by drjova** [comment]
I think the issue is with the serializer, we're resolving the experiment record and there is no ``record.$ref`` anymore for the UI https://github.com/inspirehep/inspirehep/blob/41e91c73c58a8d7e49f93410c0a9706b4e6ff417/backend/inspirehep/records/marshmallow/common/accelerator_experiment.py#L18

**Comment by drjova** [comment]
I just replicate the issue https://github.com/inspirehep/inspirehep/pull/1196

**Comment by pazembrz** [comment]
I'm working on it... Actually now I'm running tests now...
