### ISSUE TITLE
Claim final tasks

### ISSUE THREAD

**Issue by StellaCh** [inspirehep/inspirehep#1207]
1. Missing tooltip. 
When you hover over the < FileExclamationTwoTone / > icon, add a tooltip: 
Unclaimed paper. Click on the Claim button to claim or remove it from the profile

2. Claim button should be next to cite_all, currently they are not aligned 
<img width="218" alt="Screenshot 2020-08-18 at 10 12 33" src="https://user-images.githubusercontent.com/24955201/90487942-6d391900-e13b-11ea-8cf1-b341c1709e34.png">

3. Claim all button. If I don't select any paper and I hover over the Claim all button, I still see the dropdown options, which is confusing. If there're no papers selected, we should add the tooltip "Please select the papers you want to claim or remove from the profile." and make the button disabled

4. Weird bug: I claimed some papers and then for some seconds I saw the following screen. A few seconds after that, it refreshed back to the author profile page:
<img width="1281" alt="Screenshot 2020-08-18 at 10 17 01" src="https://user-images.githubusercontent.com/24955201/90489175-36640280-e13d-11ea-85d5-0b4a5b161c71.png">

5. Sometimes, when I assigned a paper to another author and clicked 'Assigned', the author page wasn't updated with the latest papers and was still showing the removed paper. When I refreshed the page, I could no longer see it in the list. Same for claiming. If I click "this is my paper" , I have to refresh or try several times, before it appears claimed in the profile.

6. When I open the drawer and assign a paper to an author, it takes several seconds before making the change. We therefore need to warn users that the system is working on it by displaying a spinner.

7. When I assign papers to another author, sometimes I receive a success notification, and sometimes I don't. The success notification should always be displayed and should stay in the page until it gets closed by a user. Currently, it displays the author id that links to the profile. Can we display the link to the author name instead?

**Comment by harunurhan** [comment]
5. won't be fixed here we'll create a new task.

**Comment by harunurhan** [comment]
4. is related to issues with QA data, it doesn't happen on PROD.
