### ISSUE TITLE
sync reindexing when record is updated

### ISSUE THREAD

**Issue by harunurhan** [inspirehep/inspirehep#1218]
**Is your feature request related to a problem? Please describe.**
For `/assign`, we would like to return `success` after all records update and indexed successfully so that user can see the new data after the action.

**Describe the solution you'd like**
`record.update(sync_reindex=true)`

TECH:
* Add a parameter to `put` request called `wait_for_index` or something similar.
* We have to use https://flask.palletsprojects.com/en/1.1.x/api/#flask.has_request_context to check if there is request context in base record update. If it is then check if `wait_for_index` is inside request parameter.
* Update https://github.com/inspirehep/inspirehep/blob/22f728bead6b016a5b9326e3a5d2e45f91e0e845/backend/inspirehep/indexer/tasks.py#L62 by adding new parameters: `record` which will contain whole record, and `igore-records_sync`. 
* do not require `uuid_parameter` anymore if `record` is provided.
* when `record` is provided use it for indexing.
* if `ignore_records_sync` is `True` then ignore this part of indexing https://github.com/inspirehep/inspirehep/blob/22f728bead6b016a5b9326e3a5d2e45f91e0e845/backend/inspirehep/indexer/tasks.py#L89-L104 (As this will happen after commit)

IMPORTANT: Be sure that indexing is not modifying record data! (Our serializers likes to do this...)

**Comment by michamos** [comment]
This doesn't make sense any longer, as we do the whole assignment asynchronously.
