### ISSUE TITLE
Linked references to detailed page

### ISSUE THREAD

**Issue by StellaCh** [inspirehep/inspirehep#1227]
When I click on a linked reference in the editor, it leads to the api link https://labs.inspirehep.net/api/literature/….. It should link to the record instead so https://labs.inspirehep.net/api/literature/…... It's the same link we have under 'View in literature' under the record field

**Comment by harunurhan** [comment]
- Change the config https://github.com/inspirehep/record-editor/blob/d588f318587d4027968a05c7cdf9f84224d1fce8/src/app/shared/config/commons.ts#L98-L111 to not to link `old.inspirehep.net` but just removing `/api` in the link. This is not mentioned in the task but should be fixed
- Remove `/api` from the `$ref` link here: https://github.com/inspirehep/record-editor/blob/42089b71478623a97abdd21abd6636f2fc8f221c/src/app/shared/components/reference-brief/reference-brief.component.html#L4 
- Remove `/api` from the `$ref` link here: https://github.com/inspirehep/record-editor/blob/42089b71478623a97abdd21abd6636f2fc8f221c/src/app/shared/components/author-brief/author-brief.component.html#L4 (this is not mentioned in the task but should be fixed)
