### ISSUE TITLE
Display pdf hidden as preview

### ISSUE THREAD

**Issue by StellaCh** [inspirehep/inspirehep#1228]
If there is an attached pdf offer it as preview, even if pdf is hidden (e.g. arXiv)

**TECH NOTES:**
* Remove these lines https://github.com/inspirehep/inspirehep/blob/master/backend/inspirehep/records/api/literature.py#L353-L375
* Remigrate all records
* Check records with `hidden` documents and make sure are on S3.

**Comment by StellaCh** [comment]
@michamos to investigate whether this is acceptable from publishers due to privacy issues

**Comment by michamos** [comment]
It's ok, we can display also hidden PDFs.

**Comment by drjova** [comment]
@michamos  Currently we don't process `hidden` files:

```json
{
    "documents": [
      {
        "hidden": true,
        "key": "arXiv:astro-ph_9812133.pdf",
        "source": "arxiv",
        "url": "http://inspire-afs-web2.cern.ch/var/data/files/g41/821160/arXiv%3Aastro-ph_9812133.pdf%3B1"
      }
    ],
}
```

If we want to enable preview we should process them on `hep`, is it something that we want?

**Comment by michamos** [comment]
We'll need to do it before switching off legacy in a any case.

**Comment by StellaCh** [comment]
For which other use cases we need to process hidden files before switching off legacy?

**Comment by michamos** [comment]
We don't want to lose them and we'll stop migrating records after switching off legacy, so we necessarily need to migrate them before switching off legacy.
