### ISSUE TITLE
Improve autocompletion

### ISSUE THREAD

**Issue by StellaCh** [inspirehep/inspirehep#1230]
>Affiliation picker only shows 5 choices, can't scroll beyond 5 – It would be nice to have more so as not to have to leave and search Institutions 

>Some Affiliations don’t show in the picker – Example: “Caltech” - Today, I could not get it to give just “Caltech” as a choice. When I typed in “Caltech”, I got all the affiliations that have the word in them, but had to type in “Division of Physics” (without the word “Caltech” at all) to get it to offer “Caltech” as a choice.

It is impossible to add some experiments or affiliations because they are not in the proposed (short) list, even if the exact value is given.
Need better sort and/or no truncation

**Comment by drjova** [comment]
We'll try the search as you type solution, https://www.elastic.co/guide/en/elasticsearch/reference/7.x/search-as-you-type.html

**Comment by harunurhan** [comment]
This should be probably done for all completion fields.

**Comment by drjova** [comment]
**TECH NOTES:**

We're using already ES `7.1.1` on `prod`

* Change the mapping type to `search_as_you_type` for `affiliation_suggest ` https://github.com/inspirehep/inspirehep/blob/b6aa07abab5504eb5744ef74d161a1f5c1e2f208/backend/inspirehep/search/mappings/v7/records/institutions.json#L67
* Remap and reindex institutions

**Comment by drjova** [comment]
You're right it needs `7.2` thanks!

**Comment by drjova** [comment]
ES team will release 7.8 in few weeks. We should revisit this issue when it's done.

**Comment by MJedr** [comment]
**TECH NOTES**
Add `size` parameter [here](https://github.com/inspirehep/inspirehep/blob/636879322e68b4a9b83c40f4d76873351f9f573a/backend/inspirehep/records/config.py#L430) and set it to 20
