### ISSUE TITLE
Bug in the order of query parser

### ISSUE THREAD

**Issue by ksachs** [inspirehep/inspirehep#1239]
**Describe the bug**
`find a butler, j and title cms and title experiment and date 2008` 
on labs yields too many results.

**To Reproduce**
https://inspirehep.net/literature?sort=mostrecent&size=25&page=1&q=find%20a%20butler%2C%20j%20and%20title%20cms%20and%20title%20experiment%20and%20date%202008
yields 92 results

**Expected behavior**
on [legacy](https://old.inspirehep.net/search?ln=en&p=find+a+butler%2C+j+and+title+cms+and+title+experiment+and+date+2008&of=hb&action_search=Search&sf=earliestdate&so=d) or with [different order of arguments](https://inspirehep.net/literature?sort=mostrecent&size=25&page=1&q=find%20a%20butler%2C%20j%20and%20date%202008%20and%20title%20cms%20and%20title%20experiment)
yields 1 result, which is correct

**Additional context**
https://rt.inspirehep.net/Ticket/Display.html?id=1053317

**Comment by StellaCh** [comment]
See more: https://inspirehep.zulipchat.com/#narrow/stream/195298-experts/topic/bug.20in.20query.20parser.3F
