### ISSUE TITLE
bibtex: use article document type if there is a `journal_title` for theses

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspirehep#1249]
For the bibtex citation format, we have some logic to map our records to bibtex document types: https://github.com/inspirehep/inspirehep/blob/06a55b50721836c5f623385756e6250c788b378b/backend/inspirehep/records/marshmallow/literature/bibtex.py#L52-L65

Also for theses and book chapters, we should use article as soon as there is a `journal_title` (like for conference papers).

**Comment by drjova** [comment]
It also needs reindexing
