### ISSUE TITLE
Allow direct linking of records in the editor

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspirehep#1255]
Currently, the editor can link records (i.e. populate the info in `$ref`) only when autocompleting a different field. We need to have a method for inputting manually `$ref` even when there is no separate field to autocomplete.

**Comment by harunurhan** [comment]
https://github.com/inveniosoftware-contrib/ng2-json-editor/tree/master/src/ref-field should be change to allow manual editing, probably should be enabled via config.

we should also change the schema to validate `$ref`s properly to have `/api/<collection>/<number>`.
