### ISSUE TITLE
allow filtering of API response

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspirehep#1256]
A user reports:
> In the old Marc-XML interface, I was limiting the information I obtain from Inspire by using "&ot=001,970,100,..." etc. Is there a way to do something similar in the new API? I don't want to waste the bandwidth, as the default output is very detailed.

This request to be able to get only parts of the record in the response has come up several times and would be useful to do. We could do it only for search results (similar to legacy) very easily by having a query parameter that gets converted in the search classes to the ES `_source` parameter.

**Comment by harunurhan** [comment]
We can modify [search factory](https://github.com/inspirehep/inspirehep/blob/65a2f645ebcc5916659baa449b4820ebd150e760/backend/inspirehep/search/factories/search.py#L19) to override `_source` if it is passed as a request param.

API could look like this:
`?fields=authors,references,acquisition_source`


Fields should be validated against top level schema fields, and return `400` with a meaningful error message to API users.
