### ISSUE TITLE
seminars in profile

### ISSUE THREAD

**Issue by StellaCh** [inspirehep/inspirehep#1258]
Make the following changes in the seminar tab in the author profile:

1) Remove the seminar number from the tab. If there're 0 seminars, don't display the tab.
2) Add the warning banner under the seminar tab as in the mockup:
"Disclaimer: Please note that the list of seminars is managed by users and INSPIRE makes no claims as to its completeness and accuracy."
<img width="683" alt="Screenshot 2020-08-28 at 13 02 08" src="https://user-images.githubusercontent.com/24955201/91566114-79935200-e943-11ea-9937-da1cfb180de5.png">
    
**TECH**
In author DetailPageContainer:
- remove [TabNameWithCount ](https://github.com/inspirehep/inspirehep/blob/65a2f645ebcc5916659baa449b4820ebd150e760/ui/src/authors/containers/DetailPageContainer/DetailPageContainer.jsx#L199-L203) component 
- render conditionally the tab with Seminars based on `seminarsCount` constant
- add the warning banner (`<Alert message="Warning" type="warning" showIcon />`) inside ContentBox before `AuthorSeminars` component with the text "Disclaimer: Please note that the list of seminars is managed by users and INSPIRE makes no claims as to its completeness and accuracy."

**Comment by StellaCh** [comment]
@harunurhan the seminars tab has a typo in the literature detailed page: https://inspirebeta.net/literature/1800013
Semianrs -> Seminars

**Comment by harunurhan** [comment]
@StellaCh oh missed it during the review, will fix it soon.
