### ISSUE TITLE
Run integration tests under different DB name

### ISSUE THREAD

**Issue by harunurhan** [inspirehep/inspirehep#1268]
So that it won't interfere with the local dev setup and e2e tests.

TECH: `SQLALCHEMY_DATABASE_URI` env variable is used to determine DB to which Inspire is connecting.  If before test it will be set to different db name: for example `INVENIO_SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://inspirehep:inspirehep@localhost:5432/inspire_2` it will use it for the tests.

This variable can be set on executing test command:
```bash
INVENIO_SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://inspirehep:inspirehep@localhost:5432/inspire_2 poetry run pytest/tests/integration
```
in https://github.com/inspirehep/inspirehep/blob/d524f1fe523b61da6d3e47ea678eccd56b91a5a4/backend/run-tests.sh#L10
Or it can be hard-coded in https://github.com/inspirehep/inspirehep/blob/d524f1fe523b61da6d3e47ea678eccd56b91a5a4/backend/tests/integration/conftest.py#L37 
Please note that setting INVENIO_SQLALCHEMY_DATABASE_URI will still override value set in conftest.

BTW: Do we need [this](https://github.com/inspirehep/inspirehep/blob/d524f1fe523b61da6d3e47ea678eccd56b91a5a4/backend/tests/integration/conftest.py#L47-L57) ? Looks like it's value is overwritten if we use `INVENIO_SQLALCHEMY_DATABASE_URI`

Don't forget to also change ES index prefix by setting `SEARCH_INDEX_PREFIX` env, otherwise running tests will delete ES indexes used by local env.

Same changes should work for integration-async

**Comment by MJedr** [comment]
- Some services (matcher, oai, migrator) have hardcoded index names in the config, so we have to find a proper method for updating them. One idea is to create a function which will update them based on the prefix, eg. 
```
def get_prefixed_index(index_name, index_prefix=None):
    prefix = index_prefix or current_app.config.get("SEARCH_INDEX_PREFIX")
    if prefix not in index_name:
          return prefix + index_name
    return index_name
```
but when used directly in config it gives the ``` RuntimeError: Working outside of application context.``` error.
- Some tests [like this one](https://github.com/inspirehep/inspirehep/blob/08ae47665713aa0cce90572b72e7f2eb710cd0d6/backend/tests/integration/indexer/test_cli.py#L206) remove aliases from the ES.
One solution might be to create the proper aliases pointing to the test indices.
