### ISSUE TITLE
Limit authors to 10 in latex formats

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspirehep#1271]
Reported by Ya'ou. Currently, we add all authors to the LaTeX formats. If a paper has more than 10 authors, e.g. https://inspirehep.net/literature/1710056, we should display `first_author, \emph{et al.}` instead of all the authors.

**Comment by harunurhan** [comment]
Change https://github.com/inspirehep/inspirehep/blob/beb564068dfc9e0457cf5d662fd1360bac60a441/backend/inspirehep/records/marshmallow/literature/latex.py#L30 to limit the number of authors.
