### ISSUE TITLE
disambiguation retry on ES errors

### ISSUE THREAD

**Issue by drjova** [inspirehep/inspirehep#1302]
At the moment disambiguation fails on ES errors, instead we should retry.

**Tech notes** :
* The error happens for the [scan for get_signatures](https://github.com/inspirehep/inspire-disambiguation/blob/c6402e7367ee33107ab6f0ae33d84a7a62b0c48d/inspire_disambiguation/core/es/readers.py#L149). We could try increasing the ```ES_TIMEOUT``` param 
* We can also set the ```max_retries=10, retry_on_timeout=True``` for the [es instance](https://github.com/inspirehep/inspire-disambiguation/blob/c6402e7367ee33107ab6f0ae33d84a7a62b0c48d/inspire_disambiguation/core/es/readers.py#L47).

**Comment by harunurhan** [comment]
This should be done either after #1117 is finished or before it's in progress already.
