### ISSUE TITLE
handle manual merge records on hep

### ISSUE THREAD

**Issue by drjova** [inspirehep/inspirehep#1303]
On record update we should check if the `deleted_records` field has changed, if yes we should handle the case as follows:

* Get the `pid_value` from `deleted_record.$ref`, delete the record and mark its pid_value as `REDIRECTED` to the `pid_value` of the record we are updating.

We don't want to use invenio redirect as it's not working with deleted records. We also don't want to manually reassign pids as after reassignment we still want to have access to old record by its pid (somehow).
There are also additional requirements, all of them are mentioned in zulip thread: https://inspirehep.zulipchat.com/#narrow/stream/122202-devel/topic/handle.20manual.20merge/near/211614611

We probably have to create our own redirection system which will be aware of old (redirected) records, it should also automatically redirect all pids which were redirected by record. For example:
We have records:
Rec A: {'control_number':1234}
Rec B: {control_number': 2345, 'deleted_records':[{'$ref':'.../literature/1234'}]}
Rec C:{control_number': 3456, 'deleted_records':[{'$ref':'.../literature/2345'}]}

Record C should automatically redirect also pid 1234 to itself as record B which is redirecting record A is now redirected to record C. 
Still we should be access Record A and B by their pids (while they are still redirected to record C)

We also shouldn't allow to redirect redirected pid to another record:
Rec A: {'control_number':1234}
Rec B: {control_number': 2345, 'deleted_records':[{'$ref':'.../literature/1234'}]}
Rec C:{control_number': 3456, 'deleted_records':[{'$ref':'.../literature/1234'}]}
This is not allowed.

Looks like old record should also have an info which record replaces it like it was done on NEXT: https://github.com/inspirehep/inspire-next/blob/d237fe351bdfc2d04f5276a1d10e4198cfdd3165/inspirehep/modules/workflows/tasks/manual_merging.py#L181

**Comment by pazembrz** [comment]
https://github.com/pazembrz/inspirehep/tree/%231378_handle_manual_merge Here is my almost ready implementation with reassigning pids approach which we found out is not what we want.

**Comment by pazembrz** [comment]
Current:

`Records`:
[get_uuid_from_pid_value](https://github.com/inspirehep/inspirehep/blob/4db5dfce77feee19850a0d839ebcb8268b7013ef/backend/inspirehep/records/api/base.py#L62-L67)
[get_pid_for_pid](https://github.com/inspirehep/inspirehep/blob/a7d56913dc8d634067d7067c59d3615b562887e4/backend/inspirehep/records/utils.py#L112-L119)

`Pidstore`:
[Minter.get_all_pidstore_pids](https://github.com/inspirehep/inspirehep/blob/1311f1e5f14569a242586456c5e2e8cf8a4fdfd4/backend/inspirehep/pidstore/minters/base.py#L109-L119)
[get_pid_type_from_recid](https://github.com/inspirehep/inspirehep/blob/bcdeb79519b58e0dabd4c1d1378eb42be144559a/backend/inspirehep/pidstore/api/base.py#L134-L146) - This don't have to be aware of redirect?

`Orcid`:
[get_literature_recirds_for_orcid](https://github.com/inspirehep/inspirehep/blob/e8b0ae5b200a6a6c9e626e8c8a864ad80ec2b1b2/backend/inspirehep/orcid/utils.py#L163-L172)

`Indexer`:
[get_query_records_to_index](https://github.com/inspirehep/inspirehep/blob/08ae47665713aa0cce90572b72e7f2eb710cd0d6/backend/inspirehep/indexer/cli.py#L50-L64)

`Merger`:
[migrate_from_mirror_run_step](https://github.com/inspirehep/inspirehep/blob/bcdeb79519b58e0dabd4c1d1378eb42be144559a/backend/inspirehep/migrator/tasks.py#L126-L129)

Next:
`merger workflow`:
[merge_articles](https://github.com/inspirehep/inspire-next/blob/584a88e5b06f89294c195aac5423354b7c5b34ea/inspirehep/modules/workflows/tasks/merging.py#L67-L68)


What should be updated additionally:
[get_linked_pids_from_field](https://github.com/inspirehep/inspirehep/blob/4db5dfce77feee19850a0d839ebcb8268b7013ef/backend/inspirehep/records/api/base.py#L190)
[get_pid_from_record_uri](https://github.com/inspirehep/inspirehep/blob/bcdeb79519b58e0dabd4c1d1378eb42be144559a/backend/inspirehep/pidstore/api/base.py#L124-L131) ?


[All PersistentIdentifier.query usage](https://github.com/inspirehep/inspirehep/search?q=PersistentIdentifier.query)
