### ISSUE TITLE
Clickable buttons

### ISSUE THREAD

**Issue by StellaCh** [inspirehep/inspirehep#1340]
When I make the window smaller, the menu buttons 'Save', undo etc are not clickable anymore

**Comment by drjova** [comment]
@StellaCh do you have a specific example? I tested it in all browsers (Chrome, Firefox, Safari) and I couldn't reproduce this issue.

**Comment by StellaCh** [comment]
I just tried a few examples, some of them worked and some didn't. It's tricky because it doesn't happen regularly, try make the window smaller eg.833x440 in https://inspirehep.net/editor/holdingpen/2541187
You can not click on Save or Undo or (!)

**Comment by drjova** [comment]
Which browser did you use?

**Comment by StellaCh** [comment]
Chrome

**Comment by drjova** [comment]
@StellaCh thanks for the details.
