### ISSUE TITLE
Test CDS spider on QA

### ISSUE THREAD

**Issue by drjova** [inspirehep/inspirehep#1344]
Enable and test CDS spider on QA.

Add a `cds-weekly` harvest with the following sets:
* `cerncds:lhcb-conf`
* `cerncds:cms-pas`
* `cerncds:atlas-conf`
* `cerncds:lhcb-pub`
* `forINSPIRE`

[Example configuration](https://github.com/inspirehep/kubernetes/blob/ceb3ba456248c15dd705744fdfd685c62db3ef6f/next/base/config/inspirehep.cfg#L286-L294)

Acceptance:
* Run the harvest and check for any major errors.

**Comment by drjova** [comment]
@michamos is it something specific to test for the content?

**Comment by michamos** [comment]
We need to add the following sets:
* `cerncds:lhcb-conf`
* `cerncds:cms-pas`
* `cerncds:atlas-conf`
* `cerncds:lhcb-pub`
* `forINSPIRE`
