### ISSUE TITLE
Comments on Literature submission are not preserved

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspirehep#1356]
On the Literature submission form, there is a comment box at the bottom. However, the information in that box seems not to be added to the workflow. This functionality was probably lost when switching to the new submission form.

This should be fixed: comments should be added as `_private_notes` instead of being dropped.

**Comment by harunurhan** [comment]
Indeed `comments` field is ignored here https://github.com/inspirehep/inspirehep/blob/master/backend/inspirehep/submissions/marshmallow/literature.py#L162

We should just call https://github.com/inspirehep/inspire-schemas/blob/ab35f92f667cea0974cb54f717ef6913ba30cf65/inspire_schemas/builders/literature.py#L336 with `comments`
