### ISSUE TITLE
Institutions should have <DeletedAlert />

### ISSUE THREAD

**Issue by harunurhan** [inspirehep/inspirehep#1364]
Currently, if an admin/cataloger accesses the detail page of a deleted institutions, there is no alert that it's deleted.

**Comment by michamos** [comment]
this should be the case for all collections, not sure whether institutions are the only place it is missing.

**Comment by harunurhan** [comment]
I had a quick look already, and yes it's only missing there. I think it could be a good idea to actually think about a detail page wrapper component that handles these common behaviour for all records.
