### ISSUE TITLE
File handling in editor

### ISSUE THREAD

**Issue by StellaCh** [inspirehep/inspirehep#1365]
As a curator, I want to upload a file or delete it in the record editor.

See discussion in: https://inspirehep.zulipchat.com/#narrow/stream/208581-ready-for.20refinement/topic/files.20in.20editor

**Comment by harunurhan** [comment]
Previous file handling UI is still there and wouldn't require much modification to be able to work new files backend.

- `record-editor` is using `titleDropdownItemTemplateNames` config of `ng2-json-editor` which basically renders a dropdown menu under the field's title https://github.com/inspirehep/inspirehep/blob/d524f1fe523b61da6d3e47ea678eccd56b91a5a4/record-editor/src/app/shared/config/hep/core.config.ts#L299-L301
- Currently a template which just renders `<re-file-upload-button>` component https://github.com/inspirehep/inspirehep/blob/d524f1fe523b61da6d3e47ea678eccd56b91a5a4/record-editor/src/app/shared/components/file-upload-button/file-upload-button.component.ts#L31
