### ISSUE TITLE
Add date updated in profile

### ISSUE THREAD

**Issue by StellaCh** [inspirehep/inspirehep#1373]
Add info on the date an author profile was last updated. This should be displayed to all users regardless of whether they are logged in.

This way we can ensure that authors are kept informed for changes in their profiles. This is important both for curators and for respecting the data privacy rules.

![Screenshot 2020-10-01 at 14 04 37](https://user-images.githubusercontent.com/24955201/94807106-72061380-03ef-11eb-88c7-fe222c43bcd2.png)

On the bottom right corner of the author profile, add "Updated on"+date. 
* Position: It should be similar to the position we use in the jobs display, so bottom right before the action buttons: https://inspirehep.net/jobs/1807706
* Color: It should be similar to the gray we use for the numbering of the ordering in the search results (#1), so #AAAAAA 
* Date format: It should be similar to the format we use in the jobs deadline, so MON dd, YYYY: https://inspirehep.net/jobs/1807706

**Comment by harunurhan** [comment]
@StellaCh could you explain where you wanna display this exactly? and is it going to only displayed catalogers?

**Comment by StellaCh** [comment]
I updated the issue with more details and mockups.

**Comment by harunurhan** [comment]
- update time is `record._updated` in the detail page
- use `moment` and `moment-timezone` to format the raw date
  - date is UTC, but we should display in user's timezone
  - similar was done for seminars: https://github.com/inspirehep/inspirehep/blob/77ac942603f0bfe6fe44179872b25b1ee5d6bb5a/ui/src/seminars/components/SeminarDateTimes.jsx#L6

**Comment by StellaCh** [comment]
Just a comment to avoid confusion: if the record hasn't had any update so far, the date displayed should be the date created, again with the same text "Updated on+date"
