### ISSUE TITLE
Remove email addresses from search results

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspirehep#1374]
For privacy reasons and to make it easier to comply with our terms of use, we should remove email addresses from the search results, for all collections for the public API.

Tech:
Literature:
On UI response we have 
 [FirstAuthorSchemaV1](https://github.com/inspirehep/inspirehep/blob/a7d56913dc8d634067d7067c59d3615b562887e4/backend/inspirehep/records/marshmallow/literature/common/author.py#L25) with email field.
There is also https://github.com/inspirehep/inspirehep/blob/183ee02c49f99518cb5c937b66db5db39aeb9917/backend/inspirehep/records/marshmallow/literature/ui.py#L40 Which contains `acquisition_source.email`. This field should be excluded. But we don't want to exclude it from Detail page, so probably we have to create separate schema for literature ui field.
https://github.com/inspirehep/inspirehep/blob/183ee02c49f99518cb5c937b66db5db39aeb9917/backend/inspirehep/records/marshmallow/literature/es.py#L39 This one will also contain `acquisition_source.email` and it's displayed instead of ui_field when content_type is json.

Authors ([AuthorsListSchema](https://github.com/inspirehep/inspirehep/blob/a7d56913dc8d634067d7067c59d3615b562887e4/backend/inspirehep/records/marshmallow/authors/ui.py#L84)): extend field `Meta.exclude` with `email_addresses` field.

Jobs: [JobsListSchema](https://github.com/inspirehep/inspirehep/blob/a7d56913dc8d634067d7067c59d3615b562887e4/backend/inspirehep/records/marshmallow/jobs/ui.py#L56) Here we have emails in `acquisition_source.email`, `contact_details[].email`, `reference_letters.emails[]`. All of those should be excluded from schema.

Seminars:
[SeminarsListSchema](https://github.com/inspirehep/inspirehep/blob/a7d56913dc8d634067d7067c59d3615b562887e4/backend/inspirehep/records/marshmallow/seminars/ui.py#L32) Here emails are stored in  `acquisition_source.email`, `contact_details[].email`. All of those should be excluded from schema.

Conferences:
[ConferencesListSchema](https://github.com/inspirehep/inspirehep/blob/183ee02c49f99518cb5c937b66db5db39aeb9917/backend/inspirehep/records/marshmallow/conferences/ui.py#L19) Here we have only `contact_details` list which should be excluded from schema.

Institutions: Nothing in here

Experiments: Nothing in here

Be sure not to remove emails from Detail pages. If some schemas are reused fordetail page and search page, split schemas so we won't re-use detail page schema on search page.
Remember to check separately `application/vnd+inspire.record.ui+json` and `application/json`.

**Comment by StellaCh** [comment]
What's the value it brings if we keep it in other collections?
