### ISSUE TITLE
Order conflicts alphabetically

### ISSUE THREAD

**Issue by StellaCh** [inspirehep/inspirehep#1388]
All updates that come to a record, appear in a random order in the editor. It would be useful to display the conflicts alphabetically, so that is easier for cataloguers to go through them if they are not grouped.

**Comment by michamos** [comment]
@StellaCh wouldn't it be better to have conflicts in the order in which they appear in the editor instead?

**Comment by StellaCh** [comment]
The issue came up from the fact that additions can't be grouped. So if you have 100 new authors and in between 1 publication note update, and you'd like to accept all author updates, you might mistakenly click 'Accept all', because you missed the pubnote update, as it's hard to browse through the results.
Is the order the fields appear important for curators?

**Comment by harunurhan** [comment]
Previously they requested that fields menu should be ordered alphabetically, rather than edit view order. So I think they would prefer alphabetically here too.

**Comment by harunurhan** [comment]
So this changes concern the core library `ng2-json-editor`, we already have `sortAlphabetically`  https://github.com/inveniosoftware-contrib/ng2-json-editor/blob/cf4b9e0b5205c4007097ad220a6a713ff05528f8/src/shared/pipes/sort-alphabetically.pipe.ts#L34, we should share this logic.

And we can `sort` the patches by `path` https://github.com/inveniosoftware-contrib/ng2-json-editor/blob/cf4b9e0b5205c4007097ad220a6a713ff05528f8/src/bottom-console/patches-console-tab/patches-console-tab.component.ts#L59
