### ISSUE TITLE
Add '10 authors' facet in institutions

### ISSUE THREAD

**Issue by StellaCh** [inspirehep/inspirehep#1389]
From user:
> I find the "10 authors or less" filter very helpful. It would be nice to add this to the institution page. For example, I like to see the papers written by theorists at my institution over the last month, but don't want to include all the RHIC, DUNE, ATLAS, etc. papers.

Add the facet '10 authors or less' in the institution detailed page

**Comment by harunurhan** [comment]
Use `hep_author_count_aggregation` for https://github.com/inspirehep/inspirehep/blob/183ee02c49f99518cb5c937b66db5db39aeb9917/backend/inspirehep/search/facets.py#L306
