### ISSUE TITLE
Implement simple author disambiguation

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspirehep#1390]
Following investigations of the current "rabbit" legacy algorithm (thanks @tsgit), this is a high-level overview of how the simple author disambiguation should work.

First we need to define a few concepts:
* *signature*: an element of `authors` in a Literature record
* *author profile*: an Authors record
* *relevant metadata*: metadata inside a signature used as an input for disambiguation (i.e. name, ids, email, affiliations), or on the paper (collaboration).

For every non-deleted modified Literature record (all `_collections` with `hep` schema, not only `Literature`):
1. Collect all signatures that have changed/been added compared to the previous version (added = new `signature_uuid`, changed = same `signature_uuid`, but relevant metadata has been modified). All of those need to be re-disambiguated (if the record is new, all signatures need to be disambiguated).
2. For each of those, search its IDs and emails in author records (similar to the exact match in the workflow). If there's only one result, assign the signature to that author.
3. For each remaining non-assigned signature, do some basic normalization of the name (TBD, might be done in ES directly through analyzers) and check whether there is a unique author record with the same assigned normalized name (by searching in Literature authors). If that's the case, assign the signature to that author.
4. For each remaining non-assigned signature, there will be either no matching name or several. For each one with no results, do a search for names with compatible initials (same logic as in the query parser). If there is exactly one result, assign the signature to that author. **This is not done on legacy, but seems like a good improvement**
5. For each remaining non-assigned signature with several matches, we add more information to the search to try to get less ambiguous matches: first collaboration, then affiliations. If there's exactly one match, assign the signature to that author.
6. For each remaining non-assigned signature, either the match is too ambiguous, or there are no matches. Create a new (stub) record for those and put somewhere in the metadata (`_private_notes`?) which case it corresponds to.

It's probably a good idea to use `inspire-matcher` to implement this.

**Comment by tsgit** [comment]
email address is unreliable and often mixed up between authors
this is one reason Heath puts ORCIDs derived from email into subfield `k` instead of subfield `j`
and rabbit and autoclaim only look at `j`
I would advise caution when using email

**Comment by hoc3426** [comment]
Is this only for assigning to a profile, not autoclaim? There I would think email would be sufficient. Usually it comes in from catalogers or publisher metadata. Although it can get messed up I don't think it's too common.

**Comment by tsgit** [comment]
I have repeatedly seen emails being swapped between authors, or multiple authors having the same email

**Comment by hoc3426** [comment]
True it happens, but at what level? It is an exact match otherwise which is valuable. I don't believe it shows up in Margaret's work with the wrong IDs being in profiles very often (I could ask her about this).

**Comment by pazembrz** [comment]
Create 2 tasks:
First one:
  1. For new record add random UUID for every author entry in the paper
  2. For record update, for every new author add random UUID for every author in the paper
  3. Add record ID to new queue for disambiguation

Second one:
It should take a record id from disambiguation queue and match every author (unmatched - without $ref) as described in here:
  `For each of those, search its IDs and emails in author records (similar to the exact match in the workflow). If there's only one result, assign the signature to that author.`
If there will be exact match then store $ref to this author in literature record.
