### ISSUE TITLE
`citation_publication_date` should use the actual publication date instead of `earliest_date`

### ISSUE THREAD

**Issue by drjova** [inspirehep/inspirehep#1391]
Currently the `citation_publication_date` uses the [earliest_date](https://github.com/inspirehep/inspirehep/blob/d3829e0cb1371a659004bce8f650f3aaa5742911/backend/inspirehep/records/marshmallow/literature/ui.py#L82) instead it should use the actual publication date.

Example:
https://inspirehep.net/literature/12345
```html
<meta name="citation_publication_date" content="1982/07/01" data-react-helmet="true">
```

instead it should use the `publication_info` date which is `1983`.

**TECH**
Since we don’t want to modify date field which is used in another places in UI:
- Get the value of the year from publicationInfo variable (it’s a list with a map inside) instead of from `date` key of the metadata.

**Comment by harunurhan** [comment]
Where did this come from? format in the specs is `YYYY/MM/DD`

**Comment by drjova** [comment]
It was requested by Google Scholar team.

**Comment by drjova** [comment]
@harunurhan I have updated the description and example. The problem is that we use `earliest_date` instead of `publication` date.

**Comment by michamos** [comment]
But didn't she say ISO dates were OK? I think it would be better to use that rather than a strange format.

**Comment by drjova** [comment]
Yes, ISO format works for them and we can easily change it, although their main point was the wrong date.
