### ISSUE TITLE
Implement processing xml files in Elsevier spider

### ISSUE THREAD

**Issue by MJedr** [inspirehep/inspirehep#1400]
Currently Elsevier spider process only files from provided in Elsevier batch feed (they are packed in zip files). We should add a functionality to process selected xml file (should be parsed and converted to INSPIRE record). 

What we would need is a way to reharvest a given record, but we need to be able to provide it as an input to scrapy.

**Comment by drjova** [comment]
Supersede by https://github.com/cern-sis/issues-inspire/issues/158
