### ISSUE TITLE
workflow title display issue in the holding pen

### ISSUE THREAD

**Issue by monaawi** [inspirehep/inspirehep#1410]
https://inspirehep.net/holdingpen/2546221
Title is not displayed for some workflows even though it is in the metadata.
```
Error: [$sanitize:badparse] The sanitizer was unable to parse the following block of html: <z<3.0$
```

**Comment by harunurhan** [comment]
Isn't this #1405 ?

**Comment by drjova** [comment]
duplicate of https://github.com/inspirehep/inspirehep/issues/1405
