### ISSUE TITLE
Disambiguation I - prepare authors in literature record for disambiguation

### ISSUE THREAD

**Issue by pazembrz** [inspirehep/inspirehep#1418]
Create a task which will do:
    For new record add random UUID for every author entry in the paper.
    For record update, for every new author add random UUID for every author in the paper.
    Add record ID to new queue for disambiguation.

*TECH*:
For every `author` entry in `record['authors']` add `signature_uuid` if it's not there already. `signature_uuid` should be unique for every author in one paper.
I think that we don't need a task for this. It can be done [in update method before we store data](https://github.com/inspirehep/inspirehep/blob/bf5025906d19daf5dc018407a280321d6eb849fa/backend/inspirehep/records/api/literature.py#L160) and you can remove [`push_authors_phonetic_blocks_to_redis()`](https://github.com/inspirehep/inspirehep/blob/bf5025906d19daf5dc018407a280321d6eb849fa/backend/inspirehep/records/api/literature.py#L170) as it won't be needed anymore. 
[At the end of update method](https://github.com/inspirehep/inspirehep/blob/bf5025906d19daf5dc018407a280321d6eb849fa/backend/inspirehep/records/api/literature.py#L170) we should add `id` of the record to redis `waiting_for_disambiguation` list as we were [adding `phonetic_blocks` to `author_phonetic_blocks` set](https://github.com/inspirehep/inspirehep/blob/bf5025906d19daf5dc018407a280321d6eb849fa/backend/inspirehep/records/api/literature.py#L252) before.

**Comment by drjova** [comment]
Assigning `uuid` for authors is happening already https://github.com/inspirehep/inspirehep/blob/a7d56913dc8d634067d7067c59d3615b562887e4/backend/inspirehep/records/api/literature.py#L223
