### ISSUE TITLE
Remove *-build containers

### ISSUE THREAD

**Issue by harunurhan** [inspirehep/inspirehep#1429]
Currently we build assets (for `ui` and `record-editor`) in build step containers on CI, so that assets are build in parallel with all other images that we use for tests. This speeds up the overall test time.

However these build containers seems to be failing from time to time. In addition they are painful locally when you need to use them.

We can just remove and them find another way to paralelize image and asset builds. (ex: https://www.cyberciti.biz/faq/how-to-run-command-or-code-in-parallel-in-bash-shell-under-linux-or-unix/)

**Comment by harunurhan** [comment]
During `yarn install`
```bash
ui-build_1             | info There appears to be trouble with your network connection. Retrying...
```

It seems like network issues are the reason why our test fail, not necessarily related to these containers. However that wasn't happening before we introduced these.

We should ideally have a look at how to cache `node_modules` on `circleci` if it's not enabled by default already when `yarn.lock` exists

**Comment by pazembrz** [comment]
Actually we had networking issues on circle CI a long before we introduced `BUILD` containers. Now it's failing on them as they are running before other containers. If I'm not mistaken this error is coming from Yarn. We can add `yarn add <yourPackage> --network-timeout 100000` to force yarn to wait longer.

**Comment by harunurhan** [comment]
Looks like we are trying to solve 2 issues, which may or may not be related

### Unnecessary complexity
Only reason we have `-build` containers is to build assets in parallel with building other docker images. It does work but

- destroys local dependencies when CI setup used on macOS
- slower build times inside docker container on macOS
- maintaining build containers (they have to be on exactly same node version we support) 

### Network on CI
We can solve this by caching dependencies or failing that increasing `yarn` timeout, but downloading stuff inside docker container adds extra layer of complexity to networking. Although it's unlikely, this could be contributing to the network issues
