### ISSUE TITLE
LaTeX rendering for experiments

### ISSUE THREAD

**Issue by StellaCh** [inspirehep/inspirehep#1442]
In the experiments description, if there's LaTeX, this is not displayed properly. Compare https://inspirehep.net/experiments/1822400 to https://old.inspirehep.net/record/1822400

**Comment by harunurhan** [comment]
`<Latex>` should be used here: https://github.com/inspirehep/inspirehep/blob/85f384a29b8278a2d94304dbf5e1fcf4d3277ea4/ui/src/experiments/containers/DetailPageContainer.jsx#L158 instead of `<RichDescription>` which is for HTML supported descriptions
