### ISSUE TITLE
Improve journal linking and handle failures gracefully

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspirehep#1445]
https://sentry.inspirebeta.net/inspire-qa/next/issues/394778/?query=is%3Aunresolved

This is caused by a missing `publication_info.journal_record` (`None` instead of proper value), which should be populated by https://github.com/inspirehep/inspire-next/blob/584a88e5b06f89294c195aac5423354b7c5b34ea/inspirehep/modules/workflows/tasks/actions.py#L553-L588.

* This should be fixed to return the proper journal record when trying to normalize `Measurement`
* The `populate_journal_coverage` task should handle absence of a `journal_record` gracefully.

**Comment by oguzdemirbasci** [comment]
It seems like the error occurs only for a specific journal which does not exist on QA at the moment. We do not have the same error for the current journal records. So it is better to wait for having this error again to solve the bug.
