### ISSUE TITLE
Validate workflow.metadata on PUT /api/holdingpen/<workflow_id>

### ISSUE THREAD

**Issue by harunurhan** [inspirehep/inspirehep#1474]
Separated from #1450

> PUT /api/holdingpen/<id> must validate and return validation errors in the format that ng2-json-editor expects

https://github.com/inspirehep/inspire-next/blob/d67c86279968cd8843d657071c38e0838d0780aa/inspirehep/modules/workflows/utils/__init__.py#L449 returns the errors in the right format already and they should be set to `extra_data.validation_errors`

**Comment by harunurhan** [comment]
Btw saving a workflow is somewhat complex on the client side https://github.com/inspirehep/inspirehep/blob/ffae4ded3d52f848d95044ce1c95869fe9545c6b/record-editor/src/app/holdingpen-editor/holdingpen-save-button/holdingpen-save-button.component.ts#L115-L188

So make sure we handle `VALIDATION_ERROR` type of errors for saving without callback url too.

**Comment by drjova** [comment]
**Backend TECH NOTES:**
* Copy https://github.com/inspirehep/inspire-next/blob/d3ff3c8fb1fde8e94b7597fa4f16bb08f2811bb8/inspirehep/modules/workflows/utils/__init__.py#L449 into `inveniosoftware-contrib/invenio-workflows-ui`
* on `put` we should validate https://github.com/inspirehep/inspire-next/blob/d3ff3c8fb1fde8e94b7597fa4f16bb08f2811bb8/inspirehep/modules/workflows/tasks/actions.py#L303-L312 as here
