### ISSUE TITLE
Selecting autocomplete in editor sometimes doesn't work

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspirehep#1497]
Sorry, my screencast tool broke, so no video. Curators from IHEP report the following issue.

To reproduce:
1. Open record editor (e.g. https://inspirehep.net/editor/record/literature/4328), go to authors tab, and click show all on an author
2. Click on `affiliations`/`Add new` to add a new affiliation
3. Type something, say `cern`, in the new empty affilitation box
4. The autocomplete dropdown should display `CERN`, click on it
5. Nothing happens
6. Delete the `n` of `cern` and type it again
7. Click on the `CERN` in the autocomplete dropdown
8. the field is properly populated from autocomplete (including linked record ref)

Expected:
Result of step 4. is the same as result of step 7., namely step 8.

**Comment by harunurhan** [comment]
Selecting by enter works consistently but with mouse this issue appears, we use this typehead componnt from old `ngx-bootstrap` and this a bug there 😨, probably fixed by now but we are unfortunately stuck with very old version.
