### ISSUE TITLE
Issues with `texkeys` when we run reference matcher

### ISSUE THREAD

**Issue by drjova** [inspirehep/inspirehep#1500]
There is a [bug](https://sentry.inspirebeta.net/inspire-qa/hep/issues/394700/?query=is%3Aunresolved) with `texkeys` when we run [reference matcher ](https://github.com/inspirehep/inspirehep/blob/master/backend/inspirehep/matcher/cli.py#L42). Probably the `texkey` implementation causing this issue. 

Acceptance:
* We should run the reference matcher command on QA without any errors.

**Comment by pazembrz** [comment]
Looks like it's a but in metadata not in texkeys minter itself. We will remigrate QA db from PROD legacy_records_mirror to get updated metadata.
