### ISSUE TITLE
Update all $ref links in all other records when merging a record

### ISSUE THREAD

**Issue by pazembrz** [inspirehep/inspirehep#1504]
When record is merged it's PID is redirected to another PID. 
When this happens make sure that all old `$ref` from other records which were pointing to merged record (merged record is deleted after merge) are pointing now to the new record.

This should work on all pid types.

**TECH**
1. Check why we call `update_records_relations` only on migration
2. When we receive a record, on `update_records_relations` check the difference between previous and a new version of the record. If there is a difference in `deleted_records` field create a new celery task which will search for the references to the deleted record. Ask Micha for the exact information about collections linking in order to search only in proper fields.
3. For every result update the reference to point to the new record.

**Comment by MJedr** [comment]
It seems that we were using `update_records_relations` also in [cli which was removed](https://github.com/inspirehep/inspirehep/commit/edb9e2c3fc338945af9c93dd687e2edbb67f3e20#diff-ecb61cba1d7f51eb4d4ff616c0e1301a1f76df77a180b620b122d3bdb43b310b). We were never calling it on record update.
