### ISSUE TITLE
Check how we could get fulltext in workflows.

### ISSUE THREAD

**Issue by drjova** [inspirehep/inspirehep#1514]
We should check GROBID if we can get `fulltext ` from files. If it's possible, provide an example which can be implemented next sprint.

**Comment by michamos** [comment]
other options: `pdftotext`/`pdftoxml`

**Comment by michamos** [comment]
This is the tool that GROBID is using internally: https://github.com/kermitt2/pdfalto.

**Comment by pazembrz** [comment]
Grobid allows us to easily [get fulltext](https://grobid.readthedocs.io/en/latest/Grobid-service/#apiprocessfulltextdocument).
```python
data = {"input":pdf.content}
url = f"{current_app.config['GROBID_URL']}/api/processFulltextDocument"
r=requests.post(url, files=data)
from xml.dom import minidom
xml_data=r.text 
xml = minidom.parseString(xml_data)
xml.getElementsByTagName("body")[0]
text = body.getElementsByTagName("p")
# text contains now lists of <p> tags which have paragraphs from PDF file
# each of the paragraph can contain one or more TextNodes and ref nodes. TextNodes contains paragraph text in  nodeValue.
fulltext = " ".join([child.nodeValue for x in text for child in x.childNodes if child.nodeValue])
```
fulltext variable should contain whole fulltext from PDF.

**Comment by michamos** [comment]
I know, but it's doing a lot of work we are throwing away (using ML to get structured metadata from the PDF). If it's performant enough it's not an issue though.

**Comment by pazembrz** [comment]
I tested on few PDF and it was taking between 2 and 5 seconds (depending of the PDF size). IMHO it's better to use something we already have than implement something new for Workflows on next which is really scary to work with and which we will re-do in few months.
