### ISSUE TITLE
If workflows are not relevant to inspire check the raw affiliations

### ISSUE THREAD

**Issue by drjova** [inspirehep/inspirehep#1515]
If the workflow is not relevant to INSPIRE, check the raw affiliations. If they contain `IN2P3` or `CERN` or `Fermilab` update them with `HIDDEN` collection and upload to inspire.

They should not have `Literature` in this case but one of the hidden collections depending on the matched substring of raw affiliations:
* `IN2P3` -> `HAL Hidden`
* `CERN` -> `CDS Hidden`
* `Fermilab` -> `Fermilab`

**TECH:**
Add additional check in [here](https://github.com/inspirehep/inspire-next/blob/9c9e0975bb4a53637e7c114c618d4ea5ef593c51/inspirehep/modules/workflows/workflows/article.py#L314-L320) Which will check in all authors of this article all `raw_affiliations` If it will match with `IN2P3` or `CERN` or `Fermilab` remove `Literature` Collection from `metadata._collections` and add hidden collections based on found affiliations as mentioned above. Additionally upload record to HEP and do not halt workflow.

**Comment by pazembrz** [comment]
> If the workflow is not relevant to INSPIRE, check the raw affiliations. If they contain `IN2P3` or `CERN` or `Fermilab` update them with `HIDDEN` collection and upload to inspire.
> 
> They should not have `Literature` in this case but one of the hidden collections depending on the matched substring of raw affiliations:
> 
>     * `IN2P3` -> `HAL Hidden`
> 
>     * `CERN` -> `CDS Hidden`
> 
>     * `Fermilab` -> `Fermilab`

**Comment by michamos** [comment]
I think it's a bit more complex, because we need to do the full record enhancement in this case, so you probably need to set a mark in `extra_data` and later check the mark to verify if it should go to a special collection.
