### ISSUE TITLE
Always conflict on title changes in merger

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspirehep#1518]
@fschwenn reports that we should show always have conflicts for changes in titles. Indeed, titles might have been curated (e.g. nicely LaTeX-ifield) and changes in titles might also be the sign of scenarios that are not handled automatically yet (e.g. an erratum is merged with the main publication and overwrites lots of fields) so having a conflict gives us an opportunity to review them.

TECH NOTES:
* Change the merger config not to ignore conflicts on titles.
* Add a pre-filter to remove `titles` from the `root` to avoid silently updating in case the title has not been curated.

**Ad. 1.** 
Remove `titles` from `list_megre_ops` in `ArxivOnPublisherOperations`

**Ad. 2.**
Add a new filter (similar to [this one](https://github.com/inspirehep/inspire-json-merger/blob/8ce4bb99f373ea558fd76270bc2c1b23ff9bfc9e/inspire_json_merger/pre_filters.py#L113) but remove `titles` from root and place it in the [`pre-filters`](https://github.com/inspirehep/inspire-json-merger/blob/8ce4bb99f373ea558fd76270bc2c1b23ff9bfc9e/inspire_json_merger/config.py#L45).

**Comment by pazembrz** [comment]
On `pre-filters` merge duplicated title, (remove one of them) leaving non archive source.
