### ISSUE TITLE
Create cli for data operations

### ISSUE THREAD

**Issue by drjova** [inspirehep/inspirehep#1526]
We should create a `cli` tool for different data operations: 

* Recalculate citations
* Mint specific pid_type
* Disambiguation
* ... TBD

**Comment by harunurhan** [comment]
#1247 could be relevant too

**Comment by drjova** [comment]
@michamos could you please give examples for the MVP? What are the core needs?

**Comment by michamos** [comment]
@drjova do we still need this?

**Comment by drjova** [comment]
We don't get any request for such operations, I believe it's better to create cli when there is a request. I will close it for the moment.
