### ISSUE TITLE
Handle race condition when doing multiple updates

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspirehep#1559]
Some tasks (indexing, disambiguation) are done asynchronously after updating the record, and rely on the following property:

> The previous run of the task was for the previous version of the record.

This property is used implicitly when diffing versions of the record in order to detect
* which references have changed and their records need reindexing;
* which authors have changed and need disambiguating;
* etc.

However, the property as stated is **false**, due to the asynchronicity: it's possible for two (or more) updates of the record to be made before the task has a chance to run, causing the diff of the changes on the DB not to correspond to the diff of successive runs of the tasks. This should be fixed, as it will cause issues (wrong citation counts when updating references, wrongly disambiguated authors, etc.).

We focus here on indexing only. For disambiguation new task will be created.

Tech notes in comment below https://github.com/inspirehep/inspirehep/issues/1559#issuecomment-754013872
~~**Tech Notes:**~~
~~Solution to this problem will be quite complex.~~
~~* Add 2 locks (redis) for record control number. One will be for indexing and second for disambiguation.~~
~~* Locks should be acquired in [here](https://github.com/inspirehep/inspirehep/blob/a325629aea4e8717997a26ec0f37b5d2e62ad313/backend/inspirehep/records/receivers.py#L37) before indexing and disambiguation will run. And they should be released at the end of indexing and disambiguation tasks. So next indexing and disambiguation won't run until previous one will finish.~~
~~* check which version is on ES currently (based on `updated` field from db and `updated` field on ES) and index/disambiguate ONLY if `record.updated` is NOT OLDER than `es_data['_updated]`.~~
~~Before executing indexing and disambiguation add a check `if InspireSearch.get_record_data_from_es(rec)['_updated'] <= rec.updated: then reindex/disambiguate`~~
~~Remember that `_updated` is in isoformat, so it should be parsed first.~~
~~* all `get_modified_*` methods should diff between `last_indexed_version` and `current_version`. To properly get this version is should be passed from `index_after_commit` receiver to index/disambiguation task.~~

**Comment by michamos** [comment]
I don't think that would work, as sometimes we index due to changes not reflected in the DB record (e.g. citation count) which wouldn't update the `_updated` field.

**Comment by pazembrz** [comment]
I Updated tech notes.

**Comment by pazembrz** [comment]
We are changing the idea qhat and how we want to fix here

*Tech Notes* 
* https://github.com/inspirehep/inspirehep/blob/a325629aea4e8717997a26ec0f37b5d2e62ad313/backend/inspirehep/indexer/tasks.py#L28 Extend this list with Elasticsearch errors: [`ConnectionError`](https://elasticsearch-py.readthedocs.io/en/7.9.1/exceptions.html#elasticsearch.ConnectionError), [`ConnectionTimeout`](https://elasticsearch-py.readthedocs.io/en/7.9.1/exceptions.html#elasticsearch.ConnectionTimeout), [`SSLError`](https://elasticsearch-py.readthedocs.io/en/7.9.1/exceptions.html#elasticsearch.SSLError), [`NotFoundError`](https://elasticsearch-py.readthedocs.io/en/7.9.1/exceptions.html#elasticsearch.NotFoundError)['RequestError`](https://elasticsearch-py.readthedocs.io/en/7.9.1/exceptions.html#elasticsearch.RequestError)
* https://github.com/inspirehep/inspirehep/blob/a325629aea4e8717997a26ec0f37b5d2e62ad313/backend/inspirehep/indexer/tasks.py#L87 Gracefully handle error from indexing when we try to update document to older version [`VersionConflictException`](https://elasticsearch-py.readthedocs.io/en/7.9.1/exceptions.html#elasticsearch.ConflictError) so rest of the task continue without a problem
