### ISSUE TITLE
Reuse the Jinja environments for caching

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspirehep#1565]
From https://inspirehep.zulipchat.com/#narrow/stream/122202-devel/topic/migration.20profiling/near/217984830:

Compiling Jinja templates to bytecodes is expensive, but Jinja has built-in caching mechanisms. Unfortunately, they are not used in use in our case, because we recreate the `Environment` object on every call:
 https://github.com/inspirehep/inspirehep/blob/e4fd6b57fe2ccf78a315f4e0c0b33dd0e3a0d263/backend/inspirehep/records/serializers/latex.py#L44-L48 and
https://github.com/inspirehep/inspirehep/blob/e4fd6b57fe2ccf78a315f4e0c0b33dd0e3a0d263/backend/inspirehep/records/serializers/cv.py#L28-L30
This should be refactored to have global environments that can be reused during the whole application lifetime, as explained in https://jinja.palletsprojects.com/en/2.11.x/api/#basics.

**Comment by drjova** [comment]
TECH NOTES:

* Create an environment in `records/serializers/jinja.py` with `loader` the `template` folder of `inspirehep.records.serializers.templates`.
* Change https://github.com/inspirehep/inspirehep/blob/e4fd6b57fe2ccf78a315f4e0c0b33dd0e3a0d263/backend/inspirehep/records/serializers/latex.py#L44-L48 and https://github.com/inspirehep/inspirehep/blob/e4fd6b57fe2ccf78a315f4e0c0b33dd0e3a0d263/backend/inspirehep/records/serializers/cv.py#L28-L30 to use the new environment instead.
