### ISSUE TITLE
Avoid deepcopies in marshmallow schemas

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspirehep#1566]
From https://inspirehep.zulipchat.com/#narrow/stream/122202-devel/topic/migration.20profiling/near/217984830.

We are deepcopying the input object in every marshmallow schema due to https://github.com/inspirehep/inspirehep/blob/e4fd6b57fe2ccf78a315f4e0c0b33dd0e3a0d263/backend/inspirehep/records/marshmallow/base.py#L54
Unsurprisingly, this is expensive. The `deepcopy` is currently needed because some schemas are mutating their input, but it's probably better to fix those in order not to perform mutation rather than calling `deepcopy` all the time, or only make a shallow `copy` when needed instead of a systematic `deepcopy`.

**Comment by MJedr** [comment]
It seems possible to replace `deepcopy`  [here](https://github.com/inspirehep/inspirehep/blob/e4fd6b57fe2ccf78a315f4e0c0b33dd0e3a0d263/backend/inspirehep/records/marshmallow/base.py#L54) with `copy` and in latex schema replace copy [here](https://github.com/inspirehep/inspirehep/blob/e4fd6b57fe2ccf78a315f4e0c0b33dd0e3a0d263/backend/inspirehep/records/marshmallow/literature/latex.py#L36) and [here](https://github.com/inspirehep/inspirehep/blob/e4fd6b57fe2ccf78a315f4e0c0b33dd0e3a0d263/backend/inspirehep/records/marshmallow/literature/latex.py#L110) with deepcopy

A small improvement which might fasten the serialization is to not `deepcopy` [here](https://github.com/inspirehep/inspirehep/blob/master/backend/inspirehep/records/marshmallow/base.py#L58) but in case when we don’t receive inspire record (it has no attribute `model`) we might replace `deepcopy` with `obj_copy = orjson.loads(orjson.dumps(obj))` ([reference](https://stackoverflow.com/questions/24756712/deepcopy-is-extremely-slow)).
