### ISSUE TITLE
Datasets icon for papers

### ISSUE THREAD

**Issue by StellaCh** [inspirehep/inspirehep#1601]
Users complain that they can't find hepdata links to papers. The HEPData link is hidden in the detailed page and you can view HEPData links in `View in: HEPData`, eg. https://inspirehep.net/literature/1810348 . At the moment, users go to legacy to view these links because they don't know they exist on labs.

We need to the HEPData info more visible:
Add a new icon <DatabaseOutlined /> that links to HEPData.
The icon should appear only if there're links to datasets in the paper. The icon should be visible both to search and detailed page
<img width="642" alt="Screenshot 2020-12-14 at 15 37 41" src="https://user-images.githubusercontent.com/24955201/102105039-2defb000-3e2f-11eb-8a9c-385edf1e38dd.png">

The icon 'datasets' should be the last item of the icons list.

**Comment by drjova** [comment]
TECH NOTES:

* Remove `hepdata` from https://github.com/inspirehep/inspirehep/blob/master/backend/inspirehep/records/marshmallow/literature/common/external_system_identifier.py#L12
* Create a new field `hepdata_link` in the serializer https://github.com/inspirehep/inspirehep/blob/a325629aea4e8717997a26ec0f37b5d2e62ad313/backend/inspirehep/records/marshmallow/literature/ui.py#L40
* Add `UrlsAction` her https://github.com/inspirehep/inspirehep/blob/bf5025906d19daf5dc018407a280321d6eb849fa/ui/src/literature/containers/DetailPageContainer/DetailPageContainer.jsx#L132 for the `hep_data_link`
