### ISSUE TITLE
Move /authorlist to hep

### ISSUE THREAD

**Issue by drjova** [inspirehep/inspirehep#1621]
Move `/editor/authorlist/text` to `hep`.

Tech Notes:
* https://github.com/inspirehep/inspire-next/blob/master/inspirehep/modules/editor/api.py#L74-L82
* Change routing on k8s

**Comment by MJedr** [comment]
What about this view:
https://github.com/inspirehep/inspire-next/blob/2fe0a80ba872dd91ffdfec9134b8be7a7a0cc78c/inspirehep/modules/tools/views.py#L51-L71
Should we leave it on next?

**Comment by michamos** [comment]
yes, this will go away once we switch off legacy.
