### ISSUE TITLE
Change legacy redirects

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspirehep#1631]
We have a few redirects in place in https://github.com/inspirehep/inspirehep/blob/master/backend/inspirehep/legacy/views.py to redirect users to legacy (essentially prepending `old.` to the domain). Before switching off legacy, those should instead be redirected to equivalent labs functionality.

**Comment by drjova** [comment]
@michamos what about `/manage_profile`? Should it go to update form?

**Comment by drjova** [comment]
TECHO NOTES:

* Create a new feature flag, `FEATURE_FLAG_ENABLE_LEGACY_VIEW_REDICTS`
* In the [views](https://github.com/inspirehep/inspirehep/blob/master/backend/inspirehep/legacy/views.py) when there is a redirect to `LEGACY_BASE_URL` add the feature flag and change the redirect to `hep`.

**Comment by drjova** [comment]
@michamos any idea what `info` is? https://github.com/inspirehep/inspirehep/blob/master/backend/inspirehep/legacy/views.py#L99-L101
