### ISSUE TITLE
primarch search

### ISSUE THREAD

**Issue by StellaCh** [inspirehep/inspirehep#1634]
Currently, if one wants to search for an arxiv category, they could use the arxiv facet. However, the new INSPIRE doesn't provide a way to search for papers with a specific primary arXiv category.

TECH NOTES:
* Add a new field in the mappings `primary_arxiv_category` with type`keyword`
* In the `ES` serializer get the first arxiv category from `arxiv_eprints.categories` and  add it to `primary_arxiv_category`

**Comment by drjova** [comment]
@michamos should the field named `primarch`?

**Comment by michamos** [comment]
I would go for `arxiv_eprints.primary_category`.
