### ISSUE TITLE
Move python-client-sword2 to python 3

### ISSUE THREAD

**Issue by drjova** [inspirehep/inspirehep#1641]
https://github.com/inspirehep/python-client-sword2 move to python3 with automated tool

**Comment by michamos** [comment]
Note that some forks have already performed this conversion, e.g. https://github.com/inspirehep/python-client-sword2/compare/master...tuub:python-2to3?expand=1. It might be useful to take that as a starting point, review the changes and adapt if needed.

**Comment by drjova** [comment]
@michamos but we already have some changes in our own fork right?

**Comment by michamos** [comment]
yes, but we might still be able to merge these other changes on top.
