### ISSUE TITLE
HAL push

### ISSUE THREAD

**Issue by drjova** [inspirehep/inspirehep#1642]
On record create/update we should check if the record has `_export_to.HAL: true` and if it's `True` we should send a task that pushes this record to HAL with the following logic https://github.com/inspirehep/inspire-hal/blob/master/inspire_hal/bulk_push.py#L62-L88. 

Note: We could copy the logic of `tei` and `sword` functionality directly.

Blocked by https://github.com/inspirehep/inspirehep/issues/1641

**TECH NOTES**
1. create a HAL module
2. Copy sword and tei modules from here https://github.com/inspirehep/inspire-hal/tree/master/inspire_hal/core
2. Create a celery task which will do the push to hal using the logic from [here](https://github.com/inspirehep/inspire-hal/blob/master/inspire_hal/bulk_push.py#L62-L88)
3. Call the task in [create](https://github.com/inspirehep/inspirehep/blob/03d47172983da1531a657ab6ed6b798c6a9e1245/backend/inspirehep/records/api/literature.py#L92) and [update](https://github.com/inspirehep/inspirehep/blob/03d47172983da1531a657ab6ed6b798c6a9e1245/backend/inspirehep/records/api/literature.py#L157) methods of the LiteratureRecord

**Comment by michamos** [comment]
When the push fails for some reason, Mathieu should be able to see the failure. Either we log it and then we build some periodic task to send the logs to the chat/to Mathieu by email, or we send failures immediately. It's probably better to decouple this from the application and have the application just do logs.
