### ISSUE TITLE
Improve earliest date handling

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspirehep#1644]
Currently the `earliest_date` uses the `legacy_creation_date`: https://github.com/inspirehep/inspirehep/blob/69f4ceeff84c2284b0b3f6b64c7c898301caadda/backend/inspirehep/records/utils.py#L27-L54. That date is not really part of the paper metadata, but an "accidental" property of the INSPIRE record (aka metametadata). We should not consider that field for the calculation of the `earliest_data`, and instead use the record creation date as a fallback if no other date can be found inside the record (`created` attribute instead of `legacy_creation_date` which won't be there for labs-native records).

**TECH NOTES**
1. Remove `legacy_creation_date` from [here](https://github.com/inspirehep/inspirehep/blob/69f4ceeff84c2284b0b3f6b64c7c898301caadda/backend/inspirehep/records/utils.py#L38)
2. In [LiteratureRecord](https://github.com/inspirehep/inspirehep/blob/bf8fc166e01119590a3f56937b05014583592764/backend/inspirehep/records/api/literature.py#L88) if get_earliest_date is None set `self.created` as the `earliest_date` (converted to string)
3. In `LiteratureDetailSchema` instead of using the [method to retrieve the earliest date](https://github.com/inspirehep/inspirehep/blob/bf8fc166e01119590a3f56937b05014583592764/backend/inspirehep/records/marshmallow/literature/ui.py#L88) use `fields.Field(attribute='earliest_date')`

**Comment by MJedr** [comment]
It seems that currently we use `legacy_creation_date` for `created` attribute too (if it is available) https://github.com/inspirehep/inspirehep/blob/69f4ceeff84c2284b0b3f6b64c7c898301caadda/backend/inspirehep/records/api/base.py#L397

**Comment by michamos** [comment]
That's ok, as long as we use the created date (either on labs or legacy, so `created` field thanks to this) as a fallback.

**Comment by pazembrz** [comment]
>     3. In `LiteratureDetailSchema` instead of using the [method to retrieve the earliest date](https://github.com/inspirehep/inspirehep/blob/bf8fc166e01119590a3f56937b05014583592764/backend/inspirehep/records/marshmallow/literature/ui.py#L88) use `fields.Field(attribute='earliest_date')`

This wont' be possible, as `data` in there might not be an LiteratureRecord object, but just simple dictionary. Additionally this method returns "prettified" date like: "Sep 15, 2020" which is different form what `earliest_date` property returns.

**Comment by michamos** [comment]
wouldn't also the citation count stuff fail in that case? when is the thing passed to the schema a `dict` and not a `LitetatureRecord`?

**Comment by pazembrz** [comment]
In this schema we do not serialize citations. 
Almost all tests for this schema is passing only a dictionary.  In principal we should pass there only LiteratureRecord object, but as I remember from the past we had issues with this that sometimes object was stripped from data :/ In my implementation I will assume that there is LiteratureRecord object but I will do simple fallback if we pass a dictionary.
