### ISSUE TITLE
Sync identifiers from CDS

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspirehep#1657]
Currently, legacy is exchanging identifier information with CDS. A new protocol has been developed for use on labs, but we're not using it yet. We should use it to get information about new identifiers and update our records based on it.

We have to sync identifiers with CDS periodically, using their API <http://cds-test.cern.ch/api/inspire2cdsids?since=2020-07-01> The output of the API is the following:
```json
[{
      "id": "1992565",
      "metadata": {
        "other_ids": [
          "1344808"
        ],
        "eprints": [
          "1502.04088"
        ],
        "dois": [
          {
            "value": "10.1103/PhysRevSTAB.18.041004"
          }
        ],
        "report_numbers": [
          {
            "value": "arXiv:1502.04088"
          }
        ],
        "control_number": "1992565"
      }
    }]
```

TECH NOTES:
* Create a module cds which has a `task` in `cds/tasks.py` that we pass the `since` and consumes the API from cds and update the inspire records, this should be behind a feature flag and the cds API url should be configurable. We could use Record builder to update the record.
* Create a `cli` in `cds/cli.py` that calls async the task with a specific date (default will be the current data)
* On Kubernetes we should create a daily job that runs the cli.
* Add a dashboard on `grafana` to monitor if the job has run or not.
* Add the steps to run manually the `cli` on documentation

**Comment by pazembrz** [comment]
Do we have any docs available for this protocol? @michamos

**Comment by michamos** [comment]
Stupid question: why do you need to have a task and do stuff async if you already have a job to run it?

Less stupid remark: I think there's something else that you didn't take into account, namely that we want to run it with `since` set to the last successful run, with an option to set the `since` on the first run (that will be set to the last run of legacy). So you need to keep some state somewhere (redis?), or retrieve the last successful run through the k8s API.
