### ISSUE TITLE
Improve PDG identifiers

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspirehep#1659]
On legacy, PDG identifiers are expanded into their human-friendly name and link back to the PDG site. On labs we display the PDG codes among the keywords and don't link them. Compare 
![Screenshot_2021-01-21 Observation of a New Boson at a Mass of 125 GeV with the CMS Experiment at the LHC - INSPIRE](https://user-images.githubusercontent.com/2895793/105375960-83c32f00-5c09-11eb-8b8b-c6599791b291.png)
 on https://inspirehep.net/literature/1124338 and 
![Screenshot_2021-01-21 Observation of a New Boson at a Mass of 125 GeV with the CMS Experiment at the LHC - INSPIRE-HEP](https://user-images.githubusercontent.com/2895793/105376007-93427800-5c09-11eb-89b6-e42166cf32d7.png)
on https://old.inspirehep.net/record/1124338 

We should improve that.

**Comment by drjova** [comment]
A solution is to filter out PDG keywords and display them like in the screenshot:
![Image](https://user-images.githubusercontent.com/4287772/188115461-8637419b-ddb3-4dd3-89b2-7c0e1fd21f15.png)

**Comment by michamos** [comment]
Translation from PDG identifiers to long descriptions is in https://pdg.lbl.gov/2022/pdgid/PDGIdentifiers-2022v0.json.
