### ISSUE TITLE
Normalize journal names in references 

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspirehep#1673]
In the workflow, we currently run the journal name normalization for the `publication_info` of the record, but we don't do this for the references. This is not needed for arXiv as references are coming from refextract which are already normalized, but it's required for references coming from publisher metadata. So we need to perform journal name normalization of references in case they didn't come from refextract.

**Comment by pazembrz** [comment]
There is already a [task](https://github.com/inspirehep/inspire-next/blob/fdc7f052b7c43f4846f4da7e0effc82e1495fdbb/inspirehep/modules/workflows/tasks/actions.py#L554-L589) in workflows which is doing this  but it's processing only entries from [wf.data['publication_info'] publication_info](https://github.com/inspirehep/inspire-next/blob/fdc7f052b7c43f4846f4da7e0effc82e1495fdbb/inspirehep/modules/workflows/tasks/actions.py#L574) it should be extended to also process publication_info from _**wf.data["references"]**_.
