### ISSUE TITLE
Reorder author name after succesful disambiguation

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspirehep#1674]
Some authors have several last names, but the grouping of last and first name is wrong on the paper. For example we have `Smith, John Davis`, but the actual name should be `Smith Davis, John`. After performing author disambiguation, we should take the proper grouping of names from the linked author record (just the grouping, not initials/spelling/accents).

**Comment by MJedr** [comment]
**TECH NOTES**
1. Add a function `reorder_literature_author_names` and call it [here](https://github.com/inspirehep/inspirehep/blob/13611dfecb47ff2c94d1eb5d138e6bdcd842292d/backend/inspirehep/disambiguation/tasks.py#L263) for author that was disambiguated to assign a new name to the lit author. In the function:
* get name from `author.name.value` from author record and move corresponding name from lit author to last_name or first_name, depending on the position in author name (on the left comma side - last name). Normalize strings with `unidecode` for comparing. If there's no token in author name, leave it as it was in lit author.

**Comment by michamos** [comment]
Just to make sure everything is clear: the name absolutely has to be the one on the paper, all that's allowed is moving things around.

Also, as this is just a heuristic, we probably should do this only in case there is only one last name in the literature record, if there's more than one, chances are that it's already been split correctly at the source.

**Comment by drjova** [comment]
Thanks for the clarification!
