### ISSUE TITLE
keywording API

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspirehep#1676]
DESY have a whole process to assign keywords to records. This involves sending the records to experts, which assign keywords, which then need to be added back to the record. This requires two pieces of metadata: `_desy_bookkeeping` to manage the process and the `keywords` themselves.

Suggestion by @michamos : build a simple API to modify this information on a record. 

We should create `curation` module with a REST API prefix `/curation`.

We could have something like `PUT /curation/literature/<pid_value>/keywords` with a payload of the form:
```
{ 
"_desy_bookkeeping": {...},
"keywords": [...]
}
```
which would *append* an element to the `_desy_bookkeeping` array and *replace* all `keywords` with `schema` `INSPIRE` with the provided list of keywords (each element being optional, so you can provide only one or the other).

**Comment by pazembrz** [comment]
Tech:
* Create new module called `curation` in HEP
* this module should have a view which will accept only PUT
* * `PUT /curation/literature/<pid_value>/keywords`
* As authentication use tokens assigned to their accounts.
* * Only curators should be allowed to use this API.
It should accept json with one or both keys:
`_desy_bookkeeping` - dictionary and `keywords`- list

`_desy_bookkeeping` should be added to `_desy_bookkeeping` list on the record as is.

If `keywords` are provided, remove from record all keywords with `INSPIRE` schema. Then add those new keywords with `INSPIRE` schema and without `source`. Then update records and commit changes. If there will be any error return it as a response in the API with proper text and status code.
If update was successful return 200 status code

Remember to [register](https://github.com/inspirehep/inspirehep/commit/415ee4f550307776db1fec437fa9ed7f08546bbf#diff-bafe36cadd61f15c41fb61105985bd5c72b3da49f96083e515001b621fddda47) this module views in setup.py
