### ISSUE TITLE
Put classifier keywords into the record

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspirehep#1677]
We currently run `invenio-classifier` in the workflow but its output is used only to help curators decide whether a record is core, and gets discarded afterwards. We should put the keywords extracted from metadata into the record if it's accepted as CORE, with `schema: INSPIRE`.

TECH NOTES:
* Modify https://github.com/inspirehep/inspire-next/blob/f9c7fd311c6b68dc393c7706265714c392c8d4c9/inspirehep/modules/workflows/tasks/classifier.py#L56-L107 to always run on the metadata (`else` branch in https://github.com/inspirehep/inspire-next/blob/f9c7fd311c6b68dc393c7706265714c392c8d4c9/inspirehep/modules/workflows/tasks/classifier.py#L84), and put `complete_output.composite_keywords.keyword + complete_output.single_keywords.keyword` into `extra_data.extracted_keywords`. Note that it should not overwrite the output of `extra_data.classifier_results`, which should still contain the results of the keywords extracted from PDF if that's available.
* If workflow accepted as `CORE`, take keywords from `extra_data.extracted_keywords` and add them to `keywords` with `schema:INSPIRE`.

**Comment by drjova** [comment]
@michamos is this task up to date?

**Comment by michamos** [comment]
I asked but never got a reply. I'll ask again

**Comment by michamos** [comment]
I've edited it, it's really refined now :)

**Comment by drjova** [comment]
thanks!
