### ISSUE TITLE
Normalize collaborations

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspirehep#1689]
On legacy @ksachs has some scripts to normalize collaboration names and add the experiment identifier for the corresponding experiment. The script is semi-automatic as there can be ambiguities and unknown collaborations. On labs, the right place to perform this kind of normalization is in the workflows, but this would only work for the automatic part, so some extra work is probably needed for the part requiring human supervision.

**Comment by ksachs** [comment]
Might be enough (at least for now) to run it automatically and write the log-file to an RT ticket for confirmation, fixing mistakes via editor. I don't want a ticket for every record, but a list to go though, maybe once per week.
Not sure how to deal with ambiguous experiments (e.g. D0, NEMO), add all or none? tbd.

**Comment by ksachs** [comment]
FYI: don't know if this is useful.
[Code](https://github.com/ksachs/MixedStuff/blob/demo/collclean_lib.py) currently running at DESY.

**Comment by michamos** [comment]
Thanks @ksachs, it is useful to see more precisely what you're currently doing.

**Comment by michamos** [comment]
@ksachs I had a deeper look at your code. As far as I can tell there are functions to do 3 different things:
1. disentangle collaboration from author/affiliation (`coll_cleanforthe`)
2. normalize affiliation names (`coll_cleansimple` and `coll_clean710`)
3. add also the experiment field corresponding to the affiliation (`exp4coll`)

Here is how I envision doing this on labs:
1. I believe this is out of scape for this issue, as it's not really about collaboration normalization, but rather collaboration extraction, so should be the responsibility of the parser/record builder: it's some static rules that don't depend on which collaborations actually exist, and it probably depends a lot on the structure of the incoming metadata (in that you can do better with better metadata, and need to do this kind of dirty parsing on poorer metadata). We have a more basic version of this function that is used in the record builder, which all non-DESY harvesters will use: https://github.com/inspirehep/inspire-schemas/blob/afc2553e150fc83e72aa3187926caa126a0a096d/inspire_schemas/utils.py#L785-L812, and a more involved one for arXiv https://github.com/inspirehep/hepcrawl/blob/master/hepcrawl/parsers/arxiv.py#L92. If those need to be improved, we can create extra tasks.
2. If 1. is taken care of, we can assume that the input record has a collaboration field with some text that looks like a collaboration name, which might however not be the sanctioned collaboration name we want to use in INSPIRE. For normalization, I would suggest following essentially the same approach as for journal name normalization. Namely, we do some search in the experiments database (in `collaboration.value`, `name_variants`) with a properly set-up analyzer to ignore irrelevant differences like spacing, punctuation, etc. If there's a match, we take the name from `collaboration.value` and also populate a reference to the record in `collaboration.record`.
3. As we now have a collaboration record, we can easily add also the corresponding experiment tag.

So we would actually do steps 2. and 3. together, and it would be more similar to `exp4coll` than to your hardcoded lists.

Would something like that work? It would also be good if you could provide examples of pairs of non-normalized/normalized collaboration names so we have something to tune our algorithm on.

**Comment by ksachs** [comment]
yes, that sounds good.
1. was mainly due to bad metadata we got from arXiv. I this this is mostly fixed.
2. the only tricky part is that collaboration names are not strictly normalized. Somehow we have to allow for the `Belle Tracker Group`, if possible normalize `BELLE -> Belle`, `BELLE II -> Belle-II`

**Comment by ksachs** [comment]
Another example: there was the experiment name in the collaboration field:
`001848199 CERN-LHC-CMS`
For the code it is difficult to understand that CERN-LHC is not a subgroup. That's why I check the list manually. In any case the identified collaboration is put in front so you can search for all subgroups with `cn CMS*` : `CMS CERN-LHC`
And to be sure nothing is missed the experiment search is a bit fuzzy, so I also get the US-CMS group, which I manually delete: ` ['CERN-LHC-CMS', 'FNAL-E-0892']`

**Comment by hoc3426** [comment]
Hi All,
Here's the dictionary of 
Collaboration name -> experiment tag
I use in case it's of any help
https://github.com/hoc3426/heath-inspire-scripts/blob/master/hep_collaboration_experiment.py

**Comment by michamos** [comment]
We should also normalize based on the subgroup name: if no collaboration is found, search in `collaboration.subgroup_names`, and normalize and link based on that name.
