### ISSUE TITLE
No save with empty subfield in conference editor

### ISSUE THREAD

**Issue by ksachs** [inspirehep/inspirehep#1705]
**Describe the bug**
In the Editor for conferences it is not possible to save the record if there is a stray empty subfield for series.number

**To Reproduce**
1. https://inspirehep.net/editor/record/conferences/1774115
2. delete content of series.number
you get a subfield with description "Number of the conference in the series" displayed
3. I don't see a way to delete the subfield
4. It is not possible to save the record in this state
5. I have to delete the field and create a new one with that series

**Expected behavior**
Empty subfields should be deleted on save.
Unless the field is mandatory
Are there other fields affected?

**Screenshots**
![Screenshot from 2021-02-11 11-19-52](https://user-images.githubusercontent.com/7591594/107624498-4592bb80-6c5b-11eb-9af8-0ed49dc69008.png)

**Comment by michamos** [comment]
Exception caught on sentry: https://sentry.inspirehep.net/inspire-prod/record-editor/issues/24154/?query=is%3Aunresolved
