### ISSUE TITLE
Report issues to curators

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspirehep#1706]
It would be good to have some mechanism to collect and report warnings from automated tasks to curators, so they can investigate and fix them, for example:
* HAL push failures
* Collaboration normalization
* Ambiguous reference matches

Idea: we could write to the logs in some specific format and have a separate process extract the data from the logs and send it somewhere (RT, zulip, etc.), either in real time or periodically.

**Comment by michamos** [comment]
This can now be done with saved searches on Kibana. We need to define exactly what kind of data access is required.

**Comment by michamos** [comment]
We need to revisit this

**Comment by drjova** [comment]
@michamos what kind of information we will need for each case? Could we have a detailed example for each?

**Comment by michamos** [comment]
It's probably better to discuss this in person

**Comment by drjova** [comment]
@michamos we will ask for more cases to understand better the issue.
