### ISSUE TITLE
Improve title merging

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspirehep#1719]
* For arXiv on arXiv, keep both titles instead of conflicting.
* For the other cases, titles should be normalized before comparing (lowercase everything, normalize hyphens, maybe ascii-folding?)

**Comment by pazembrz** [comment]
TECH:
Add in the config https://github.com/inspirehep/inspire-json-merger/blob/e2e484d1d19488a64240376cc28f81d1883bf47c/inspire_json_merger/config.py#L96-L115 for arxivonarxiv an 'titles' key to merge titles together https://github.com/inveniosoftware-contrib/json-merger/blob/e32cd749cc6b873d4c95f140ca9aa7c839c0bb3c/json_merger/config.py#L81-L82
