### ISSUE TITLE
workflows: new harvest marked previous harvests as completed and superseded them

### ISSUE THREAD

**Issue by drjova** [inspirehep/inspirehep#1730]
See https://inspirehep.zulipchat.com/#narrow/stream/122199-ops/topic/bugninja/near/270236344

It looks like we are aborting worfkflows when there's a match with an unfinished workflow in the holdingpen that has a different source. We should find a better way to deal with this situation as it causes us to loose legitimate updates.

**Comment by MJedr** [comment]
**TECH NOTES**
Instead of checking if the source [here](https://github.com/inspirehep/inspire-next/blob/fae46d3bd5f032987f14a6cbd2b1d202a8bda7d8/inspirehep/modules/workflows/workflows/article.py#L486) is the same we can check if it's submission (and then stop workflow).
