### ISSUE TITLE
Handle hidden records correctly

### ISSUE THREAD

**Issue by StellaCh** [inspirehep/inspirehep#1739]
See https://inspirehep.zulipchat.com/#narrow/stream/195298-experts/topic/Fermilab.20collection

Some records are not part of the main Literature collection so should not be shown in the default search, yet they're not really private so knowing unauthenticated users should be able to search for them somehow and records in those collections should be visible.

## Classification
We'll need to refine our current public/private simple permission distinction and have three collection types in total:
1. **public records**: these records have `Literature` in `_collections`. They are show in the search by default and any user is allowed to see the records.
2. **hidden records**: these records have at least one of the following in `_collections`, but are not public:
* `CDF Notes` 
* `CDS Hidden` 
* `D0 Preliminary Notes` 
* `Fermilab` 
* `HAL Hidden` 
* `LArSoft Notes` 
* `SLAC` 
* `ZEUS Preliminary Notes` 

They will not be visible in the search by default but will require adding a request arg, and any user is allowed to see the records.
3. **private records**: these records don't have values in `_collections` making them either public or hidden. They are never shown in the search to non-privileged users, and those users are not allowed to access the records either.

Note that behaviors 1. and 3. already exist, 2. is new

## New features
These features only concern non-privileged users (not authenticated, or authenticated by having no superadmin or curator privileges). Admins and curators should still get the current behavior (including the visible collection facet).

1. For **hidden records**, adding a `collection={collection_name}` request argument (example: https://inspirehep.net/literature?sort=mostrecent&size=25&page=1&q=&collection=fermilab) will switch the search from searching for `_collections:Literature` (this currently happens in https://github.com/inspirehep/inspirehep/blob/6f7e3aab8f4b820a9e24b431a8749a0b0dff1b30/backend/inspirehep/search/api.py#L191) to searching in that collection. Non-privileged users should never see **private records** in search results.
2. When a hidden collection is active, any search typed in the search bar (until I go back to the main page or switch to a non-Literature collection) should stay in that collection.
3. The permission check on record access needs to be changed to only disallow non-authenticated access to **private records**. So https://inspirehep.net/literature/1861814 should return a 200 for everyone, instead of 401 as is currently the case for non-privileged users.

**Comment by drjova** [comment]
TECH NOTES:

1. Read the `collections` parameter in https://github.com/inspirehep/inspirehep/blob/6f7e3aab8f4b820a9e24b431a8749a0b0dff1b30/backend/inspirehep/search/api.py#L191 and by deafault the `_collections` should be `Literature`
