### ISSUE TITLE
Decode LaTeX in arXiv parser

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspirehep#1754]
Currently we don't do any specific post-processing of arXiv titles and abstracts. However, they might contain LaTeX escape sequences. While we support them for math, we don't support them for text, so those would need to be converted to unicode using `pylatexenc`. See for example https://inspirehep.net/literature/1705614 which displays this issue, both in title and abstract.

TECH NOTES:
* Add a new static method to the arXiv parser in hepcrawl that takes a string and converts LaTeX escape sequences to unicode. This should use [`pylatexnenc.latex2text.LatexNodes2Text`](https://pylatexenc.readthedocs.io/en/latest/latex2text/#pylatexenc.latex2text.LatexNodes2Text) with `math_mode="verbatim"` in order to preserve the LaTeX markup inside math environments.
* Use that method in `title` and `abstract` to convert them to unicode outside of math environments.

Test case:
The title in the provided record, `$L^2$ vanishing theorem on some K\"{a}hler manifolds` should become `$L^2$ vanishing theorem on some Kähler manifolds`.

**Comment by michamos** [comment]
Some discussion happened on Zulip following https://inspirehep.zulipchat.com/#narrow/stream/195298-experts/topic/bibtex.20issues/near/230612064. Better be conservative and unescape only the characters declared as [supported by arXiv](https://arxiv.org/help/prep#accents), otherwise we might accidentally mess up things. I've done that in a new PR.

**Comment by michamos** [comment]
Why was this closed? it has never been deployed :confused:

**Comment by oguzdemirbasci** [comment]
> Why was this closed? it has never been deployed 😕

Sorry, my bad. I thought you were putting your PR's to another issue.
