### ISSUE TITLE
[UI] Bulk interface for assign conferences

### ISSUE THREAD

**Issue by drjova** [inspirehep/inspirehep#1765]
Create a new action item 'tools' in literature, visible only to curators and superusers with the options: 'assign conference'

The prototype is found here: https://www.figma.com/proto/TUAMWktXlnKLOivYGg9p2V/Other-collections?node-id=344%3A5206&viewport=1676%2C306%2C0.3636794090270996&scaling=min-zoom

Add a checkbox on the left of each search item in literature. (This exists already for authors). A checkbox next to the number of results should also be added that allows users to select all results.
Assign conference: A drawer with a conference search is displayed (similar to the claiming interface for authors). When the user selects the appropriate conference, a confirmation modal appears.

UI:
* Add a new route `curation` here https://github.com/inspirehep/inspirehep/blob/master/ui/src/App.jsx, and use the same components there (`curation/literature` etc.).
* If user is `curator` or `superuser` https://github.com/inspirehep/inspirehep/blob/master/ui/src/literature/containers/LiteratureSearchContainer.jsx#L98 add a drop down (as described in the mockup)
  * Disable drop down if search results are more than `9999` results

* If user is `curator` or `superuser` https://github.com/inspirehep/inspirehep/blob/master/ui/src/literature/containers/SearchPage.jsx#L21 create an AssignVIewContext as https://github.com/inspirehep/inspirehep/blob/master/ui/src/authors/containers/AuthorPublicationsContainer.jsx#L27-L36
 and an AssignDrawer as https://github.com/inspirehep/inspirehep/blob/master/ui/src/authors/components/AssignDrawer/AssignDrawer.jsx
  * Add the confirmation box
  * We should pass to the API the current  query for assigning conferences if user select all otherwise we should pass the recids of the selected record. Display an alert with a message from the API response.

@StellaCh what message should we display on success or error?

**Comment by StellaCh** [comment]
Finally, we are going forward with the option to create a new interface for curators. What do you need to refine this solution?

**Comment by StellaCh** [comment]
Regarding 
>@StellaCh what message should we display on success or error?
It should be the same messages we display for the claiming interface when we assign papers to authors.

**Comment by StellaCh** [comment]
As discussed, if I have 500 results and I select the first page with 250 results we should display:

- [ ] 250/500 results
