### ISSUE TITLE
[Backend] Bulk interface for assign conferences 

### ISSUE THREAD

**Issue by drjova** [inspirehep/inspirehep#1768]
BACKEND:
Refactor https://github.com/inspirehep/inspirehep/blob/master/backend/inspirehep/assign/views.py#L67-L84 to be author specific and add 2 new endpoints for assigning conferences to literature:
1. Endpoint that accepts `recids` and create a celery task which will create a chain of update tasks  
~~2. Endpoint that accepts a search query and create a celery task which gets the `recids` from ES  and create a chain of update tasks~~

The API should return `200`, `400`  or `500`

**Comment by pazembrz** [comment]
Literature record should be assigned as `conference paper` to conference unless the paper already has `proceedings` among `document_type`
