### ISSUE TITLE
Don't allow undeleting records

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspirehep#1794]
In the record editor, it's possible to undelete deleted records. This is not currently handled correctly, some PIDs (at least the primary ones like `lit`, `con`, etc.) remain deleted. It seems that undeleting records is a very rare occurrence and is not actually a required feature, so we should simply disallow undeleting (or even updating) deleted records.

TECH NOTES:
* Add `force_undelete` flag in `update` function on  [record base](https://github.com/inspirehep/inspirehep/blob/master/backend/inspirehep/records/api/base.py#L445)
* Throw a validation error in update record when `deleted: true` changed to `deleted: false`

**Comment by drjova** [comment]
@michamos what we will do with the redirected records?
