### ISSUE TITLE
mint PIDs for existing author BAIs

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspirehep#1830]
We have a feature flag to enable BAI PID minting, but we can't turn it on in prod currently for two reasons:
* BAIs will start to diverge from legacy (legacy is minting more PIDs than what is exposed in author records)
* the sequential approach to BAIs (`J.Smith.3` is minted after `J.Smith.4`) makes it impossible to mint PIDs for records one by one during the migrator, as we might mint a BAI that is still to come later in the migration, causing a collision.

So we would need to have a way to have a two-step process after switching off legacy:
1. Mint PIDs for all existing BAIs in author records through some script/CLI.
2. Enable the PID minting feature flag.

The procedure should be tested on QA by turning off author disambiguation and the minting feature flag, removing all existing BAI PIDs from the pidstore, running the script then turning on minting and disambiguation again. No collisions should occur.

**Comment by pazembrz** [comment]
Tech Notes:
* Enable `FEATURE_FLAG_ENABLE_BAI_PROVIDER` Flag.
* Add new Feature Flag to disable BAI minter `create` method ONLY https://github.com/inspirehep/inspirehep/blob/60155f9ddc036932bb3653e11e1696ab2b4daf7c/backend/inspirehep/pidstore/minters/bai.py#L49. 

Now all PIDS which are already present in records should be minted. Records without BAI should be ignored until second flag will be enabled.
