### ISSUE TITLE
Some records are not indexed

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspirehep#1848]
From https://inspirehep.zulipchat.com/#narrow/stream/195298-experts/topic/Profile.20author.20disconnect/near/235354920: 

Thorsten said:

    mmh, actually simple search like

    recid:1430804
    recid:1747121
    recid:1704911

    doesn't turn up the desired records

    more records not indexed properly

    recid:1592520
    recid:1507561

I manually edited the first on the labs editor and it got indexed properly. I'm not sure what's going on. @drjova  do you think this is related to the batch index failure we experienced recently?

**Comment by tsgit** [comment]
some labs index holes Thu Apr 22 00:59:59 CEST 2021:

these searches 

recid:1592520
recid:1507561
recid:1747121
recid:1592520

return nothing. It appears that none of the info in those records is indexed.

e.g.
https://inspirehep.net/literature/1747121
has a DOI, but

https://inspirehep.net/literature?sort=mostrecent&size=25&page=1&q=doi%2010.1007%2F978-3-030-04260-8

returns nothing.

https://old.inspirehep.net/search?p=doi+10.1007%2F978-3-030-04260-8

works as expected.

meanwhile empty search on legacy vs labs returns a difference of 3

1,417,473 vs
1,417,470

so something else is askew, too.

(the totals change, but the difference of 3 has been consistent for a couple of days now)

**Comment by michamos** [comment]
I believe I found the root cause in https://inspirehep.zulipchat.com/#narrow/stream/122202-devel/topic/index_record.20vs.20batch_index/near/235853889: records 1729274 and 1735862 have no history which causes indexing to fail for their batches. We should fix that (either manually clean history or purge those records from the DB completely) and do a full reindex of literature, making sure that no batches fail.
The additional records present on labs and not legacy can also be found in that list. I'll check those.

**Comment by tsgit** [comment]
an empty search on labs vs legacy still returns a different number of HEP records
1,418,623 labs vs 1,418,626 legacy    so a difference of 3 records
