### ISSUE TITLE
Check if France in fulltext in workflow

### ISSUE THREAD

**Issue by StellaCh** [inspirehep/inspirehep#1854]
In the workflow we need to add the following step (presented in https://miro.com/app/board/o9J_kiinL1c=/), before checking if it's CORE:

Does the paper have 'France' in the fulltext? Then create a ticket for HAL

See https://github.com/inspirehep/inspirehep/issues/1514

**Comment by StellaCh** [comment]
@michamos can you write more details about the ticket to HAL - to whom would it be assigned? Is there an existing queue already?

**Comment by michamos** [comment]
@mathieugrives I don't remember what we discussed. Should we assign those tickets to you personally? Or should we create a new RT queue?

**Comment by mathieugrives** [comment]
@michamos Tickets to me personally, please, if you also think it's the simpler solution. It can be in the general curation queue, and then, after a check, I assign them to my curators, treat them personally  or put them to "anyone" if it is a false positive.

**Comment by mathieugrives** [comment]
@michamos I would also need tickets systematically assigned to me for new records arriving in HAL Hidden collection, if it's possible. I think it's more reliable than the France word, often unfindable in these records.

**Comment by MJedr** [comment]
**TECH**
1. Create a function `check_if_france_in_fulltext` and use [grobid](https://github.com/inspirehep/inspirehep/issues/1514#issuecomment-730326219) to check if France is in fulltext
2. Create an environmental variable with Mathieu id 
3. Create a new function which will create a ticket by calling `submit_rt_ticket`, using same parameters [as here](https://github.com/inspirehep/inspire-next/blob/f68516cbf4951cb4c70789e6dbbe5c167ee24c32/inspirehep/modules/workflows/workflows/article.py#L284-L287) plus a new env variable as `requestors`
2. Add a step to workflow in [`POSTENHANCE` before this line](https://github.com/inspirehep/inspire-next/blob/f68516cbf4951cb4c70789e6dbbe5c167ee24c32/inspirehep/modules/workflows/workflows/article.py#L299). If True call the new function
