### ISSUE TITLE
Order fields in author editor

### ISSUE THREAD

**Issue by StellaCh** [inspirehep/inspirehep#1864]
- Ordering should be:

1. IDS
2. NAME
3. POSITIONS
4. _private_notes 
5. EMAIL
6. STATUS
7. PROJECT MEMBERSHIP

and then all the rest of the fields

- Do not display: $schema

- Order inside `name`:

1. Preferred Name
2. value
3. Title
4. Numeration
6. Name Variants
7. Native Name

- Order inside `positions`:

1. Current
2. Institution
3. Start Date
4. End Date  
5. Rank 
6. record
7. hidden
8. curated relation

- Order inside `project membership`:

1. Current
2. Name
3. Start Date
4. End Date  
6. record
7. hidden
8. curated relation

- Order inside `Advisors`:

1. ids
2. name
3. degree type 
and display these 3 fields always by default

- Remove delete option from `positions` and `email addresses`: when you click on `positions`, you have the option to 'Add new' or 'Delete' - remove (or deactivate) the delete option

- positions>rank: order dropdown options alphabetically 

- positions>record: remove api from link. it should link to an institution page eg: https://inspirehep.net/institutions/902885

- ids>schema: Can ID choices be re-ordered with the most common ones used by HEPNAMES on top: INSPIRE ID, ORCID, BAI, CERN, Wikipedia, etc.

**Comment by MJedr** [comment]
@StellaCh the changes should be for hep or authors?

**Comment by StellaCh** [comment]
I don't understand the difference. The changes should be in the author record editor, both the one we have in the holdingpen and the one that curators will see when they edit an author from the author profile and the search authors public pages.

**Comment by drjova** [comment]
TECH NOTES:

* Add in [authors config](https://github.com/inspirehep/inspirehep/blob/master/record-editor/src/app/shared/config/authors.config.ts#L27) 

```json
{
  schemaOptions: {
    order: []
  }
}
```
