### ISSUE TITLE
holdingpen improvements for journals

### ISSUE THREAD

**Issue by StellaCh** [inspirehep/inspirehep#1865]
- [x] search for DOI 
- [ ] Search for title, author, journal pub-note would be extremely helpful
- [ ] A facet for journals would be helpful to split work between Florian and Kirsten

**Comment by pazembrz** [comment]
TECH:
Add a check here https://github.com/inspirehep/inspire-next/blob/f3a85e38c87dea44c41f7debdd9553a13c2e993e/inspirehep/modules/workflows/tasks/actions.py#L910 if there are more than one result then do not set collaboration reference.

**Comment by MJedr** [comment]
The search for does must be done like that (with quotes): `metadata.dois.value: "10.1016/j.dark.2020.100743"`

Update mapping - add:
* `titles`
* `authors.full_name`
* `pub_note`
* `journals`.

Add a facet for journals here:
https://github.com/inspirehep/inspire-next/blob/f3a85e38c87dea44c41f7debdd9553a13c2e993e/inspirehep/config.py#L1335
