### ISSUE TITLE
Clarify wording on signup page

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspirehep#1872]
When creating an INSPIRE account, users are getting redirected from ORCID back to a page displaying the message https://github.com/inspirehep/inspirehep/blob/6f7e3aab8f4b820a9e24b431a8749a0b0dff1b30/ui/src/user/components/SignUpPage.jsx#L15-L16

It doesn't seem obvious to some users that this is required, and they won't be properly logged in if they don't. We should improve the message to clarify that.

**Comment by StellaCh** [comment]
The new text should be:

> Please let us know your e-mail address to complete your account registration.
