### ISSUE TITLE
CV format should be cached

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspirehep#1887]
We don't seem to pre-render the CV format at indexing time, but instead generate it at search time:
https://github.com/inspirehep/inspirehep/blob/9e8060d78172520614bf007bf3ba8291da5288dd/backend/inspirehep/records/serializers/cv.py#L44-L47
This makes it unusable for authors having a large number of collaboration papers with many authors.

**Comment by tsgit** [comment]
for example, pick some CMS author
https://inspirehep.net/authors/1020601
use the date facet to select year 2018
that gives 142 records
select `cite all` -> `CV (html)`       this times our for me

**Comment by pazembrz** [comment]
Tech Notes: 
1. Add entry for CV format in here https://github.com/inspirehep/inspirehep/blob/f30063c16774758f878e23ae7722b0ab21353e44/backend/inspirehep/records/marshmallow/literature/es.py#L40 with `"text/vnd+inspire.html+html"` mimetype. It shoudl be similar to [other cached entries](https://github.com/inspirehep/inspirehep/blob/f30063c16774758f878e23ae7722b0ab21353e44/backend/inspirehep/records/marshmallow/literature/es.py#L45-L47) 
2. Update this https://github.com/inspirehep/inspirehep/blob/f30063c16774758f878e23ae7722b0ab21353e44/backend/inspirehep/records/config.py#L644-L652 to include only CV cached field from ES also extend https://github.com/inspirehep/inspirehep/blob/f30063c16774758f878e23ae7722b0ab21353e44/backend/inspirehep/records/config.py#L654-L661 to properly exclude all fields except CV when CV format is requested.

Note: Currently ES is failing to return response as it's trying to return all the authors and response is just too too big.
