### ISSUE TITLE
Submission rejection reason is not communicated to user any longer

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspirehep#1895]
When a submission gets rejected, the curator can choose among predefined rejection reasons or even manually edit the reason. This rejection reason should be shown to the submitter, as it should be put into the RT reply. However, this behavior seems to be broken since the workflow change in https://github.com/inspirehep/inspire-next/commit/1721346f57bcea321583638123e4395a692ecf74#diff-be749b2eb22809aff7ab7b72d436c11b4171579d16c85e1a7cd411355c7a5e90. We should fix that.

**Comment by drjova** [comment]
@michamos is it just the message or the ticket is not closed at all?

**Comment by michamos** [comment]
ticket gets closed with a message saying only "Article rejected": https://rt.inspirehep.net/Ticket/Display.html?id=1136265.

**Comment by drjova** [comment]
AFAIS in the code, correct me if I'm wrong, that was always the case. [Previously](https://github.com/inspirehep/inspire-next/commit/1721346f57bcea321583638123e4395a692ecf74#diff-be749b2eb22809aff7ab7b72d436c11b4171579d16c85e1a7cd411355c7a5e90L316) was passing `Article automatically rejected` [message](https://github.com/inspirehep/inspire-next/blob/0662a4a965db24b8bd0e3b0c4ecb3523264e8d40/inspirehep/modules/workflows/tasks/actions.py#L192-L211) and not what the curators write as an explanation.

**Comment by michamos** [comment]
No, at some point in the past it was putting the message chosen by the curators, I'm absolutely certain of that.

**Comment by drjova** [comment]
https://rt.inspirehep.net/Ticket/Display.html?id=1137096
