### ISSUE TITLE
OSTI identifier sync

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspirehep#1929]
At Fermilab, they need to deposit all their publication in the OSTI repository, and the corresponding OSTI identifier should be added to the INSPIRE record after depositing.

@hoc3426 [mentions on the chat](https://inspirehep.zulipchat.com/#narrow/stream/202056-curation/topic/multiedit.2Fbatchupload.20requests/near/241931409) that currently, it works as follows:
> 1. I collect a list of all the new Fermilab papers that don't have an OSTI ID and create an xml output in a special format and send it to OSTI
> 2. OSTI sends back an xml file pairing the INSPRE recids with the new OSTI IDs.
> 3. I create from that an  OLD INSPIRE xml file that appends the OSTI IDs to the 035 field of the INSPIRE records

> This is usually done on a weekly basis and typically involves  around 5 to 20 records. It doesn't have to happen on any sort of regular basis and occasionally can go a month with no action. At the time of the switch over from SPIRES to INSPIRE, though, it went a very long time and the Director was asked by the DOE what was going on. So long as that is avoided :)

> It can, of course, be done manually if needed (just editing records to add the OSTI ID). It's a little tedious and error prone but means there is no crisis if it's not there from Day One.

More details on the process:
> 1. records are only sent if we have approved them and there is a link to the Fermilab Server indicating Fermilab has "published" the paper 
*OR* it is a  paper where the Fermilab report is hidden (like CMS) in which case we simply send the arXiv PDF
> 2. records at OSTI also have to be updated when we get accepted manuscripts. When this happens we send the accepted PDF, named with the OSTI ID, e.g. 123534.pdf to the OSTI pdf site.  Naturally we have to keep a record of all the accepted PDFs we have already sent. Usually this happens several months after the original submission to OSTI and is triggered by a link to "Fermilab Accepted Manuscript", "Fulltext from Publisher" or "PDF from SCOAP3" (not sure on the exact wording of that last one).

Possible approaches:
*  push all relevant records to OSTI from INSPIRE directly, similarly to what we do for HAL or ORCID
*  push to OSTI like you're currently doing, but have a periodic task in INSPIRE to fetch the OSTI identifiers using their API and match with our records based on DOI/report number, etc.
*  keep doing what you're doing, and have a dedicated API in INSPIRE to add OSTI identifiers to records

> Because of all this book-keeping, which we have in place on the Fermilab side and which are able to quickly update in case something changes, I might prefer the third option with the dedicated API to add OSTI identifiers but I'm open to other things if they would work better.

We need to define how to best do this on the new system from a technical point of view in a way that is compatible with Fermilab needs.

**Comment by michamos** [comment]
In case we want to go with the second approach like for CDS identifier sync, they seem to have a straightforward API that we could use (dates are in US `MM/DD/YYYY` format, but that's manageable) : https://www.osti.gov/api/v1/records?research-org=%22Fermi%20National%20Accelerator%20Lab.%20(FNAL),%20Batavia,%20IL%20(United%20States)%22&update-date-start=06/01/2021

**Comment by hoc3426** [comment]
One further complication is that although the OSTI ID is minted immediately, the record isn't created for several days, so it's not searchable until then.

**Comment by michamos** [comment]
Here are the requirements
## Definition of records to be sent to OSTI
Any record having the following metadata will be synced with OSTI:
1. a `report_numbers.value` starting with `FERMILAB`
2. either
    * a `urls.value` starting with `https://lss.fnal.gov`
    * `report_numbers.hidden: True` (for the list element satisfying 1.) and an `arxiv_eprints.value` field

## Sync process
Any record satisfying the above requirements will be synced to OSTI on every update, using the API documented in https://www.osti.gov/stip/document/an2411-web-services. 
There are two cases:
* The record doesn't contain an `external_system_identifiers.schema:OSTI`. This means that the record has never been pushed to OSTI. On the initial push, in case of success we'll receive a response from OSTI containing the OSTI ID in the response payload (in `//record/osti_id/text()` using XPath  selector syntax). This OSTI ID needs to be written back to the record (in `external_system_identifiers` with `schema: OSTI` and `value: {osti_id}`.
* The record already contains an `external_system_identifiers.schema:OSTI`. It has already been pushed to OSTI, so we need to update the record there by including `<osti_id>{osti_id}</osti_id>` in the POST payload.

We should lock the records like for HAL to avoid concurrent pushes of the same record

## Metadata conversion
The metadata for OSTI needs to be sent in a special format that is part of the API documentation (basically an XML serialization of a simple key-value structure, only authors seem to be a bit more nested). There are scripts in https://github.com/hoc3426/heath-inspire-new/blob/master/osti_web_service.py that already generate this metadata. We probably want to reimplement the same logic but the existing script can be used to make sure the same output is produced.

### Special considerations
* If the Fermilab report number is in the hidden field, send the eprint or some other PDF.
https://github.com/hoc3426/heath-inspire-new/blob/master/osti_web_service.py#L455-L461
Test case: https://inspirehep.net/literature/1856090
* Check to see if it’s a corporate author paper
https://github.com/hoc3426/heath-inspire-new/blob/master/osti_web_service.py#L506-L509
Test case: https://inspirehep.net/literature/1945404
* Don’t send more than 20 authors
https://github.com/hoc3426/heath-inspire-new/blob/master/osti_web_service.py#L511-L515
Test case: https://inspirehep.net/literature/1916528
* Accepted manuscripts (there's a `urls.description` matching https://github.com/hoc3426/heath-inspire-new/blob/a00ae7f4f2278ae712072b1e680f6e100951a0cd/check_url.py#L7-L10 case-insensitively) need to have `<journal_type>AM</journal_type>`.
Test case: https://inspirehep.net/api/literature/1929143

### More examples
[tmp_osti_web_service.txt](https://github.com/inspirehep/inspirehep/files/7468745/tmp_osti_web_service.txt)
(several records grouped together, we'll send them one by one, but we still need to wrap it as `<records><record>...</record></records>`).

**Comment by MJedr** [comment]
**TECH NOTES**
1. On record create or update (if criteria are satisfied - see `Definition of records to be sent to OSTI`) push to OSTI
2. Get the record and translate it to osti format 
* push always with Heath details 
* translation details are there https://github.com/hoc3426/heath-inspire-new/blob/master/osti_web_service.py
* use xml builder for that
3. Push to https://www.osti.gov/stip/document/an2411-web-services 
* ask Heath for credentials, they should be added to k8s as sealed secrets
* there is test api, might be used for qa 
* do it the same as for hal (including locks)

**Comment by michamos** [comment]
There is currently no way forward because we can't get credentials to use the service, so let's close this for now.
