### ISSUE TITLE
Improve affiliation normalization

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspirehep#1930]
An author might have several affiliations and raw affiliations, but currently we assign all affiliations of the author based on a single raw affiliation. This might cause "phantom" affiliations to be added, coming from the other affiliations of the matched author that have nothing to do with the raw affiliation in question. For example, in https://inspirebeta.net/api/literature/1985763, the third author has among its raw affiliations
> Helmholtz Forschungsakademie Hessen für FAIR (HFHF), GSI Helmholtzzentrum für Schwerionenforschung, Campus Frankfurt, Max-von-Laue-Str. 12, 60438 Frankfurt, Germany

which gets mapped to
```python
[{u'record': {u'$ref': u'https://inspirebeta.net/api/institutions/902780'},
  u'value': u'Dubna, JINR'},
 {u'record': {u'$ref': u'https://inspirebeta.net/api/institutions/1850857'},
  u'value': u'Helmholtz Res. Acad. Hesse for FAIR'},
 {u'record': {u'$ref': u'https://inspirebeta.net/api/institutions/903807'},
  u'value': u'Darmstadt, GSI'}]
```
of these, only the second one is correct.

We can improve the current situation by counting `raw_affiliations` and `affiliations` in the matched literature record. There are two clear situations:
* `len(raw_affiliations) == len(affiliations)`: we can assume that a single raw affiliation maps to a single affiliation in the same order, and assign that affiliation only
* `len(raw_affiliations) == 1`: we can assume, as we do currently, that all affiliations correspond to that single raw affiliation, and assign all of them.

In other cases, it's ambiguous and we should avoid assigning the affiliation based on this match, and use the next match instead.

**Comment by MJedr** [comment]
**TECH**
In [here](https://github.com/inspirehep/inspire-next/blob/807c31ef64a182c2b0675eb2eadc661d94c2b717/inspirehep/modules/workflows/tasks/actions.py#L1007) add the check `if len(raw_affiliations) == len(affiliations) or len(raw_affiliations) == 1` and assign affiliations only in that case.

**Comment by fschwenn** [comment]
I have no idea how the aff normalization works in detail. From my naive perspective it would be interesting to understand **why** this happens. By this heuristic approach you might remove some good matches and nevertheless some bad matches slip through.

**Comment by michamos** [comment]
Sorry, I hadn't reviewed the PR and I realize right now that the implementation is not correct, so I'm reopening it for next sprint.
* Instead of looking at number of affs and raw affs of the matched author, it looks at the current author after matching, which is not the same thing.
* It doesn't take the next match if the current match doesn't satisfy the criteria, but instead doesn't assign affiliations at all.
