### ISSUE TITLE
Don't reset the `curation collection` facet when doing a search

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspirehep#1945]
@PaulinaBaranowska reports that it would be more useful to keep that facet active even when doing a search. Currently, it gets reset after changing the search query like all facets.

**Comment by MJedr** [comment]
**TECH NOTES**
Add `curation_collection` [to the `persistedQueryParamsDuringNewSearch` here](https://github.com/inspirehep/inspirehep/blob/13611dfecb47ff2c94d1eb5d138e6bdcd842292d/ui/src/search/config.js#L40)
