### ISSUE TITLE
arXiv completeness check

### ISSUE THREAD

**Issue by StellaCh** [inspirehep/inspirehep#1955]
Create a script that regularly checks missing arXiv CORE records. This script exists on legacy and we also used to have a similar one on labs a while ago - we just need to resurrect it.

**Comment by MJedr** [comment]
**TECH NOTES**
* Create a new repo in cerns-sis, which will used for completeness checks in our different projects.
* Create a cli that will reuse [this completeness check](https://gitlab.cern.ch/inspire/images/-/blob/master/arxiv-harvest-check/arxiv-harvest-check.py) (code must be refactored).
* Add a dockerfile which will run the cli command
* Add the cronjob in hep application that will run everyday from Monday to Friday. Make sure to pass all the necessary secrets for Zulip.

**Comment by drjova** [comment]
@benjamin-bergia ☝️ could you please have a look?
