### ISSUE TITLE
Change text for claim papers in profile

### ISSUE THREAD

**Issue by StellaCh** [inspirehep/inspirehep#1958]
In the author settings, we have instructions that ask users to go to legacy to claim their papers. Update these instructions with the current process on labs

**Comment by drjova** [comment]
TECH NOTES:
* Change the text here https://github.com/inspirehep/inspirehep/blob/master/ui/src/authors/components/OrcidPushSetting.jsx#L16-L21

**Comment by StellaCh** [comment]
Also the text under the toggle should be changed. 
I found a screenshot here: https://its.cern.ch/jira/browse/INSPIR-3450 , please let me know of the whole text so that I can provide a replacement.

**Comment by hanadikaleel** [comment]
Clean your INSPIRE profile
              Before you export your publications to ORCID, you must clean up
              and prepare your INSPIRE author profile. The goal is to have a
              unique INSPIRE profile associated to you, with all works marked as
              yours.

              The most expedient way to clean your profile is to obtain an arXiv
              ID and login to INSPIRE using this arXiv ID. If you don’t use an
              arXiv ID, you can make changes to your profile as a guest, but all
              actions will require approval from the INSPIRE team, which may
              take a few days depending on how many requests are before yours.
              If you don’t mind waiting, you can follow the instructions below
              without signing in with an arXiv ID and still prepare your author
              profile for an ORCID connection. Please be aware that this
              approval process is necessary to ensure the quality of the
              information we have in INSPIRE.

              <ExternalLink href="//inspirehep.net/info/HepNames/connect_orcid#hide1">
                Instructions on cleaning your profile
              </ExternalLink>

    Claim your work

              Once your profile is clean, you need to confirm that the{' '}
              <ExternalLink href={`//inspirehep.net/author/claim/${authorBAI}`}>
                listed works
              </ExternalLink>{' '}
              are yours. Only claimed works will be pushed to ORCID.

              Note that cleaning and claiming have to be done periodically, in
              order to keep your profile up to date
    
    Connect your INSPIRE author profile to ORCID

              Once you clean up your INSPIRE author profile and you claim your
              works as explained above, you are ready to export them to ORCID.

        Note that if you use your ORCID when publishing a paper, INSPIRE will
        automatically attribute it to you and send this information to the ORCID
        register. If you don’t, or if the publisher doesn’t send this
        information to INSPIRE, you need to claim it.
 
        If you have questions or need assistance during any steps of this
        process, don’t hesitate to send a message to{' '}

**Comment by hanadikaleel** [comment]
If toggle is enabled:


  This profile is already connected to the following ORCID:
          <OrcidProfileLink orcid={orcid} />
          Your{' '}
          <ExternalLink href={`//inspirehep.net/author/claim/${authorBAI}`}>
            claimed
          </ExternalLink>{' '}
          works will be exported automatically.

**Comment by StellaCh** [comment]
1. If toggle is enabled, keep the same text, but remove the ExternalLink:

> 
> This profile is already connected to the following ORCID:
> 
> Your{' '}
> <ExternalLink href={//inspirehep.net/author/claim/${authorBAI}}>
> claimed
> {' '}
> works will be exported automatically.



2. If toggle is disabled, again, keep the same text but remove the link:
 

> Your INSPIRE{' '}
>           <ExternalLink href={`//inspirehep.net/author/claim/${authorBAI}`}>
>             claimed
>           </ExternalLink>{' '}
>           works will be exported to your ORCID account. 

3. Change the text under the toggle to:

Your INSPIRE works are not exported to your ORCID{' '}
    <OrcidProfileLink orcid={orcid} /> yet. Please note that only the
    publications that are verified as yours on INSPIRE will be exported to
    ORCID. 

A new interface that will allow you to claim your papers is coming up soon. In the meantime, if you wish to claim a paper as yours, you can send your request at <TBD-----inspirehep.net>.
