### ISSUE TITLE
Make 412 error more clear in editor

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspirehep#1971]
If you save a record in the regular editor (at `/editor/record`), go back and save again, you get a 412, as the underlying version has changed and the `If-Match` check now fails, but the editor has not reloaded the record. This should be dealt with better, either by displaying a more clear error message, or maybe auto-reloading the record (not sure that makes sense).

**Comment by oguzdemirbasci** [comment]
TECH NOTES:

* Copy `check_etag` function from [here](https://github.com/inveniosoftware/invenio-rest/blob/master/invenio_rest/views.py#L250) and paste it as an overriden method into `RecordResource` class that is defined [here](https://github.com/inspirehep/invenio-records-rest/blob/master/invenio_records_rest/views.py#L715).
* Modify the `abort(412)` lines as it will contain the error message: `abort(412, "The record version {} is not matching the current version {}".format(etag, ', '.join(request.if_match.as_set())))`
