### ISSUE TITLE
Select multiple workflows doesn't work

### ISSUE THREAD

**Issue by StellaCh** [inspirehep/inspirehep#1976]
Following the override coreness task https://github.com/inspirehep/inspirehep/issues/1690 , when I try to select multiple papers in https://inspirehep.net/holdingpen/list?page=1&size=10&workflow_name=CORE_SELECTION and click 'Accept' this doesn't work.

**Comment by michamos** [comment]
@drjova is this working correctly now?

**Comment by drjova** [comment]
It should be, what's the issue?
