### ISSUE TITLE
Merger is using `head` version acquisition_source.source instead of `update`

### ISSUE THREAD

**Issue by pazembrz** [inspirehep/inspirehep#1977]
https://inspirehep.net/api/holdingpen/3092316
In this WF we should have `desy` in acquisition_source.source not `arxiv` after merge.

https://inspirehep.zulipchat.com/#narrow/stream/122199-ops/topic/merger/near/243360930

Note from Micha:
I think it's due to the 3-way merging. We should erase the root for the acquisition source to be systematically updated to the update version.

**Comment by MJedr** [comment]
**TECH**
This problem appears only if `source` in `acquisition_source` is the same in root and update.

Create a [pre-filter](https://github.com/inspirehep/inspire-json-merger/blob/master/inspire_json_merger/pre_filters.py) which will remove `acquisition_source` from root.
