### ISSUE TITLE
Improve France detection and handling in workflows

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspirehep#1981]
@mathieugrives reports that the current France detection and ticket creation in the fulltext doesn't work well for his needs.
These are the required improvements:
* Tickets shouldn't be created only for arXiv, but for all records having France among `raw_affiliations`.
* For arXiv, on legacy we didn't have `raw_affiliations`, which is why fulltext was used. Instead, we can systematically extract `raw_affiliations` but only put it into the workflow for core records. For non-core, we could simply flag that `France` ha been seen in an affiliation (we could do this also for core of course).
* Tickets should be create only for new records.
* Tickets should be created in a new queue, `HAL_curation`, instead of assigning to Mathieu (this didn't work, he was set as the requestor, not the owner) so we can prevent other curators from closing the ticket by setting permissions properly. These tickets shouldn't be created instead of, but in addition to the regular curation tickets.

Is that correct @mathieugrives ?

**Comment by mathieugrives** [comment]
Yes:
- 100% of the records with a french author should be concerned: core + non core, arXiv or not, fulltext or not, in literature + hal hidden, all types of documents ; if there is a little bit of noise, that's OK, it's better than loose track of some records
- a separate HAL_curation queue is the best idea to not bother other curators, not have tickets closed without seeing them and apply the HAL export tag, or not lock records too long in case of french curators absence
- if possible, only me should be able to close these tickets, but that's not mandatory

Actual issues of the tickets (except the design):
- multiple tickets for a same record (for each update?)
- some tickets are empty (links to 'none')
- requestor and not owner

**Comment by MJedr** [comment]
**TECH**
1. Create a function that will check if France is in `raw_affiliations` which will be used for non-arxiv records
2. Create a function that will get `raw_affiliations` from grobid [as here](https://github.com/inspirehep/inspire-next/blob/c9c469a872a2a11b6e4c3fbb5d233d1b6a317872/inspirehep/modules/workflows/tasks/actions.py#L805-L809). Check if France is in xml (no parsing needed). That will be used for arxiv.
3. Modify `create_hal_ticket` - we no longer need Mathieu as user. As a queue use `HAL_curation`.
4. In workflows move the whole logic to `NOTIFY_CURATOR_IF_NEEDED`. 
    1. Check if it is a new record. 
    2. If yes, check if it is arxiv.
    3. For arxiv use the function created in step 2.
    4. For non-arxiv use the function created in step 1.
    5. If France was in full text, create ticket.
5. Remove `HAL_ADMIN_ID` from app config.
6. Create a new queue `HAL_curation` in Kubernetes and remove variable `APP_HAL_ADMIN_ID`.

**Comment by michamos** [comment]
@MJedr looks good! for step 6. do you mean create a new queue in RT rather than Kubernetes?

**Comment by mathieugrives** [comment]
If you need testing, you can compare with the actual [ForHal collection](https://old.inspirehep.net/search?ln=fr&cc=For+HAL&ln=fr&cc=For+HAL&p=&action_search=Recherche&sf=&so=d&rm=&rg=250&sc=0&of=hb) on Legacy.
It's very accurate to see all new records arriving for France. Except few false positives, they almost all should create a HAL_curation ticket.
