### ISSUE TITLE
Don't set core on updates

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspirehep#1991]
CORE should be set only for new records, not overridden in updates, see discussion in https://inspirehep.zulipchat.com/#narrow/stream/195298-experts/topic/CORE.20for.20updates.

**Comment by drjova** [comment]
TECH NOTES:

* https://github.com/inspirehep/inspire-next/blob/master/inspirehep/modules/workflows/workflows/article.py#L158-L166 check if it's an update don't set core
