### ISSUE TITLE
Wrong url for `open in editor` on holdingpen for authors

### ISSUE THREAD

**Issue by MJedr** [inspirehep/inspirehep#2006]
Currently, button `Open in editor` in author profile (on holdingpen) fails to save because  the validation function https://github.com/inspirehep/inspire-next/blob/master/inspirehep/modules/editor/api.py#L262 expects only `hep` workflows.

**Comment by drjova** [comment]
TECH NOTES:
* Instead of hardcoded `hep` https://github.com/inspirehep/inspire-next/blob/master/inspirehep/modules/editor/api.py#L262 it should read the schema from the workflow
