### ISSUE TITLE
HAL pushes stale metadata

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspirehep#2008]
We're sending the HAL push task during record update, not after record commit: https://github.com/inspirehep/inspirehep/blob/9281776185dfc3b363e0c900fd17523c0c5a9aad/backend/inspirehep/records/api/literature.py#L128-L129

This might cause the task to fire too early (before the record is commited), and retrieve the previous version from the DB. The solution is to move this to the `models_committed` receiver, like for disambiguation: https://github.com/inspirehep/inspirehep/blob/9281776185dfc3b363e0c900fd17523c0c5a9aad/backend/inspirehep/records/receivers.py#L44.

The same applies to ORCID (but is less critical, as we check the version there).

**Comment by drjova** [comment]
TECH NOTES:

* We should send to orcid and hal on `CREATE` and `UPDATE` in the receivers https://github.com/inspirehep/inspirehep/blob/master/backend/inspirehep/records/receivers.py#L20-L46

**Comment by michamos** [comment]
ORCID requires pushing on `DELETE` too.
