### ISSUE TITLE
Disambiguation raises NoRecordFound on deleted records

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspirehep#2010]
See https://sentry.inspirehep.net/inspire-prod/hep/issues/36303/events/72c5ae98ac0b404ba3a344b664c64571/

**Comment by MJedr** [comment]
**TECH NOTES**
In [`disambiguate_authors`](https://github.com/inspirehep/inspirehep/blob/24cfb453e60c60145208a78b21b7df66a01a7fe8/backend/inspirehep/disambiguation/tasks.py#L202) handle the `NoRecordFound` exception.
