### ISSUE TITLE
Cache info in the editor

### ISSUE THREAD

**Issue by StellaCh** [inspirehep/inspirehep#2013]
"when I re-open a record in the editor (I made changes and saved the record in the editor before)
it shows cached information, when I then try to save the record I get an error message.
I have to reload the web-page to get the current data."

**Comment by drjova** [comment]
TECH NOTES:
* On `412` status code error we should automatically refresh the editor here https://github.com/inspirehep/inspirehep/blob/master/record-editor/src/app/holdingpen-editor/holdingpen-save-button/holdingpen-save-button.component.ts#L183-L196

**Comment by oguzdemirbasci** [comment]
With this pr https://github.com/inspirehep/inspirehep/pull/2036, page is redirected to the detail view when the record successfully saved. If save is failed, user should refresh the page manually when they see the error message. I am closing this issue.
