### ISSUE TITLE
Claim button bug

### ISSUE THREAD

**Issue by StellaCh** [inspirehep/inspirehep#2018]
Curators reported that the Claim button in each paper doesn't work.

Check out details in: https://inspirehep.zulipchat.com/#narrow/stream/195298-experts/topic/Author.20claiming.20on.20NEW/near/244580708

**Comment by drjova** [comment]
@StellaCh we need more details here, what "Doesn't work means" do they get an error message?

**Comment by michamos** [comment]
request payload is wrong:
```
{"from_author_recid":1259096,"to_author_recid":1259096,"literature_recids":[]}
```
