### ISSUE TITLE
Search in report numbers should come after search for other identifiers

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspirehep#2023]
Report numbers can be ambiguous (same report number in several records), but they're currently treated on the same footing as arXiv ID/DOI in the reference matcher. Matching on report numbers should be changed to have lower priority, to prevent the matching from failing when the report number is ambiguous, but a DOI/arXiv ID is present. See also conversation in https://inspirehep.zulipchat.com/#narrow/stream/195298-experts/topic/searching.20report.20numbers/near/244282992.

**Comment by MJedr** [comment]
**TECH NOTES**
* Create a new config for report numbers in [here](https://github.com/inspirehep/inspirehep/blob/10e12d95c6c1acc03277a8c95b460604aa3ce841/backend/inspirehep/matcher/config.py#L31-L35)
* Register config [there](https://github.com/inspirehep/inspirehep/blob/10e12d95c6c1acc03277a8c95b460604aa3ce841/backend/inspirehep/matcher/api.py#L99) and add it to [this list](https://github.com/inspirehep/inspirehep/blob/10e12d95c6c1acc03277a8c95b460604aa3ce841/backend/inspirehep/matcher/api.py#L109) at the last position
