### ISSUE TITLE
Garbage collect stub authors with no papers

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspirehep#2034]
In the disambiguation process, we create a new stub author (having `stub: true` in the metadata) if there's no unambiguous match for a given signature. Manual intervention or a subsequent disambiguation run might remove the paper from that author profile, causing that author to have no associated papers. In the long term, these authors will pile up and cause noise in the authors collection. 

To avoid that, we should garbage collect stub authors. This can happen either periodically, or during disambiguation/claiming (but is more tricky to get right).

**Comment by MJedr** [comment]
**TECH NITES**
* Write a cli in a disambiguation module which will:
    - query all authors with `stub: true`
    - for every author it will check if it has any linked papers - if no, delete record
* in kuberneres add a cronjob which will run the task (similarly to [mailing cronjob](https://github.com/inspirehep/kubernetes/tree/master/hep/overlays/mail-jobs-weekly))
* add a cronjob to the [hep kustomisation file](https://github.com/inspirehep/kubernetes/blob/c383bbf91f1dd1b7b7cabc55b697d39febfdf8c7/hep/environments/prod/kustomization.yml#L24)
