### ISSUE TITLE
Add bookkeeping for core deselection

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspirehep#2057]
From https://inspirehep.zulipchat.com/#narrow/stream/195298-experts/topic/CORE.20.28de-.29selection/near/245676546.

Sometimes, papers tagged as CORE automatically because they've been crosslisted to a CORE arXiv category shouldn't actually be core. The change in the metadata can be handled manually, but there needs to be some way to handle the bookkeeping, namely:
* a list of candidate records that have been set automatically as CORE (so new arXiv records that have the right category), but are crosslisted to core categories instead of having it as their primary category (first element of `arvxiv_eprints.categories` is not `hep*`)
* for each, the same information as in the harvesting workflow regarding coreness (core prediction, core references, core keywords, etc.)
* a way of keeping track of which records have already been handled

@ksachs suggests having simply a copy of completed workflows, that can then be deleted.

**Comment by ksachs** [comment]
A simple copy is the minimal solution. 

Somehow we have to open that INSPIRE record in the editor:
1. cut-and-paste the arXiv-ID to the INSPIRE search & open that record in editor
    Works with simple copy of WF, is a bit slow and cumbersome
2. cut-and-paste the arXiv-ID to the search in the editor (which currently doesn't work)
    Needs cut-and-paste, but much faster than 1) since we don't have to open the editor for each record
3. a button to edit the corresponding INSPIRE record from that WF
    most convinient, but most likely not faster than 2) and more development (I guess)

**Comment by ksachs** [comment]
The WF-copy should be in `workflow_name=CORE_SELECTION` , not in `HEP`

**Comment by michamos** [comment]
@ksachs I was thinking of a new workflow, don't you want to distinguish easily between core selection and core deselection?

**Comment by ksachs** [comment]
That's fine too. As long as it is not `HEP`

**Comment by ksachs** [comment]
a search in the editor at least for recids, arxiv-IDs and DOIs might be useful in any case.

**Comment by MJedr** [comment]
**TECH NOTES**
* Create a new workflow when any workflow has the secondary categories. Copy required metadata and _extra_data inside a new workflow. The name should be `non-core-selection`.  The workflow should do nothing and be completed.
