### ISSUE TITLE
DESY parser does not strip auther id value

### ISSUE THREAD

**Issue by oguzdemirbasci** [inspirehep/inspirehep#2058]
For DESY workflows, author ORCID ids are incorrect. 

`https://orcidorg/0000-0001-7325-2274` should be `0000-0001-7325-2274`.

https://inspirehep.net/holdingpen/3174764

```
ValidationError: {u'value': u'https://orcidorg/0000-0001-7325-2274', u'schema': u'ORCID'} is not valid under any of the given schemas
```

**Comment by michamos** [comment]
@oguzdemirbasci there's nothing we can do here. All we're doing on our side is converting the metadata from MARCXML to JSON. This needs to be handled by @fschwenn.
