### ISSUE TITLE
link papers when creating new profile from BAI

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspirehep#2064]
Legacy had profiles (with BAI) with no associated records. There exist in the system as Literature records with a BAI but no linked record. Users/curators can create new author profiles for those, but upon creation the existing signatures in Literature records with that BAI don't get linked to the newly created author profile. We should fix that and automatically add the author record ref to the Literature record.

**Comment by MJedr** [comment]
**TECH NOTES**
1. Create a function that will take as an argument an author record. It should query db for all the papers where this author exists (by using his BAI). For every paper in the result set, assign the reference to this author.
1. On author create call the new function.
