### ISSUE TITLE
allow editing experiments and journals through editor

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspirehep#2068]
The editor works for these collections, but permissions are not set up correctly to allow saving the record. This should be fixed so curators can modify them (even if the editor has not been fully configured yet).

Current response:
```json
{
  "message": "You don't have the permission to access the requested resource. It is either read-protected or not readable by the server.", 
  "status": 403
}
```

**Comment by drjova** [comment]
TECH NOTES:
* Add https://github.com/inspirehep/inspirehep/blob/master/backend/inspirehep/records/config.py#L120-L122 to Journals and Experiements
