### ISSUE TITLE
Don't allow attaching HTML/JS/CSS to records

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspirehep#2080]
Currently we don't impose any restrictions on the type of files attached to a record. That causes issues when we expect a PDF but we get some publisher page instead (because we have been detected as a robot and banned) but also poses security issues as we serve the files using the `inspirehep.net` domain, so any page and script that we host has access to all associated secrets (e.g. cookies).

We should simply disallow these file types, as there is currently no real use for attaching them. This would catch problems and avoid the security issue.

**Comment by MJedr** [comment]
**TECH NOTES**
1. Check the mime type in the response headers [here](https://github.com/inspirehep/inspire-next/blob/52b1795c12df0a15bb9bf2daaa5e974d16233ed0/inspirehep/modules/workflows/utils/__init__.py#L325) and if it’s `HTML/JS/CSS` don’t attach the file.

**Comment by michamos** [comment]
I don't think that's a sufficient approach. We need to forbid these files from being attached to INSPIRE records, not merely to workflows, as files might be attached directly without being downloaded by workflows first (e.g. inputting the URL in the record editor).
