### ISSUE TITLE
Author list tool

### ISSUE THREAD

**Issue by drjova** [inspirehep/inspirehep#2106]
When appending authors to the list via the authorlist tool (so the box 'replace existing' is unticked):

Yhe authors are extracted in reverse alphabetical order before the author(s) that are already present. They should appear in alphabetical order after the authors already present in the record. (When you do 'replace existing' it works correctly)

![image](https://user-images.githubusercontent.com/4287772/128372075-bf145fb3-81a2-4b61-b2a1-818b523b395f.png)

**Comment by michamos** [comment]
same story for references, appending would be better than inserting at the beginning.

**Comment by michamos** [comment]
This requires changing `0` to `-` in https://github.com/inspirehep/inspirehep/blob/47ef8e69623f4598b389ed9e4d39b4d7d8d396aa/record-editor/src/app/shared/components/extract-actions/author-extract-actions.component.ts#L77 and https://github.com/inspirehep/inspirehep/blob/47ef8e69623f4598b389ed9e4d39b4d7d8d396aa/record-editor/src/app/shared/components/extract-actions/ref-extract-actions.component.ts#L66.

**Comment by drjova** [comment]
```this.jsonStoreService.updateIn(["authors"], (arr) => arr.push(author));```
