### ISSUE TITLE
make permission system more flexible

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspirehep#2123]
From https://inspirehep.zulipchat.com/#narrow/stream/195298-experts/topic/BaBar.20internal.20notes.20access

We currently have a 3-tiered permission system for literature-type records: public (`Literature` collection), hidden (not visisble by default), private (visible only to curators). The private collections however need to be accessible by selected groups of people. We should add for each private collection two different roles, one allowing to view/search records in that collection, and the other allowing also to edit records.

**Comment by drjova** [comment]
TECH NOTES:
* Permissions should be `name-of-collection-read` and `name-of-collection-read-write`
* Update [LiteraturePermissionCheck](https://github.com/inspirehep/inspirehep/blob/eb6fa8d303b2007adf1583971b98281d4f63756a/backend/inspirehep/access_control.py#L40) to check for permissions if the user has the role for this specific collection
* Update [SessionCatalogerPermission](https://github.com/inspirehep/inspirehep/blob/master/backend/inspirehep/records/config.py#L122)  to check for permissions if the user has the role for this specific collection
* Update [query_for_superuser_or_users](https://github.com/inspirehep/inspirehep/blob/master/backend/inspirehep/search/api.py#L188) to check for permissions if the user has the role for this specific collection
* Create a new mixin similar to [CatalogerCanEditMixin](https://github.com/inspirehep/inspirehep/blob/ba5fe0fdd9aa4daebad985376068487edccf995a/backend/inspirehep/records/marshmallow/common/mixins.py#L10) to check for permissions if the user has the role for this specific collection and replace `CatalogerCanEditMixin` [here]( https://github.com/inspirehep/inspirehep/blob/ba5fe0fdd9aa4daebad985376068487edccf995a/backend/inspirehep/records/marshmallow/literature/ui.py#L45)

**Comment by michamos** [comment]
I think you're missing the editor views in https://github.com/inspirehep/inspirehep/blob/master/backend/inspirehep/editor/views.py
