### ISSUE TITLE
Display students on advisor profile

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspirehep#2125]
From https://rt.inspirehep.net/Ticket/Display.html?id=1121227:

> [...] one important feature
that got lost along the way relative to the previous version was the "students"
of any given individual. The "advisor" is there, and I assume the information
on students is still in the underlying database.

> This is particularly useful to understand potential conflicts of interest
(e.g. for review panels) and facilities understanding some aspects of career
trajectories (e.g. which experiments people were on and in what context). Would
it be possible to add the "students" feature back in the new version?

As discussed in the ticket, this would require reliably linking the students to the advisors. Currently we don't really link to an author's advisors (there is no record ref to the advisor record) but generate a search for the name in the author display. @hoc3426 mentions that many `advisors` fields contain an `INSPIRE ID`, which could be used to more reliably link back to the advisor.

This probably also requires creating a new table to hold this relation.

**Comment by MJedr** [comment]
**TECH NOTES**
1. Create a new table students_advisors, which should contain: 
* student_id (record uuid),
* advisor_id (record uuid).
  Put an index on author_id column and advisor_id column.
2. Create a mixin which will: 
* prepare (generate) entries for table (by using $ref of the advisor in student record)
*  update table (put all the entries to the table).
*  delete all the entries from table. 
* hard delete all the entries from table. That mixing should be used in AuthorsRecord.
3. In AuthorsRecord, add a method to update relationships in the new table (update table method from mixin) and then call it in `create`.
4. Add a new field to ES schema for authors: `students` which will contain `name` and reference to student record.
5. In authors ES serializer add a new method that will populate `students` (for `preferred_name`, if it's not available use `name.value`).
6. Create a new method in AuthorsRecord that will take all the advisors if `full_name` or `preferred_name` changed. It should return uuids.
7. To reindex records affected by change, call the method from point 6 [here](https://github.com/inspirehep/inspirehep/blob/61348b82d55d950419daa9d5ced8436ef52e7aa2/backend/inspirehep/indexer/api.py#L28)

**Comment by michamos** [comment]
it would be good to add the `degree_type` to the table and ES too, so we can display the type of student. We potentially have this info for the `advisor` (not required): https://github.com/inspirehep/inspire-schemas/blob/8b0dd65c43c4e890e99b7c766250b995526abaee/inspire_schemas/records/authors.yml#L52.

**Comment by StellaCh** [comment]
Before deciding on a UI, can someone get some stats on the distribution of the number of students per advisor please?
