### ISSUE TITLE
make merger faster

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspirehep#2155]
See https://inspirehep.zulipchat.com/#narrow/stream/122202-devel/topic/slow.20merger

The merger is currently slow when performing rootless (`root={}`) merges of large records, causing requests to time out. This is mostly due to the deduplication of patches, which has been introduced in https://github.com/inveniosoftware-contrib/json-merger/commit/594107d4553444b8c9264ed1d082dd7b5ea3ce3c as a fix for duplicate `remove` patches and is quadratic because `dict`s/`set`s can't be used due to dealing with unhashable elements (`dict`s). As the underlying issue seems to affect only `remove` patches, we might be able to deduplicate only those instead of the full list, or if that's complicated first check if there are any `remove` patches to decide whether to deduplicate them or not.

Note that this requires reverting  https://github.com/inveniosoftware-contrib/json-merger/pull/72 as we're currently using an earlier version in prod due to issues with that PR (I couldn't find a tracking issue, @MJedr can you provide more info?)

**Comment by MJedr** [comment]
Here is the issue https://github.com/inspirehep/inspirehep/issues/1841#issuecomment-847887817. As far as I remember the problem was that in the newest version of `json-merger` we did a change which is taking the value even if it's empty (after processing by graph builder), so for example we had `raw_affiliations` empty in many workflows:
```
ipdb> root['authors'][0]['raw_affiliations']
[{u'value': u'Department of Physics, Brown University, Providence, RI, 02912, USA'}]
ipdb> head['authors'][0]['raw_affiliations']
[{u'value': u'Department of Physics, Brown University, 02912 Providence, USA'}]
ipdb> update['authors'][0]['raw_affiliations']
[{u'value': u'Department of Physics, Brown University, Providence, RI, 02912, USA'}]
ipdb> merged['authors'][0]['raw_affiliations']
[]
```

**Comment by MJedr** [comment]
**TECH NOTES**
* Take out remove patches to the other list [here](https://github.com/inveniosoftware-contrib/json-merger/blob/69331b1355231082d220ce5f44050ecc9b13fa77/json_merger/dict_merger.py#L173) (the patch is given as a first element of the `unified_patches` list) and dedupe them. Then join the list of the deduplicated `remove` patches and all the other patches.
