### ISSUE TITLE
Keep number of results in references

### ISSUE THREAD

**Issue by StellaCh** [inspirehep/inspirehep#2158]
In the literature detail page, when I have more than 25 references, I get the option to see more references per page. If I change the number of references I prefer to see per page, I'd like the system to remember this selection the next time I look for references.

When I do a literature search, then this selection is kept - it should be the same for references in the literature detail page.

**Comment by MJedr** [comment]
**TECH NOTES**
1. Create a new namespace for references: 
* define new namespace in constants.js
* create onReferencesQueryChange which will do:
```
  if (helper.isInitialQueryUpdate() || helper.hasQueryChanged()) {
    helper.fetchSearchResults();
  }
  ```
* add a config for that in config.js 
```
[REFERENCES_NS]: {
    persistedQueryParamsDuringNewSearch: defaultPersistedQueryParamsDuringNewSearch,
    onQueryChange: onReferencesQueryChange,
  }
```
2.  Add a new namespace to state.js with size and page
3. For query in ReferenceListContainer use a state.search.getIn([‘namespaces’, REFERENCES_NS, ‘query’]).
