### ISSUE TITLE
Display `imprints` for books

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspirehep#2171]
From https://inspirehep.zulipchat.com/#narrow/stream/195298-experts/topic/pubinfo.20for.20books/near/250475668:

Books often contain useful metadata in `imprints`, which is currently not displayed in the search results or detailed record view. We should improve that.

**Comment by StellaCh** [comment]
In the detailed page of the paper, under ISBN add a new line with the following information: 
Published **imprints.date** in **imprints.place** by **imprints.publisher** 

eg: 

> Published May 1, 2021 in Boca Raton by CRC Press

 for https://inspirehep.net/literature/1886833

**Comment by MJedr** [comment]
**TECH NOTES**
1. Create a new component `ImprintInfo` which will take imprint list as the argument and will generate 
Published **imprints.date** in **imprints.place** by **imprints.publisher**
2. Add the new component [here](https://github.com/inspirehep/inspirehep/blob/39bbacf372b720b6cfed7ce577f74abf72256dc5/ui/src/literature/containers/DetailPageContainer/DetailPageContainer.jsx#L193) and pass imprints from metadata

**Comment by michamos** [comment]
Example of record with two imprints: https://inspirehep.net/literature/659635.

**Comment by StellaCh** [comment]
Thank you!
@hanadikaleel The list of imprints should be connected with 'and'
