### ISSUE TITLE
Improve API experience for searches with > 10k results

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspirehep#2173]
Prompted by @hoc3426, see also https://inspirehep.zulipchat.com/#narrow/stream/195298-experts/topic/API.20results.20.3E.2010k/near/250503856.

Currently, the API doesn't give any visible hint that something is wrong when performing searches with > 10k results. Simply, no results are returned beyond that number and there is no `link` to go to the next page, so it's indistinguishable from the case where there are simply no longer results, unless you look at the number of total hits and compare the counts in `hits.total` with the total number of returned results.

This silent truncation of results is confusing. There are several options:

1. We could communicate somehow to the user that it's impossible to get more results with the current API, maybe by having a `next` link returning a 400 error with a clear error message.
2. Better, we could improve the API to use a different pagination mechanism and left the 10k result limit in the API. The current mechanism of `next` links is well-adapted to the recent [`search_after`](https://www.elastic.co/guide/en/elasticsearch/reference/current/paginate-search-results.html#search-after) option in the ES search API (docs only exist for very recent versions, but I've tested it and it seems to work with our current ES version). If you have a stable sort in the API such that the `sort` value returned is not shared by several documents (this requires using a unique ID such as the UUID or recid as a tie-breaker), you can simply pass the value of the last score on the current page to `search_after` to get the next page, indefinitely. This seems compatible with the `next` API links (if treated as opaque URLs, so we could have `?next=<base64-sort-value>` instead of `?page=<page-number>`) that we return, so wouldn't break the API, but would probably require some work on `invenio-records-rest`.

**Comment by tsgit** [comment]
I agree with the above 

Also, ideally enhancements of the API remain compatible with the existing interface.


Providing the `hits.total` is certainly important and useful --
usually whenever there is pagination of results and information on the total results I compare the counts when retrieving the full result set to ensure completeness (there are many possible sources for omissions -- implementation issues, sub-optimal handling of connection drops, json conversion errors, slice overlap or gap, unstable sort-order, db updates/refresh, ...).

**Comment by drjova** [comment]
We already returning 400 https://inspirehep.net/api/literature?page=10000

**Comment by michamos** [comment]
the problem is that the API for the last valid page doesn't tell you that there's more but can't show you.

**Comment by oguzdemirbasci** [comment]
TECH NOTES:

* Remove this line that is hiding the results after 10k. https://github.com/inspirehep/invenio-records-rest/blob/d79c5f6ed05560f423c6cb0390c7b33224c7883f/invenio_records_rest/views.py#L644

**Comment by michamos** [comment]
I don't think removing the line is correct. If there are 3 results, you don't want to display a `next` link, only in case you're not at the end yet.
