### ISSUE TITLE
URI Validation: URI inputs should be encoded to replace special characters with valid values.

### ISSUE THREAD

**Issue by oguzdemirbasci** [inspirehep/inspirehep#2185]
Our validator doesn't validate the following URI because of the character `φ`. 
http://caod.oriprobe.com/articles/61619219/Some_characterizations_for_the_exponential_φ_expan.htm

Browsers can automatically encode it, load the page and still show the special characters in the URL bar. So URIs with special characters can be passed to the validator and we need to replace them with the valid ASCII codes. For this example, the encoded URI should be like this:
http://caod.oriprobe.com/articles/61619219/Some_characterizations_for_the_exponential_%CF%86_expan.htm

Following code should work:
```Python
url = url.encode('utf-8')
url = urllib.parse.quote(url)
```

ASCII encoding reference:
https://www.w3schools.com/tags/ref_urlencode.asp

**Comment by michamos** [comment]
@oguzdemirbasci copy/pasting from the browser bar should already encode the URL behind the scenes as you mention. I'm not sure I understand the scenario that would cause the URL to be unencoded and hence invalid.

**Comment by oguzdemirbasci** [comment]
Yes, but It was the input for a workflow. I do not know how it is written there. Maybe not all browsers support it.

**Comment by michamos** [comment]
So looks like we should improve the form or the submission logic, rather than the record logic.

**Comment by oguzdemirbasci** [comment]
**TECH NOTES**
* Add a `transform` function into the `yup` validation schema for [these URLs](https://github.com/inspirehep/inspirehep/blob/master/ui/src/submissions/literature/schemas/sections/links.js) that encodes the valid URL inputs. ([Check out the documentation](https://github.com/jquense/yup#mixedtransformcurrentvalue-any-originalvalue-any--any-schema)).
* Use default URI encoding function of javascript `encodeURI()` in the transform function.

**Comment by michamos** [comment]
I don't think that's sufficient. You somehow need to detect whether the URL is already encoded, to avoid encoding it twice in case it is.

**Comment by MJedr** [comment]
> **TECH NOTES**
> 
> * Add a `transform` function into the `yup` validation schema for [these URLs](https://github.com/inspirehep/inspirehep/blob/master/ui/src/submissions/literature/schemas/sections/links.js) that encodes the valid URL inputs. ([Check out the documentation](https://github.com/jquense/yup#mixedtransformcurrentvalue-any-originalvalue-any--any-schema)).
> * In the transform function, decode the input URL with `decodeURI()` and compare to original. If it differs, original URL is already encoded and no need for any transform. Otherwise, encode the original URL with `encodeURI()`.

The given solution works only for submissions. If we want to fix it for editor/workflows we need to add encoding to inspire-schemas before validating the record.

**Comment by michamos** [comment]
This will be revisited in case it happens again.
