### ISSUE TITLE
Make the distinction between `Literature` and hidden collections more clear

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspirehep#2196]
See https://rt.inspirehep.net/Ticket/Display.html?id=1166423 and discussion in https://inspirehep.zulipchat.com/#narrow/stream/195298-experts/topic/CDS.20candidates.20on.20labs

We don't display records from hidden collections (`HAL Hidden`, `Fermilab`, etc.) which are not part of Literature in the default search results, but they are still publicly available, so people can end up there when following external links. This confuses users, so it would be good to make it more clear when records are not part of the main `Literature` collection.

**Comment by StellaCh** [comment]
In the literature detailed page of these records, display an alert message, similar to the one we used for closed jobs, see https://inspirehep.net/jobs/1899313.
The text should be: `This record is not part of the INSPIRE Literature collection. Learn more` 
On Learn more should link to the FAQ page

**Comment by MJedr** [comment]
**TECH NOTES**
1. Create a component `LiteratureCollectionBanner` similar [to this](https://github.com/inspirehep/inspirehep/blob/ba5fe0fdd9aa4daebad985376068487edccf995a/ui/src/jobs/components/JobStatusAlert.jsx)
2. Put it in [`LiteratureDetailedContainer`](https://github.com/inspirehep/inspirehep/blob/ba5fe0fdd9aa4daebad985376068487edccf995a/ui/src/literature/containers/DetailPageContainer/DetailPageContainer.jsx)
