### ISSUE TITLE
Scale citation-count graph for partial years

### ISSUE THREAD

**Issue by agbuckley** [inspirehep/inspirehep#2197]
The citation-count vs calendar year graph is a nice feature, but as the y-axis shows number rather than number density, there is usually an unrepresentative dip in the current year, especially in its early months, e.g.:
![image](https://user-images.githubusercontent.com/926164/132674205-3e629113-050e-45ee-bf6f-dc0cb0303d6b.png)

Less obvious is the suppression in the year of publication, e.g. a publication written in December will not pick up many citations in that calendar year. Overall, the graph does not show "citations per year" as captioned, but "citations by calendar year".

A nice solution would be to show the density instead, or as a (preferred?) option, e.g. dividing the number of citations in each calendar year by the fraction of that year in which the paper was "active", i.e. the months since the first submission in the initial year, and the months elapsed in the current year (and the combination of the two for this-year publications). This would more accurately show the impact trajectory of the research, which is presumably the real intention of the feature.

**Comment by michamos** [comment]
Hi @agbuckley, thanks for the detailed report. I agree things are currently a bit confusing for the current year (and the publication year to a lesser extent) and there is room for improvement.

We've had some internal discussion regarding possible ways to improve the display. The big advantage of the current graph is that it's easy to understand what are the underlying data, even if the current year is not really representative. If we switched to more advanced things like citation density (or replace the current year's citations by a convex combination of the current year and last year's citations of the form to avoid the large variability at the beginning of the year), it would make the graph harder to interpret. So this requires more work regarding data visualization to convey the information clearly.

**Comment by karolina-siemieniuk-morawska** [comment]
Done in: https://github.com/cern-sis/issues-inspire/issues/238
