### ISSUE TITLE
Error on save - invalid data

### ISSUE THREAD

**Issue by StellaCh** [inspirehep/inspirehep#2206]
When I try to save my changes in the editor I get an error message for invalid data, that I don't understand. 

The problem is that when there is a validation error on save (from the validation in `InspireRecord.update`), we only include the exception's message, but that is often not sufficient for a human to locate the error, and we display this uninformative message as a notification.

In the workflows, we manage to display the validation errors in a nice way. We should do the same thing for errors on save on `hep`. The notification can stay, but we should also add the error to the error panel and attach it to the proper place.

**Comment by drjova** [comment]
TECH NOTES:
* On [records/config.py](https://github.com/inspirehep/inspirehep/blob/master/backend/inspirehep/records/config.py) add an error handler as the example [here](https://github.com/inspirehep/invenio-records-rest/blob/master/invenio_records_rest/config.py#L135-L137) to catch `ValidationError` and return the validation errors like we do on [workflows](https://github.com/inspirehep/inspire-next/blob/master/inspirehep/modules/workflows/views.py#L460-L464)
