### ISSUE TITLE
Concurrency in the editor

### ISSUE THREAD

**Issue by StellaCh** [inspirehep/inspirehep#2207]
It often happens that 2 curators are in the record editor of the same record. 
What should happen when one saves the record? How to handle changes in the record?

**Comment by michamos** [comment]
after discussing with the curators, it seems the biggest issue is not concurrent edits by another curator, but automated processes running after saving the record (e.g. author disambiguation).

**Comment by drjova** [comment]
TECH NOTES:

EDITOR:
* Use the `editor-lock:control_number@version_id` as a key that expires after configurable time and add a message to `editor`: `{user_email} has opened the record at {time} and hasn't saved yet. Your or their modifications might get lost.` on https://github.com/inspirehep/inspirehep/blob/master/backend/inspirehep/editor/views.py#L68 
* Get all the locks for the specific record and pass them to the payload `locks`
* Create an endpoint to clear the lock of the editor on Save, on browser [close window event and on the warning when you trying to leave the browser with unmodified changes](https://github.com/inspirehep/inspirehep/blob/3c55ba49a38c0af0e073c702957ade5b83808962/record-editor/src/app/core/services/dom-utils.service.ts).
* On the editor read the `locks` payload and display notifications accordingly 

HAL_PUSH:
* Add the `editor-lock:control_number@version_id` as a key that expires after configurable time  and add to `hal_push`: `{task_name} has been scheduled at {time} and hasn't finished yet. Your modifications might get lost.`
* When the task finishes clear the lock

AUTHOR DISAMBIGUATION:
* In the receivers add the `editor-lock:control_number@version_id` as a key and add to `disambiguation`: `{task_name} has been scheduled at {time} and hasn't finished yet. Your modifications might get lost.`
* Pass the `version_id` to the task
* When the task finishes clear the lock
