### ISSUE TITLE
Put inspire-classifier into production

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspirehep#2235]
Currently we're running the very old core classifier in the workflows which is part of beard-server: https://github.com/inspirehep/beard-server/tree/master/beard_server/modules/predictor.

For quantum physics, we'll need to retrain the classifier so it also treats those papers as core. We want to use the newer [inspire-classifier](https://github.com/inspirehep/inspire-classifier) for that. It's currently an HTTP microservice, but inference cant take 10s of seconds, so it might be better to use a celery-based approach instead (as @benjamin-bergia  suggested).

**Comment by drjova** [comment]
Supersede by https://github.com/inspirehep/kubernetes/issues/434
