### ISSUE TITLE
Disambiguate records that are not disambiguated

### ISSUE THREAD

**Issue by drjova** [inspirehep/inspirehep#2250]

**Comment by drjova** [comment]
@benjamin-bergia could we plan for next sprint to import the latest PROD data to QA?

**Comment by benjamin-bergia** [comment]
Yeah

**Comment by MJedr** [comment]
**TECH NOTES**
* ensure that the dataset on qa is updated with prod data.
* query the records that are not disambiguated (using es scan).
* for each record in the result dataset: remove `uuid` from an author and save the record.

**Comment by MJedr** [comment]
It would be nice to have it as a curation script in order to run it as a k8s job

**Comment by drjova** [comment]
- [ ] @drjova will check qa 
- [ ] merge PR author name
