### ISSUE TITLE
strip trailing whitespace

### ISSUE THREAD

**Issue by StellaCh** [inspirehep/inspirehep#2269]
This is an issue for mainly the url field in the editor, but if it could be applied to more fields it would be ideal

Request from Fermilab:

Our catalogers are constantly annoyed by urls not being accepted in the editor because they have included whitespace (usually at the end). I think this might also be a problem for other fields and perhaps even in the submission forms. Is there any way leading and trailing whitespace could simply be stripped (and even better an multiple white space inside a field, e.g. abstract, reduced to a single whitespace)?

**Comment by drjova** [comment]
TECH NOTES:
* Add `onValueChange` https://github.com/inspirehep/inspirehep/blob/master/record-editor/src/app/shared/config/hep/core.config.ts#L148-L150 for the url fields in all the collections

**Comment by michamos** [comment]
This should be applied to all fields in the editor, not only URLs.
