### ISSUE TITLE
Automatically assign categories to journals

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspirehep#2273]
From https://inspirehep.zulipchat.com/#narrow/stream/195298-experts/topic/QIS/near/258521117

Some of the journals we receive exclusively contain papers related to a single or a couple of INSPIRE categories, so we could automatically assign them to all the papers in that journal.
For *new* records, after journal title normalization, we should add an extra step in the workflow that adds to the record in the workflow `inspire_categories.term` from the journal record.

**Comment by drjova** [comment]
TECH NOTES:
* If it's a new record on [normilize journals](https://github.com/inspirehep/inspire-next/blob/bf4209939be34548cc5ab733c5e1c61b458e6738/inspirehep/modules/workflows/tasks/actions.py#L575) get the `inspire_categories` and save them to `extra_data.journal_inspire_categories`.
* After the [branch](https://github.com/inspirehep/inspire-next/blob/44e7b97dec4282508800ef17989cbd452b20ac09/inspirehep/modules/workflows/workflows/article.py#L390-L417) get the `extra_data.journal_inspire_categories` and add them to `inspire_categories`
