### ISSUE TITLE
Move flaky test to integration-async

### ISSUE THREAD

**Issue by MJedr** [inspirehep/inspirehep#2277]
[This test](https://github.com/inspirehep/inspirehep/blob/3c55ba49a38c0af0e073c702957ade5b83808962/backend/tests/integration/indexer/test_cli.py#L209) is flaky and it fails very often. The reason is probably that we don't wait until all the indices are created. Moving it to integration-async (and retrying in case of failure) should fix it.

**Comment by michamos** [comment]
Is this done @MJedr?

**Comment by MJedr** [comment]
yes
