### ISSUE TITLE
Create a static maintenance page.

### ISSUE THREAD

**Issue by benjamin-bergia** [inspirehep/inspirehep#2283]
Write a single file, static maintenance page to put up during major outages or maintenance when most of inspire is unresponsive/unavailable.

**Comment by benjamin-bergia** [comment]
Just a reminder to myself https://shami.blog/2021/07/maintenance-pages-with-haproxy/

**Comment by drjova** [comment]
* In the inspirhep repo create a new maintenance directory
* Create an HTML page with the graphic from https://inspirehep.net/static/media/404.73e5fcae.svg 
* Create a docker image with nginx
