### ISSUE TITLE
Add new categories to submission form

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspirehep#2284]
We need to add `Condensed Matter` and `Quantum Physics` to the Literature submission form, which was overlooked in #1554.

**Comment by MJedr** [comment]
**TECH NOTES**
Add new categories [here](https://github.com/inspirehep/inspirehep/blob/5f1eea698a571037c0df02992e9167c0096c3151/ui/src/submissions/common/schemas/constants.js#L182)
