### ISSUE TITLE
Run inspire-classifier in the workflows

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspirehep#2299]
After `inspire-classifier` has been trained and deployed, we need to run it in the workflows instead of the old core-guesser. There is a previous PR from the first attempt at running the classifier in prod that could be revived: https://github.com/inspirehep/inspire-next/pull/3703.

**Comment by drjova** [comment]
TECH NOTES:
* [ ] Add an init step to download the latest model on k8s
* [ ] Take the PR and fix what is broken
