### ISSUE TITLE
handle current emails in author submission form

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspirehep#2309]
From https://inspirehep.zulipchat.com/#narrow/stream/195298-experts/topic/No.20.22current.22.20for.20emails.20in.20submission.20form, it looks like the `current` flag is not being set in the author submission form for emails. We should update the form UI and logic to also handle the `current` `True`/`False` distinction correctly.

**Comment by drjova** [comment]
TECH NOTES:
* Add a current checkbox next to the emails (similar to the institution history)
* Add in the schema `current` https://github.com/inspirehep/inspirehep/blob/master/ui/src/submissions/authors/schemas/author.js#L38 
* Normal users are not allowed to remove emails (only superadmins and curators)
* Update https://github.com/inspirehep/inspirehep/blob/master/backend/inspirehep/submissions/marshmallow/author.py#L155 and add the flag current
*
