### ISSUE TITLE
Sort literature descending/ascending

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspirehep#2333]
Several users have been asking for a way to sort the literature results with the least recent papers at the top. This ordering is sometimes required when producing lists of papers. Additionally, the sort should be stable, so the results shouldn't change ordering based on the shard receiving the request or on the index order when remapping (so `_doc` shouldn't be used). We need to 

* add a new option to the sort order dropdown named `Least recent` which performs the same ordering as `Most recent` but in the opposite order
* make sure the search is always stable for the `records-hep` index (for all sort orders), easiest solution is probably adding `_id` (not sure it's possible) or `control_number` as a tie-breaker.

**Comment by drjova** [comment]
@michamos we don't understand the reason of the `tie-breaker`, they will not be any issue in `records-hep` index to sort by  `earliest_date`

**Comment by MJedr** [comment]
**Tech notes**
In [records config](https://github.com/inspirehep/inspirehep/blob/master/backend/inspirehep/records/config.py#L602-L607) add option:
* leastrecent - sort by earliest date

**Comment by michamos** [comment]
> @michamos we don't understand the reason of the `tie-breaker`, they will not be any issue in `records-hep` index to sort by `earliest_date`

There can be issues if two different records share the same `earliest_date`, then the ordering is "random" (depends on which shard the search is performed on, which is controlled by the [`preference` value](https://www.elastic.co/guide/en/elasticsearch/reference/7.16/search-search.html#search-preference) set to some hash of user IP and user agent by invenio), so it's not stable.

**Comment by michamos** [comment]
`Least recent` should be the second option, right after `Most recent`.

**Comment by MJedr** [comment]
@michamos Here's the PR for it https://github.com/inspirehep/inspirehep/pull/2338
