### ISSUE TITLE
Number of search results is not persisted when going directly to search page

### ISSUE THREAD

**Issue by MJedr** [inspirehep/inspirehep#2339]
When you enter directly to the literature search page by url (so `inspirehep.net/literature) the number of results is reseted by url because base query is used which displays 25 results. The same thing happens for references in detailed view, if you'll go directly to the paper the number of results is reseted to 25.

**Comment by michamos** [comment]
We should also persist the number of search results for embedded literature searches and other collections (ideally a unique saved setting that is valid for all of those).
