### ISSUE TITLE
don't allow `00` in PartialDate and fix experiment records

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspirehep#2340]
Currently, the `PartialDate.loads` method will accept dates of the form `2022-01-00`, which should actually be invalid. It needs to be modified to have extra validation and reject these dates.

Once that is done, we need to check all dates in existing experiment records to make sure they do not appear and fix them by removing the `-00` in case they do (due to lack of config of the experiment record editor, actual partial dates were treated as invalid and this kind of dates were used).

**Comment by MJedr** [comment]
**Tech notes**

Add [here](https://github.com/inspirehep/inspire-utils/blob/4f89d20b4543cc4aca7571fb1aaf464d8190df52/inspire_utils/date.py#L108) check if day is not `0` or `00`

**Comment by drjova** [comment]
@MJedr did you run the script to fix the existing ones?
