### ISSUE TITLE
date searches should be intepreted as ranges

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspirehep#2345]
From https://rt.inspirehep.net/Ticket/Display.html?id=1210605

Searches like `de 2020` don't get translated into range queries, unlike what happens for `d 2020`, so it only returns records with a literal `2020` as earliest date, but not things like `2020-06-14`. We need to fix that to make the query parser interpret date searches (that is, in configured fields representing dates) as range queries.

**Comment by MJedr** [comment]
**TECH NOTES**
add `self.KEYWORD_TO_ES_FIELDNAME['date-edited']`[here](https://github.com/inspirehep/inspire-query-parser/blob/16063982aefe28f32a48daa38279d664cf84e083/inspire_query_parser/visitors/elastic_search_visitor.py#L723-L724)
