### ISSUE TITLE
allow searching journal titles with spaces

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspirehep#2359]
The journal name abbreviation scheme we use doesn't put spaces between abbreviated words, e.g. `Phys.Rev.D`. The standard ES tokenizer doesn't start new tokens for `.`, so searching for `Phys. Rev. D` doesn't work, neither in `_all` or in `publication_info.journal_title.raw` (which is used for `j` searches).

We should fix it so that searching for `Phys. Rev. D` works, either by ~~changing the tokenizers (but that might have other unwanted effects) or by~~ explicitly indexing the variant with spaces.

**EDIT** after discussion, the better solution is to index to a new `text` field both variants (straight name and variant with extra spaces after the punctuation) and copy that field to `_all` and use it for the `j` search.

**Comment by MJedr** [comment]
**TECH NOTES**
Add [this normalizer](https://github.com/inspirehep/inspirehep/blob/ba3d3129ff31a6b009ce2a7aa562e3b8a02a24fb/backend/inspirehep/search/mappings/v7/records/journals.json#L251-L256) (without lowercase filter) to `journal_title` field in hep schema [here](https://github.com/inspirehep/inspirehep/blob/ba3d3129ff31a6b009ce2a7aa562e3b8a02a24fb/backend/inspirehep/search/mappings/v7/records/hep.json#L1031)

**Comment by drjova** [comment]
TECH NOTES:

Inspirehep

* Create a new field in the mappings `journal_title_variants` 
* On indexing create a new field `journal_title_variants` https://github.com/inspirehep/inspirehep/blob/master/backend/inspirehep/records/marshmallow/literature/es.py#L63 and add the `journal_title` and `journal_title` with spaces in the punctuation

inspire-query-parser

* Change https://github.com/inspirehep/inspire-query-parser/blob/bce7704864be3b493a986ae8e9c4b30133fd4353/inspire_query_parser/visitors/elastic_search_visitor.py#L80 to use the new `journal_title_variants` 


Afterwards, we have to remap and reindex.
