### ISSUE TITLE
Improve `keywords` comparator

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspirehep#2361]
From https://inspirehep.zulipchat.com/#narrow/stream/195298-experts/topic/merge.20conflict/near/270559340

We currently cause spurious manual merge conflicts for `keywords`. It seems that the comparator we use doesn't take the `schema` into account.

**Comment by MJedr** [comment]
**TECH NOTES**
* Add a new comparator `SchemaValueComparator` which will take into account `schema` and `value` [here](https://github.com/inspirehep/inspire-json-merger/blob/2e87ec5a0f86d4f12a29b24e06aa6e45879831a7/inspire_json_merger/comparators.py#L112)
* Use a new comparator for `keywords` [here](https://github.com/inspirehep/inspire-json-merger/blob/2e87ec5a0f86d4f12a29b24e06aa6e45879831a7/inspire_json_merger/comparators.py#L149)
