### ISSUE TITLE
Add `Unknown` to `Subject` facet

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspirehep#2363]
Currently, under the `Subject` facet in literature, we only display records that have `inspire_categories`. However, we have a large number of records without that field. In order to make it more clear that the facet is not exhaustive, we need to add a [`missing`](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html#_missing_value_5) option to the `terms` aggregation to count records without category under the `Unknown` value. When selecting the checkbox, only records without a category should remain in the search.

**Comment by drjova** [comment]
@michamos is it just for Literature facets? Or also the embed searches with literature?

**Comment by michamos** [comment]
All `Subject` facets we have everywhere.
