### ISSUE TITLE
Don't fuzzy match arXiv with arXiv

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspirehep#2377]
From https://inspirehep.zulipchat.com/#narrow/stream/195298-experts/topic/Matching.20algorithm/near/271800029:

When the fuzzy matcher matches an incoming arXiv record with an existing arXiv record (necessarily with a different arXiv ID, otherwise it's an exact match), the match is almost always wrong and it's very rare that we merge two arXiv records. That's confusing for curators. We should add a validator for the fuzzy matcher that ignores matches where both records have `arxiv_eprints.value`s that don't intersect.

**Comment by MJedr** [comment]
**TECH NOTES**
* In matcher [api](https://github.com/inspirehep/inspire-matcher/blob/e7854a11e157109fac989add0889d60cf89e7f65/inspire_matcher/api.py#L37-L39) change this function to accepts lists and then [here](https://github.com/inspirehep/inspire-matcher/blob/e7854a11e157109fac989add0889d60cf89e7f65/inspire_matcher/api.py#L102) validate hits with each validator from the list
* Add [a validator](https://github.com/inspirehep/inspire-matcher/blob/master/inspire_matcher/validators.py) which will check if `arxiv_eprints.value` doesn't intersect

**Comment by nooraangelva** [comment]
To add a validator I need to create a separate function to the file you linked right? Is there a certain name it has to have? Or do I just add the validation to an existing validator function? 
Would [this(https://github.com/inspirehep/inspire-matcher/pull/71)] be close to the wanted solution?
