### ISSUE TITLE
Replace Piwik with Matomo

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspirehep#2391]
We're currently using a non-privacy compliant Piwik instance which collects IP addresses. We need to switch to Matomo intsead. There has been some contact with Pete Jones in November to obtain a Matomo instance but we didn't follow up. We need to get the Matomo instance and set the integration up with INSPIRE.

**Comment by nooraangelva** [comment]
**TECH NOTES**

- Piwik has changed its name to Matomo (so it's only about updating to a high enough version)
- The newest version of Matomo is 4.8.0
- Some methods have been deprecated, but mostly the name has only changed
- same goes for classes and files
- some old browser versions are not supported ( IE7 and older, Firefox 3 and older)
- It is changing its frontend framework currently from AngularJS to Vue
- Some APIs have been deprecated and removed (ex. Referrers.getKeywordsForPageUrl and Referrers.getKeywordsForPageTitle)

**Comment by drjova** [comment]
https://github.com/inspirehep/inspirehep/blob/master/ui/src/tracker.js

**Comment by nooraangelva** [comment]
**TECH NOTES**

```trackEvent``` hasn't been changed or deprecated

**Comment by drjova** [comment]
Now it's accessible at https://webanalytics.web.cern.ch
