### ISSUE TITLE
add `preprint_date` as default field in editor

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspirehep#2396]
`preprint_date` should be displayed by default in the Literature record editor, even if it's empty.

**Comment by drjova** [comment]
TECH NOTES:

* Add `preprint_date` in `alwaysShow` list https://github.com/inspirehep/inspirehep/blob/448fbe8b5e8f76e6c667627cbbf2c42583e69f61/record-editor/src/app/shared/config/hep/core.config.ts#L86-L110
