### ISSUE TITLE
Claiming: As a user claim in different profile

### ISSUE THREAD

**Issue by drjova** [inspirehep/inspirehep#2403]
## Different profile

When a user is logged in and has a profile but the profile they're on is not theirs.

* Don't display the unclaimed flags
* Display the claim menu at the top and the checkboxes on every paper
* Add claim menu on every paper
* All claim menus only contains "Move to my profile" option
* When clicking on the "Move to my profile" menu entry, for every paper to be claimed, there are two possible cases:
*  If the paper is allowed to be claimed (see further), it will claim the paper to the profile of the currently logged in user (not the profile the user is currently on)
*  If not allowed, claiming generates an RT ticket in the AUTHORS_claim_manual RT queue (single ticket for the whole claiming action containing details of all papers that were not processed automatically) and a message is displayed to the user explaining that (some of) the claims will be reviewed by a curator (See further for the ticket contents).

## When are users allowed to claim papers from other profiles

* If the paper is currently unclaimed, AND
* The names are compatible, namely there is a last name in common between the signature that the user wants to claim and the names (including variants) in the user profile

## Notification messages

The success messages that are displayed on success in the notification depend on the case:
* `This is my paper`: All selected papers will be claimed to your profile.
* `This is not my paper`: All selected papers will be removed from your profile.
* `Move to my profile`: 
    - All claims are allowed: All selected papers will be moved to your profile.
    - Some claims are not allowed: Some claims will be reviewed by our staff for approval.
* For curators, keep the current message

https://github.com/inspirehep/inspirehep/issues/2354

**Comment by MJedr** [comment]
* In backend add a field `can_claim` in ui serialiser (along with the method) which will check names compatibility
* Create a new action [similar to this one](https://github.com/inspirehep/inspirehep/blob/ba5fe0fdd9aa4daebad985376068487edccf995a/ui/src/authors/components/AssignAction.jsx#L35-L70) and adjust dropdown inside and call it `AssignActionDifferentProfile`.
