### ISSUE TITLE
Claiming: As a user that has no profile, claim a paper

### ISSUE THREAD

**Issue by drjova** [inspirehep/inspirehep#2404]
## Special case: no profile

When a user is logged in but there is no author record containing his ORCID.

* Don't display the unclaimed flags
* Display the claim menu at the top and the checkboxes on every paper
* Add claim menu on every paper
* The claim menus are not clickable and display the following message on hover: "There is no profile associated to your account. Please contact us at authors@inspirehep.net.", with a clickable email address. The email has a prepopulated title: "Profile association for {orcid}" and body "[Explain the situation here]".

## When are users allowed to claim papers from other profiles

* If the paper is currently unclaimed, AND
* The names are compatible, namely there is a last name in common between the signature that the user wants to claim and the names (including variants) in the user profile

## RT ticket example

```
Title: Claims by user {preferred_author_name} require curator action

The following claims performed by author {author_profile_url} were not handled automatically and require manual intervention.

Names in profile:
* {name_1}
* {name_2}
[etc.]

Already claimed:
* {paper_url_1} is already claimed to {author_url_1} with name "{author_name_1}"
* {paper_url_2} is already claimed to {author_url_2} with name "{author_name_2}"
[etc.]

Incompatible names:
* {paper_url_A} is in profile {author_url_A} and has signature "{signature_full_name_on_paper_A}"
* {paper_url_B} is in profile {author_url_B} and has signature "{signature_full_name_on_paper_B}"
[etc.]
```

https://github.com/inspirehep/inspirehep/issues/2354

**Comment by MJedr** [comment]
**TECH NOTES**
* add a new context for that case that will check if user is `loggedIn`.
* create a new component (`AssignNoProfileAction`) for claiming menu, it doesn't need to have `onAssign` function and any menu items, it has to be always disabled with a tooltip `"There is no profile associated to your account. Please contact us at [authors@inspirehep.net](mailto:authors@inspirehep.net)."`.
* Add an option `disabled` to the `PublicationsSelectAllContainer` and disable the checkbox in `PublicationsSelectAll` if it's set to true.
* Pass also `disabled` prop to `PublicationSelectContainer` [here](https://github.com/inspirehep/inspirehep/blob/c92c6b79f6c6405c4474dbcdb2d66d9e77fd7375/ui/src/authors/containers/PublicationSelectContainer.jsx#L11).
* if user is logged in:
    - in LiteratureItem add a new menu [here](https://github.com/inspirehep/inspirehep/blob/c92c6b79f6c6405c4474dbcdb2d66d9e77fd7375/ui/src/literature/components/LiteratureItem.jsx#L106) if the new context is true
    - In LiteratureSearchContainer add a new menu [here](https://github.com/inspirehep/inspirehep/blob/c92c6b79f6c6405c4474dbcdb2d66d9e77fd7375/ui/src/literature/containers/LiteratureSearchContainer.jsx#L114) and add `disabled` prop for checkboxes [here](https://github.com/inspirehep/inspirehep/blob/1de6ad5869aa79f8dba0fd0eae652689abf5a075/ui/src/literature/containers/LiteratureSearchContainer.jsx#L158) and [here](https://github.com/inspirehep/inspirehep/blob/1de6ad5869aa79f8dba0fd0eae652689abf5a075/ui/src/literature/containers/LiteratureSearchContainer.jsx#L990) if the context is true
