### ISSUE TITLE
Fulltext: update query parser to work with the fulltext field

### ISSUE THREAD

**Issue by drjova** [inspirehep/inspirehep#2437]
In query parser we should keep supporting the keyword `fulltext FCC `.

**Comment by MJedr** [comment]
**TECH NOTES**
Add [here](https://github.com/inspirehep/inspire-query-parser/blob/25e496dd128bba3a8d066ccb8e64eaa0b287fe06/inspire_query_parser/visitors/elastic_search_visitor.py#L91) a key-value pair which will map `fulltext` to `documents.attachment.content`
