### ISSUE TITLE
Celery requeue tasks that are failing

### ISSUE THREAD

**Issue by drjova** [inspirehep/inspirehep#2442]
Celery requeue tasks that are failing

**Comment by MJedr** [comment]
**TECH NOTES**
Add [`Reject(requeue=True)`](https://docs.celeryq.dev/en/master/userguide/tasks.html?highlight=Reject#reject) [here](https://github.com/inspirehep/inspirehep/blob/683a7c33c2d62445d2236ae17eae7b05f4787481/backend/inspirehep/celery.py#L28) for other kinds of exception
