### ISSUE TITLE
Fix empty `documents` or `figures` from submissions

### ISSUE THREAD

**Issue by drjova** [inspirehep/inspirehep#2455]
We are having several errors like the following:

```

On instance[u'documents']:
    []
```
Example: https://inspirehep.net/holdingpen/3998554

**Comment by MJedr** [comment]
**TECH**

* [Here](https://github.com/inspirehep/inspire-next/blob/a1e6356e2ed30a764825d6e5fa875a16efa2d3e0/inspirehep/modules/workflows/tasks/arxiv.py#L206) check if figures are empty, if they are remove `figures` key from wf object.
* [Here](https://github.com/inspirehep/inspire-next/blob/9b3a14b623ec8673a8f9af1a3438a594e907918d/inspirehep/modules/workflows/tasks/arxiv.py#L103) and [here](https://github.com/inspirehep/inspire-next/blob/42183bdfb7f4a73b0c76f42eed1e6cb6ba56fb08/inspirehep/modules/workflows/tasks/actions.py#L414) check if document array is empty, if it is remove `documents` key from wf obj.
