### ISSUE TITLE
prometheus exporter for celery

### ISSUE THREAD

**Issue by drjova** [inspirehep/inspirehep#2467]
Add prometheus exporter for celery https://github.com/danihodovic/celery-exporter

It will need a sidecar on rabbitmq

**Comment by MJedr** [comment]
**TECH NOTES**

* put that in [config.py](https://github.com/inspirehep/inspirehep/blob/25a09cad3fb5cd59cc3d6f4238963103e684671a/backend/inspirehep/config.py#L150)
```
# In settings.py
CELERY_WORKER_SEND_TASK_EVENTS = True
CELERY_TASK_SEND_SENT_EVENT = True
```
* in k8s repo in [stateful set for rabbitmq](https://github.com/cern-sis/kubernetes/blob/dddbba29af9198b9089e995730c54cd6876c0706/rabbitmq/statefulset.yml#L48) add a container based on `danihodovic/celery-exporter` image
